### ISSUE TITLE
NoiseTorch sometimes fails to load into PulseAudio when running as a snap

### ISSUE THREAD

**Issue by lawl** [lawl/NoiseTorch#1]
There is currently a race in canonicals snap mediator module in pulseaudio.

Issue here: https://bugs.launchpad.net/ubuntu/+source/pulseaudio/+bug/1886854

**Comment by Spurlos** [comment]
Bug fix has been released recently.
https://bugs.launchpad.net/ubuntu/+source/pulseaudio/+bug/1886854/comments/8
> This bug was fixed in the package pulseaudio - 1:13.99.2-1ubuntu2.1

Was it the last bug holding you from releasing the snap package?

**Comment by lawl** [comment]
Yes, as far as i'm aware. But pipewire currently has higher priority than dealing with snapcraft. I'll reevaluate if i'll provide a snap once the pipewire stuff is done.

This issue can be closed though i suppose, as the bug is fixed.
