### ISSUE TITLE
What's going on?

### ISSUE THREAD

**Issue by PreciousWarrior** [lawl/NoiseTorch#1]
why have you deleted all the issues? what is the security vulnerability? can we see the code?

**Comment by mritunjaymusale** [comment]
He could have atleast kept the uninstall instructions

**Comment by smaftoul** [comment]
Seems it moved to https://github.com/noisetorch/NoiseTorch

**Comment by lawl** [comment]
added removal instructions i don't recommend using that mentioned fork
