### ISSUE TITLE
I don't hear any difference at all

### ISSUE THREAD

**Issue by T4O2M0** [lawl/NoiseTorch#10]
Basically title, I am on fedora kde respin, and when on at max and mic switched to noise torch it picks up just as much sound as not, it will still pick up a person about 6 feet away talking around normal volume. This is the mic i have: https://fifinemicrophone.com/collections/microphones/products/usb-microphone-with-volume-control-k669-669b

**Comment by lawl** [comment]
Can you provide the `/tmp/noisetorch.log` log file? Additionally can you start the application you tested noisetorch with (so that it is recording) and then run `pacmd list-sources` and give me the output?

**Comment by T4O2M0** [comment]
Here's the log file: 
[noisetorch.log](https://github.com/lawl/NoiseTorch/files/4935967/noisetorch.log)

And I tested it with discord

And here's the pacmd list-sources:
[teefourty@localhost ~]$ pacmd list-sources
2 source(s) available.
  * index: 0
        name: <alsa_input.usb-0c76_USB_PnP_Audio_Device-00.mono-fallback>
        driver: <module-alsa-card.c>
        flags: HARDWARE HW_MUTE_CTRL HW_VOLUME_CTRL DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
        state: RUNNING
        suspend cause: (none)
        priority: 9040
        volume: mono: 65536 / 100% / 0.00 dB
                balance 0.00
        base volume: 19944 /  30% / -31.00 dB
        volume steps: 65537
        muted: no
        current latency: 0.00 ms
        max rewind: 0 KiB
        sample spec: s16le 1ch 48000Hz
        channel map: mono
                     Mono
        used by: 1
        linked by: 1
        configured latency: 30.00 ms; range is 0.50 .. 2000.00 ms
        card: 0 <alsa_card.usb-0c76_USB_PnP_Audio_Device-00>
        module: 6
        properties:
                alsa.resolution_bits = "16"
                device.api = "alsa"
                device.class = "sound"
                alsa.class = "generic"
                alsa.subclass = "generic-mix"
                alsa.name = "USB Audio"
                alsa.id = "USB Audio"
                alsa.subdevice = "0"
                alsa.subdevice_name = "subdevice #0"
                alsa.device = "0"
                alsa.card = "2"
                alsa.card_name = "USB PnP Audio Device"
                alsa.long_card_name = "USB PnP Audio Device at usb-0000:01:00.0-7, full speed"
                alsa.driver_name = "snd_usb_audio"
                device.bus_path = "pci-0000:01:00.0-usb-0:7:1.0"
                sysfs.path = "/devices/pci0000:00/0000:00:01.2/0000:01:00.0/usb1/1-7/1-7:1.0/sound/card2"
                udev.id = "usb-0c76_USB_PnP_Audio_Device-00"
                device.bus = "usb"
                device.vendor.id = "0c76"
                device.vendor.name = "JMTek, LLC."
                device.product.id = "161e"
                device.product.name = "USB PnP Audio Device"
                device.serial = "0c76_USB_PnP_Audio_Device"
                device.string = "hw:2"
                device.buffering.buffer_size = "192000"
                device.buffering.fragment_size = "96000"
                device.access_mode = "mmap+timer"
                device.profile.name = "mono-fallback"
                device.profile.description = "Mono"
                device.description = "USB PnP Audio Device Mono"
                module-udev-detect.discovered = "1"
                device.icon_name = "audio-card-usb"
        ports:
                analog-input-mic: Microphone (priority 8700, latency offset 0 usec, available: unknown)
                        properties:
                                device.icon_name = "audio-input-microphone"
        active port: <analog-input-mic>
    index: 1
        name: <alsa_output.pci-0000_06_00.6.analog-stereo.monitor>
        driver: <module-alsa-card.c>
        flags: DECIBEL_VOLUME LATENCY 
        state: IDLE
        suspend cause: (none)
        priority: 1030
        volume: front-left: 65536 / 100% / 0.00 dB,   front-right: 65536 / 100% / 0.00 dB
                balance 0.00
        base volume: 65536 / 100% / 0.00 dB
        volume steps: 65537
        muted: no
        current latency: 0.00 ms
        max rewind: 17 KiB
        sample spec: s16le 2ch 44100Hz
        channel map: front-left,front-right
                     Stereo
        used by: 0
        linked by: 0
        fixed latency: 100.14 ms
        monitor_of: 0
        card: 2 <alsa_card.pci-0000_06_00.6>
        module: 8
        properties:
                device.description = "Monitor of Family 17h (Models 10h-1fh) HD Audio Controller Analog Stereo"
                device.class = "monitor"
                alsa.card = "1"
                alsa.card_name = "HD-Audio Generic"
                alsa.long_card_name = "HD-Audio Generic at 0xfcd80000 irq 56"
                alsa.driver_name = "snd_hda_intel"
                device.bus_path = "pci-0000:06:00.6"
                sysfs.path = "/devices/pci0000:00/0000:00:08.1/0000:06:00.6/sound/card1"
                device.bus = "pci"
                device.vendor.id = "1022"
                device.vendor.name = "Advanced Micro Devices, Inc. [AMD]"
                device.product.id = "15e3"
                device.product.name = "Family 17h (Models 10h-1fh) HD Audio Controller"
                device.string = "1"
                module-udev-detect.discovered = "1"
                device.icon_name = "audio-card-pci"

**Comment by lawl** [comment]
[You can sandwich code/console output between three backticks (```) to format it as code , I've edited it for you]

The output is posted does not show that NoiseTorch is active. Have you loaded noisetorch and set discord to use it when running that command?

**Comment by T4O2M0** [comment]
NoiseTorch was not active when i ran that yes, sorry wasn't aware you wanted it to be, and yeah when i tested it it was on and switched to noise torch in discord, currently not able to get it to run for some reason, going to have to restart my computer and sorry it's a bit late so I'd really rather not, will try more tomorrow

**Comment by alx365** [comment]
You have to restart discord, in order to use the virtual microphone. It also bugged me, and i also almost thought it wasn't working for me >.<

**Comment by T4O2M0** [comment]
oh yeah @alx365 was right, started it with discord closed and then opened discord and it worked

**Comment by lawl** [comment]
I consider this solved then
