### ISSUE TITLE
No audio passes through noisetorch, no matter settings

### ISSUE THREAD

**Issue by SoptikHa2** [lawl/NoiseTorch#100]
No matter if I set voice activation threshold to 0% or 95%, or anything inbetween, no audio is passed from noisetorch. This hasn't happened before, and stopped working when I updated few weeks ago.

Any ideas how to debug this? There is no verbose flag and I'm not sure how to get useful logs.

This happens with both distro AUR version and latest official release. Even after moving `~/.config/noisetorch` so the config is regenerated by official build.

Also pulseaudio often crashes when unloading/reloading noisetorch, but I'm used to it and isn't that much of an issue. And has happened before as well.

**Comment by lawl** [comment]
You probably will also need to make sure you rebooted after removing anything AUR related. Also see the troubleshooting guide here: https://github.com/lawl/NoiseTorch/wiki/Troubleshooting

**Comment by SoptikHa2** [comment]
*bangs head into wall*

Null output and ladsba module on null output were both muted for some reason, maybe when I dis/connected headphones while noisetorch was running?

Thank you!

**Comment by lawl** [comment]
>  maybe when I dis/connected headphones while noisetorch was running?

Shouldn't, never heard of that. Weird. Glad you got it resolved though.
