### ISSUE TITLE
Long unloading/loading times & noisetorch mic produces no sound

### ISSUE THREAD

**Issue by 9mido** [lawl/NoiseTorch#101]
When unloading and loading noisetorch, it takes minutes to unload/load. Is there a way to make this process faster or is this normal? 

I also have a problem where the mic input noise does not get detected even after selecting the noisetorch mic as the input mic in my OS settings then changing it in OBS settings like the picture describes in the screenshots.

**Comment by lawl** [comment]
No, that isn't normal. Can you attach a log file?

**Comment by 9mido** [comment]
Which parts are not normal? How do I view the logs? 

I uninstalled the app but I may install it again to reply with logs.

**Comment by lawl** [comment]
Loading/Unloading should be pretty much instant. See here on how to find the logs: https://github.com/lawl/NoiseTorch/wiki/Troubleshooting

I'm not sure I understand the other issue you mentioned, but it may just be something that cascades from the weird loading time issues you're having.

**Comment by lawl** [comment]
> I uninstalled the app due to my dissatisfaction but I may install it again to reply with logs at a later time.

Ok then I'll close the issue in the meantime, and if you do decide to try again, you can reopen it.

**Comment by 9mido** [comment]
@lawl I was able to figure things out and it seems like everything works now. 

I did not look at the troubleshooting link the first time around. That seemed to work. Maybe you should include some of the stuff in your troubleshooting link on the front page of the noisetorch github under the installation section to make it more obvious.

**Comment by lawl** [comment]
@9mido glad you got it working!

I've moved the troubleshooting section directly below the install/uninstall now in the readme to hopefully give it a bit better visibility.
