### ISSUE TITLE
unable to build from source (0.10.1)

### ISSUE THREAD

**Issue by erbrecht** [lawl/NoiseTorch#102]
I'm was looking to create a distro-specific build, but I'm running into a couple issues.

First, when building from the source tarball, I get an error because it tries to read the git tag which doesn't exist:

```
$ make
cd c/ladspa; \
make
make[1]: Entering directory '/home/erbrecht/Downloads/NoiseTorch-0.10.1/c/ladspa'
cc -Wall -Werror -O2 -c -fPIC ../ringbuf.c ../rnnoise/*.c module.c 
cc -shared -Wl,--version-script=export.txt -o rnnoise_ladspa.so *.o
make[1]: Leaving directory '/home/erbrecht/Downloads/NoiseTorch-0.10.1/c/ladspa'
mkdir -p bin/
go generate
panic: Couldn't read git tags to embed version number

goroutine 1 [running]:
main.main()
	/home/erbrecht/Downloads/NoiseTorch-0.10.1/scripts/embedversion.go:14 +0x2aa
exit status 2
main.go:28: running "go": exit status 1
make: *** [Makefile:3: dev] Error 1
```

If I temporarily remove the line that embeds the version, I get:

```
$ make
cd c/ladspa; \
make
make[1]: Entering directory '/home/erbrecht/Downloads/NoiseTorch-0.10.1/c/ladspa'
cc -Wall -Werror -O2 -c -fPIC ../ringbuf.c ../rnnoise/*.c module.c 
cc -shared -Wl,--version-script=export.txt -o rnnoise_ladspa.so *.o
make[1]: Leaving directory '/home/erbrecht/Downloads/NoiseTorch-0.10.1/c/ladspa'
mkdir -p bin/
go generate
go build -o bin/noisetorch
main.go:22:2: cannot find package "." in:
	/home/erbrecht/Downloads/NoiseTorch-0.10.1/vendor/embed
make: *** [Makefile:4: dev] Error 1
```

This was definitely introduced in 0.10.1, with the addition of the `_ "embed"` import. I can build version 0.10.0 just fine (with the exception of the version issue above). I get the same `main.go:22:2: cannot find package "." in:` error whether I download the source tarball, or just check out the specific tags and try to build.

I don't know exactly what's missing. Is there something else I need to do in order to build?

**Comment by lawl** [comment]
What version of the go compiler are you using?

**Comment by erbrecht** [comment]
I was using 1.15. Updating to 1.16 resolved the problem.

**Comment by lawl** [comment]
Yep, "embed" is a new go 1.16 feature so 0.10.1 requires go 1.16. As for the version issue. Yes, it currently expects to be built within a git repo available. You'd need to add some kind of `make version=foo` parameter to be able to override it without patching.

Please remember to close the issue if this is resolved.
