### ISSUE TITLE
NoiseTorch is stuck on a "CAP_SYS_RESOURCE" screen and the grant capabilities button doesn't work

### ISSUE THREAD

**Issue by pedrovbeltran** [lawl/NoiseTorch#106]
Hey! I'm having trouble in Linux Mint 20.1 Xfce installing noisetorch. My log file is below for you to take a look. I know, it's huge, but the main thing is that I'm not able to find the "Couldn't setcap self as root: exit status 127" line and I've already done the step-by-step guide hat is described in wiki Troubleshooting, but it won't open. I'm pasting also a printscreen, if it helps.

[noisetorch-2021_03_15_15_15_43.log](https://github.com/lawl/NoiseTorch/files/6143642/noisetorch-2021_03_15_15_15_43.log)

![Captura de tela_2021-03-15_15-24-15](https://user-images.githubusercontent.com/24753790/111202419-bfe88f80-85bb-11eb-88d8-05c586a3bdf4.png)

**Comment by lawl** [comment]
Have you checked if the location you've installed noisetorch to in mounted with `nosuid`?

**Comment by lawl** [comment]
If you run `mount` in a terminal and post the output here I can check for you if that's your problem.

**Comment by pedrovbeltran** [comment]
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,noexec,relatime,size=3987104k,nr_inodes=996776,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=806588k,mode=755)
/dev/sda6 on / type btrfs (rw,relatime,ssd,space_cache,subvolid=256,subvol=/@)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=2568)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
/dev/sda6 on /home type btrfs (rw,relatime,ssd,space_cache,subvolid=257,subvol=/@home)
/dev/sda2 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=806584k,mode=700,uid=1000,gid=1000)
/home/.ecryptfs/pedro/.Private on /home/pedro type ecryptfs (rw,nosuid,nodev,relatime,ecryptfs_fnek_sig=e1dbe30b93e9b3fc,ecryptfs_sig=e3780b840ac1cec1,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
/dev/sdb2 on /media/pedro/PEDRO type vfat (rw,nosuid,nodev,relatime,uid=1000,gid=1000,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,showexec,utf8,flush,errors=remount-ro,uhelper=udisks2)
/dev/fuse on /root/.cache/doc type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
gvfsd-fuse on /root/.cache/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)

I guess the first line in the output answers your question... Now what do I do to fix it?

**Comment by lawl** [comment]
/home/.ecryptfs/pedro/.Private on /home/pedro type ecryptfs (rw,nosuid,nodev,relatime,ecryptfs_fnek_sig=e1dbe30b93e9b3fc,ecryptfs_sig=e3780b840ac1cec1,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs)

This is the line that answers the question. Yep, you have it mounted with nosuid. How to fix that? I cannot give individual advice on peoples system configuration, sorry. But this isn't currently supported. You would have to research yourself if you even want to disable nosuid and how to do it.

The best I can offer you is a workaround. You can copy the binary from `~/.local/bin/noisetorch` to somewhere else that doesn't have `nosuid`, for example you could copy it into `/opt` and then run `/opt/noisetorch`. This would also break the automatic updater though, so if you do that you should also edit `~/.config/noisetorch/config.toml` and set `EnableUpdates` to `false`.

You would then need to manually update the binary in `/opt/noisetorch`.

**Comment by pedrovbeltran** [comment]
Okay mate, I understand this, thanks a lot for your advice! I did this and it seems to work. For this to help more people I'll tell what I did:

1 - I move the noisetorch executable file to /opt/
2 - I put this at the end of .bashrc:
```
if [ -d "/opt" ] ; then
    PATH="$HOME/opt:$PATH"
fi
```

Again, thank you for your help and hope this helps others. :)
