### ISSUE TITLE
(incompatible?) Built-in Audio Analog Stereo

### ISSUE THREAD

**Issue by Inspire1571** [lawl/NoiseTorch#107]
Hi, I'm trying to load NoiseTorch however it doesn't. I'm using an Acer 4937G laptop running Raspberry Pi OS. The microphone and headphone works, however NoiseTorch doesn't seem to detect them. I think it has something to do with the drivers. Can you please help me troubleshoot? I'm fairly new to Raspberry OS. The link below shows screenshots from my computer

https://ibb.co/SNP8g4M

**Comment by lawl** [comment]
can you post a log file into a gist, see [here](https://github.com/lawl/NoiseTorch/wiki/Troubleshooting) where they are.

**Comment by Inspire1571** [comment]
[noisetorch-2021_03_18_00_50_47.log](https://github.com/lawl/NoiseTorch/files/6160682/noisetorch-2021_03_18_00_50_47.log)
[noisetorch-2021_03_18_01_21_26.log](https://github.com/lawl/NoiseTorch/files/6160683/noisetorch-2021_03_18_01_21_26.log)
[noisetorch-2021_03_18_01_24_08.log](https://github.com/lawl/NoiseTorch/files/6160684/noisetorch-2021_03_18_01_24_08.log)
[noisetorch-2021_03_18_01_25_57.log](https://github.com/lawl/NoiseTorch/files/6160685/noisetorch-2021_03_18_01_25_57.log)
[noisetorch-2021_03_18_01_26_30.log](https://github.com/lawl/NoiseTorch/files/6160686/noisetorch-2021_03_18_01_26_30.log)
[noisetorch-2021_03_18_00_49_25.log](https://github.com/lawl/NoiseTorch/files/6160687/noisetorch-2021_03_18_00_49_25.log)
[noisetorch-2021_03_18_00_49_42.log](https://github.com/lawl/NoiseTorch/files/6160688/noisetorch-2021_03_18_00_49_42.log)

**Comment by Inspire1571** [comment]
There are a lot of stuff here, I don't know which one.

**Comment by lawl** [comment]
Your devices are detected just fine. If they're marked as `(incompatible?)` there's not much you can currently do, other than building pulseaudio from source, see here: https://github.com/lawl/NoiseTorch/issues/30#issuecomment-771737671

Also the Pi is aarch64 and not x64, so i assume you compiled from source? I don't have an aarch64 device to test, so if there's further issues, I can't help you with that. But for `(incompatible?)` you can select the device anyways. If it doesn't work, you need a newer pulseaudio.

**Comment by Inspire1571** [comment]
> Your devices are detected just fine. If they're marked as `(incompatible?)` there's not much you can currently do, other than building pulseaudio from source, see here: [#30 (comment)](https://github.com/lawl/NoiseTorch/issues/30#issuecomment-771737671)
> 
> Also the Pi is aarch64 and not x64, so i assume you compiled from source? I don't have an aarch64 device to test, so if there's further issues, I can't help you with that. But for `(incompatible?)` you can select the device anyways. If it doesn't work, you need a newer pulseaudio.

I also have another computer to test to, it's running on Ubuntu rather than Raspberry Pi OS. NoiseTorch seems to work fine there.

**Comment by lawl** [comment]
No, sorry. As per the link i posted:

> there is currently nothing you can do, but wait.
