### ISSUE TITLE
Will this work on chromebook ?  Will we be able to use linuxmode to get this working

### ISSUE THREAD

**Issue by suikoo** [lawl/NoiseTorch#114]
Will this work on chromebook ?  Will we be able to use linuxmode to get this working

**Comment by lawl** [comment]
I don't know, I don't have a chromebook. Try it and let me know?

**Comment by suikoo** [comment]
It doesn't seem to be working.  the linux mode is containerized and wasn't
able to see it on the OS level.

**Comment by lawl** [comment]
cool, then there's the answer i suppose.
