### ISSUE TITLE
Not compatible with other software (a voice changer)

### ISSUE THREAD

**Issue by nahuel3pro** [lawl/NoiseTorch#115]
Hi! I'm trying to use it among with other software called Lyrebird [https://github.com/lyrebird-voice-changer/lyrebird/issues/75](url) but it doesn't seem to work, both programs are kinda incompatibles. Any solution or plan to the future?

**Comment by lawl** [comment]
i don't use that, but it sais it creates a virtual microphone also. you'd need to chain load them. load either noisetorch or lyrebird first, and then use that virtual microphone as input for the other app. i don't see a reason why that shouldn't work.

**Comment by lawl** [comment]
Assuming this is solved.
