### ISSUE TITLE
Adjust level of noise suppression for sibilance/plosives

### ISSUE THREAD

**Issue by mgonnav** [lawl/NoiseTorch#118]
I sense the reduction of sibilance (/s/ sound) and plosives (p-pops sound) is a bit too aggressive. So much that when I start a sentence with a word that starts with s or p, they get cut out and instead of "sound" you would hear "ound". Is there any way to adjust this? (not necessarily through the GUI)

**Comment by lawl** [comment]
Have you tried playing with the voice detection slider?

**Comment by mgonnav** [comment]
Hello! I thought the activation threshold would also lower my volume. It still cuts it off sometimes but it's way better than before, and I can't lower it much because I live next to a noisy avenue. Thank you.

**Comment by lawl** [comment]
You will probably have to make a bit of a tradeoff there in that case yeah. But I assume this is solved then, if not feel free to reopen.
