### ISSUE TITLE
Huge delay

### ISSUE THREAD

**Issue by Razer0123** [lawl/NoiseTorch#120]
I'm on Arch + Gnome, using latest version, NOT installed from AUR but followed the guide

I see a delay of about 4-5 seconds

Not sure what should i attach to be able to debug the issue

**Comment by lawl** [comment]
Please attach the noisetorch log `/tmp/noisetorch-<timestamp>.log` and a pulseaudio log `journalctl -b /usr/bin/pulseaudio`

**Comment by Razer0123** [comment]
`2021/05/05 00:28:26 Application starting. Version: 0.10.1
2021/05/05 00:28:26 CAP_SYS_RESOURCE: true
2021/05/05 00:28:26 Checking if config needs to be initialized
2021/05/05 00:28:26 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/alessandro/.config'
2021/05/05 00:28:26 Initializing config
2021/05/05 00:28:26 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/alessandro/.config'
2021/05/05 00:28:26 Wrote temp librnnoise to: /tmp/librnnoise-448968442.so
2021/05/05 00:28:26 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/alessandro/.config'
2021/05/05 00:28:26 Checking for updates
2021/05/05 00:28:26 Getting caps for: /home/alessandro/.local/bin/noisetorch
2021/05/05 00:28:26 Input alsa_input.usb-CMEDIA_USB_PnP_Audio_Device-00.mono-fallback, {Index:0 Name:alsa_input.usb-CMEDIA_USB_PnP_Audio_Device-00.mono-fallback Description:USB PnP Audio Device Mono SampleSpec:{Format:3 Channels:1 Rate:44100} ChannelMap:[0] ModuleIndex:6 Cvolume:[33411] Muted:false MonitorSourceIndex:4294967295 MonitorSourceName: Latency:0 Driver:module-alsa-card.c Flags:55 PropList:map[alsa.card:1 alsa.card_name:USB PnP Audio Device alsa.class:generic alsa.device:0 alsa.driver_name:snd_usb_audio alsa.id:USB Audio alsa.long_card_name:CMEDIA USB PnP Audio Device at usb-0000:01:00.0-2, full speed alsa.name:USB Audio alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 device.access_mode:mmap device.api:alsa device.buffering.buffer_size:8816 device.buffering.fragment_size:2204 device.bus:usb device.bus_path:pci-0000:01:00.0-usb-0:2:1.0 device.class:sound device.description:USB PnP Audio Device Mono device.icon_name:audio-card-usb device.product.id:0134 device.product.name:USB PnP Audio Device device.profile.description:Mono device.profile.name:mono-fallback device.serial:CMEDIA_USB_PnP_Audio_Device device.string:hw:1 device.vendor.id:0d8c device.vendor.name:C-Media Electronics, Inc. module-udev-detect.discovered:1 sysfs.path:/devices/pci0000:00/0000:00:01.3/0000:01:00.0/usb1/1-2/1-2:1.0/sound/card1 udev.id:usb-CMEDIA_USB_PnP_Audio_Device-00] RequestedLatency:0 BaseVolume:27636 SinkState:2 NVolumeSteps:65537 CardIndex:0 Ports:[{Name:analog-input-mic Description:Microphone Pririty:8700 Available:0}] ActivePortName:analog-input-mic Formats:[{Encoding:1 PropList:map[]}]}
2021/05/05 00:28:26 Input alsa_output.pci-0000_08_00.1.hdmi-stereo-extra1.monitor, {Index:1 Name:alsa_output.pci-0000_08_00.1.hdmi-stereo-extra1.monitor Description:Monitor of GA104 High Definition Audio Controller Digital Stereo (HDMI 2) SampleSpec:{Format:3 Channels:2 Rate:44100} ChannelMap:[1 2] ModuleIndex:7 Cvolume:[65536 65536] Muted:false MonitorSourceIndex:0 MonitorSourceName:alsa_output.pci-0000_08_00.1.hdmi-stereo-extra1 Latency:0 Driver:module-alsa-card.c Flags:34 PropList:map[alsa.card:2 alsa.card_name:HDA NVidia alsa.driver_name:snd_hda_intel alsa.long_card_name:HDA NVidia at 0xfc080000 irq 105 device.bus:pci device.bus_path:pci-0000:08:00.1 device.class:monitor device.description:Monitor of GA104 High Definition Audio Controller Digital Stereo (HDMI 2) device.icon_name:audio-card-pci device.product.id:228b device.product.name:GA104 High Definition Audio Controller device.string:2 device.vendor.id:10de device.vendor.name:NVIDIA Corporation module-udev-detect.discovered:1 sysfs.path:/devices/pci0000:00/0000:00:03.1/0000:08:00.1/sound/card2] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:65537 CardIndex:1 Ports:[] ActivePortName: Formats:[{Encoding:1 PropList:map[]}]}
2021/05/05 00:28:26 Input alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo.monitor, {Index:2 Name:alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo.monitor Description:Monitor of Audio Adapter (Unitek Y-247A) Stereo analogico SampleSpec:{Format:3 Channels:2 Rate:44100} ChannelMap:[1 2] ModuleIndex:9 Cvolume:[65536 65536] Muted:false MonitorSourceIndex:1 MonitorSourceName:alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo Latency:0 Driver:module-alsa-card.c Flags:34 PropList:map[alsa.card:0 alsa.card_name:USB Audio Device alsa.driver_name:snd_usb_audio alsa.long_card_name:C-Media Electronics Inc. USB Audio Device at usb-0000:0b:00.3-1, full speed device.bus:usb device.bus_path:pci-0000:0b:00.3-usb-0:1:1.0 device.class:monitor device.description:Monitor of Audio Adapter (Unitek Y-247A) Stereo analogico device.icon_name:audio-card-usb device.product.id:0014 device.product.name:Audio Adapter (Unitek Y-247A) device.serial:C-Media_Electronics_Inc._USB_Audio_Device device.string:0 device.vendor.id:0d8c device.vendor.name:C-Media Electronics, Inc. module-udev-detect.discovered:1 sysfs.path:/devices/pci0000:00/0000:00:07.1/0000:0b:00.3/usb3/3-1/3-1:1.0/sound/card0 udev.id:usb-C-Media_Electronics_Inc._USB_Audio_Device-00] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:65537 CardIndex:3 Ports:[] ActivePortName: Formats:[{Encoding:1 PropList:map[]}]}
2021/05/05 00:28:26 Input alsa_input.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.mono-fallback, {Index:3 Name:alsa_input.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.mono-fallback Description:Audio Adapter (Unitek Y-247A) Mono SampleSpec:{Format:3 Channels:1 Rate:44100} ChannelMap:[0] ModuleIndex:9 Cvolume:[46396] Muted:false MonitorSourceIndex:4294967295 MonitorSourceName: Latency:0 Driver:module-alsa-card.c Flags:55 PropList:map[alsa.card:0 alsa.card_name:USB Audio Device alsa.class:generic alsa.device:0 alsa.driver_name:snd_usb_audio alsa.id:USB Audio alsa.long_card_name:C-Media Electronics Inc. USB Audio Device at usb-0000:0b:00.3-1, full speed alsa.name:USB Audio alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 device.access_mode:mmap device.api:alsa device.buffering.buffer_size:8816 device.buffering.fragment_size:2204 device.bus:usb device.bus_path:pci-0000:0b:00.3-usb-0:1:1.0 device.class:sound device.description:Audio Adapter (Unitek Y-247A) Mono device.icon_name:audio-card-usb device.product.id:0014 device.product.name:Audio Adapter (Unitek Y-247A) device.profile.description:Mono device.profile.name:mono-fallback device.serial:C-Media_Electronics_Inc._USB_Audio_Device device.string:hw:0 device.vendor.id:0d8c device.vendor.name:C-Media Electronics, Inc. module-udev-detect.discovered:1 sysfs.path:/devices/pci0000:00/0000:00:07.1/0000:0b:00.3/usb3/3-1/3-1:1.0/sound/card0 udev.id:usb-C-Media_Electronics_Inc._USB_Audio_Device-00] RequestedLatency:0 BaseVolume:27111 SinkState:2 NVolumeSteps:65537 CardIndex:3 Ports:[{Name:analog-input-mic Description:Microphone Pririty:8700 Available:0}] ActivePortName:analog-input-mic Formats:[{Encoding:1 PropList:map[]}]}
2021/05/05 00:28:26 Input alsa_output.pci-0000_0c_00.3.analog-stereo.monitor, {Index:4 Name:alsa_output.pci-0000_0c_00.3.analog-stereo.monitor Description:Monitor of Family 17h (Models 00h-0fh) HD Audio Controller Stereo analogico SampleSpec:{Format:3 Channels:2 Rate:44100} ChannelMap:[1 2] ModuleIndex:10 Cvolume:[65536 65536] Muted:false MonitorSourceIndex:2 MonitorSourceName:alsa_output.pci-0000_0c_00.3.analog-stereo Latency:0 Driver:module-alsa-card.c Flags:34 PropList:map[alsa.card:4 alsa.card_name:HD-Audio Generic alsa.driver_name:snd_hda_intel alsa.long_card_name:HD-Audio Generic at 0xfc700000 irq 108 device.bus:pci device.bus_path:pci-0000:0c:00.3 device.class:monitor device.description:Monitor of Family 17h (Models 00h-0fh) HD Audio Controller Stereo analogico device.icon_name:audio-card-pci device.product.id:1457 device.product.name:Family 17h (Models 00h-0fh) HD Audio Controller device.string:4 device.vendor.id:1022 device.vendor.name:Advanced Micro Devices, Inc. [AMD] module-udev-detect.discovered:1 sysfs.path:/devices/pci0000:00/0000:00:08.1/0000:0c:00.3/sound/card4] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:65537 CardIndex:4 Ports:[] ActivePortName: Formats:[{Encoding:1 PropList:map[]}]}
2021/05/05 00:28:26 Output alsa_output.pci-0000_08_00.1.hdmi-stereo-extra1, {Index:0 Name:alsa_output.pci-0000_08_00.1.hdmi-stereo-extra1 Description:GA104 High Definition Audio Controller Digital Stereo (HDMI 2) SampleSpec:{Format:3 Channels:2 Rate:44100} ChannelMap:[1 2] ModuleIndex:7 Cvolume:[65536 65536] Muted:false MonitorSourceIndex:1 MonitorSourceName:alsa_output.pci-0000_08_00.1.hdmi-stereo-extra1.monitor Latency:0 Driver:module-alsa-card.c Flags:294 PropList:map[alsa.card:2 alsa.card_name:HDA NVidia alsa.class:generic alsa.device:7 alsa.driver_name:snd_hda_intel alsa.id:HDMI 1 alsa.long_card_name:HDA NVidia at 0xfc080000 irq 105 alsa.name:HDMI 1 alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 device.access_mode:mmap device.api:alsa device.buffering.buffer_size:17664 device.buffering.fragment_size:2944 device.bus:pci device.bus_path:pci-0000:08:00.1 device.class:sound device.description:GA104 High Definition Audio Controller Digital Stereo (HDMI 2) device.icon_name:audio-card-pci device.product.id:228b device.product.name:GA104 High Definition Audio Controller device.profile.description:Digital Stereo (HDMI 2) device.profile.name:hdmi-stereo-extra1 device.string:hdmi:2,1 device.vendor.id:10de device.vendor.name:NVIDIA Corporation module-udev-detect.discovered:1 sysfs.path:/devices/pci0000:00/0000:00:03.1/0000:08:00.1/sound/card2] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:65537 CardIndex:1 Ports:[{Name:hdmi-output-1 Description:HDMI / DisplayPort 2 Pririty:5800 Available:2}] ActivePortName:hdmi-output-1 Formats:[{Encoding:1 PropList:map[]}]}
2021/05/05 00:28:26 Output alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo, {Index:1 Name:alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo Description:Audio Adapter (Unitek Y-247A) Stereo analogico SampleSpec:{Format:3 Channels:2 Rate:44100} ChannelMap:[1 2] ModuleIndex:9 Cvolume:[52765 52765] Muted:false MonitorSourceIndex:2 MonitorSourceName:alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.analog-stereo.monitor Latency:0 Driver:module-alsa-card.c Flags:55 PropList:map[alsa.card:0 alsa.card_name:USB Audio Device alsa.class:generic alsa.device:0 alsa.driver_name:snd_usb_audio alsa.id:USB Audio alsa.long_card_name:C-Media Electronics Inc. USB Audio Device at usb-0000:0b:00.3-1, full speed alsa.name:USB Audio alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 device.access_mode:mmap device.api:alsa device.buffering.buffer_size:17632 device.buffering.fragment_size:4408 device.bus:usb device.bus_path:pci-0000:0b:00.3-usb-0:1:1.0 device.class:sound device.description:Audio Adapter (Unitek Y-247A) Stereo analogico device.icon_name:audio-card-usb device.product.id:0014 device.product.name:Audio Adapter (Unitek Y-247A) device.profile.description:Stereo analogico device.profile.name:analog-stereo device.serial:C-Media_Electronics_Inc._USB_Audio_Device device.string:front:0 device.vendor.id:0d8c device.vendor.name:C-Media Electronics, Inc. module-udev-detect.discovered:1 sysfs.path:/devices/pci0000:00/0000:00:07.1/0000:0b:00.3/usb3/3-1/3-1:1.0/sound/card0 udev.id:usb-C-Media_Electronics_Inc._USB_Audio_Device-00] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:65537 CardIndex:3 Ports:[{Name:analog-output-speaker Description:Speakers Pririty:10000 Available:0}] ActivePortName:analog-output-speaker Formats:[{Encoding:1 PropList:map[]}]}
2021/05/05 00:28:26 Output alsa_output.pci-0000_0c_00.3.analog-stereo, {Index:2 Name:alsa_output.pci-0000_0c_00.3.analog-stereo Description:Family 17h (Models 00h-0fh) HD Audio Controller Stereo analogico SampleSpec:{Format:3 Channels:2 Rate:44100} ChannelMap:[1 2] ModuleIndex:10 Cvolume:[44909 44909] Muted:false MonitorSourceIndex:4 MonitorSourceName:alsa_output.pci-0000_0c_00.3.analog-stereo.monitor Latency:0 Driver:module-alsa-card.c Flags:55 PropList:map[alsa.card:4 alsa.card_name:HD-Audio Generic alsa.class:generic alsa.device:0 alsa.driver_name:snd_hda_intel alsa.id:ALC1220 Analog alsa.long_card_name:HD-Audio Generic at 0xfc700000 irq 108 alsa.name:ALC1220 Analog alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 device.access_mode:mmap device.api:alsa device.buffering.buffer_size:17664 device.buffering.fragment_size:2944 device.bus:pci device.bus_path:pci-0000:0c:00.3 device.class:sound device.description:Family 17h (Models 00h-0fh) HD Audio Controller Stereo analogico device.icon_name:audio-card-pci device.product.id:1457 device.product.name:Family 17h (Models 00h-0fh) HD Audio Controller device.profile.description:Stereo analogico device.profile.name:analog-stereo device.string:front:4 device.vendor.id:1022 device.vendor.name:Advanced Micro Devices, Inc. [AMD] module-udev-detect.discovered:1 sysfs.path:/devices/pci0000:00/0000:00:08.1/0000:0c:00.3/sound/card4] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:65537 CardIndex:4 Ports:[{Name:analog-output-lineout Description:Line Out Pririty:9000 Available:2} {Name:analog-output-headphones Description:Headphones Pririty:9900 Available:1}] ActivePortName:analog-output-lineout Formats:[{Encoding:1 PropList:map[]}]}
2021/05/05 00:28:32 Querying pulse rlimit
2021/05/05 00:28:32 Rlimit: {Cur:200000 Max:200000}. Trying to remove.
2021/05/05 00:28:32 Have capabilities
2021/05/05 00:28:32 Rlimit: {Cur:18446744073709551615 Max:18446744073709551615}
2021/05/05 00:28:32 Loading supressor
2021/05/05 00:28:32 Loaded null sink as idx: 30
2021/05/05 00:28:32 Loaded ladspa sink as idx: 31
2021/05/05 00:28:32 Loaded fixed latency loopback as idx: 32
2021/05/05 00:28:32 Loaded remap source as idx: 33
2021/05/05 00:28:32 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/alessandro/.config'`


and

`-- Journal begins at Wed 2021-04-07 09:49:56 CEST, ends at Wed 2021-05-05 00:36:08 CEST. --
mag 05 00:26:22 archlinux pulseaudio[825]: module-rescue-stream is obsolete and should no longer be loaded. Please remove it from your configuration.
mag 05 00:28:09 archlinux pulseaudio[825]: Unable to read or parse data from client.
mag 05 00:28:11 archlinux pulseaudio[825]: Error opening PCM device front:4: File o directory non esistente
mag 05 00:28:11 archlinux pulseaudio[825]: Error opening PCM device hw:1: File o directory non esistente
mag 05 00:28:11 archlinux pulseaudio[825]: Error opening PCM device hw:0: File o directory non esistente
mag 05 00:28:19 archlinux pulseaudio[2499]: module-rescue-stream is obsolete and should no longer be loaded. Please remove it from your configuration.
mag 05 00:28:32 archlinux pulseaudio[2499]: Cannot set requested sink latency of 9223372036854752,00 ms, adjusting to 2000,00 ms
mag 05 00:28:32 archlinux pulseaudio[2499]: Cannot set requested source latency of 16,67 ms, adjusting to 99,95 ms
mag 05 00:28:32 archlinux pulseaudio[2499]: No remapping configured, proceeding nonetheless!
mag 05 00:28:49 archlinux pulseaudio[2499]: Attivazione da parte di ALSA per scrivere nuovi dati sul dispositivo, ma non c'era nulla da scrivere.
mag 05 00:28:49 archlinux pulseaudio[2499]: Molto probabilmente si tratta di un bug nei driver ALSA «snd_hda_intel». Segnalare questo problema agli sviluppatori di ALSA.
mag 05 00:28:49 archlinux pulseaudio[2499]: Attivazione avvenuta con POLLOUT impostato; tuttavia, una successiva snd_pcm_avail() ha ritornato 0 o un altro valore < min_avail.
mag 05 00:29:00 archlinux pulseaudio[2499]: Attivazione da parte di ALSA per leggere nuovi dati dal dispositivo, ma non c'era nulla da leggere.
mag 05 00:29:00 archlinux pulseaudio[2499]: Molto probabilmente si tratta di un bug nei driver ALSA «snd_usb_audio». Segnalare questo problema agli sviluppatori di ALSA.
mag 05 00:29:00 archlinux pulseaudio[2499]: Attivazione avvenuta con POLLIN impostato; tuttavia, una successiva snd_pcm_avail() ha ritornato 0 o un altro valore < min_avail.
mag 05 00:35:37 archlinux pulseaudio[2499]: Too many underruns, increasing latency to 55,00 ms
`

**Comment by lawl** [comment]
Cannot set requested sink latency of 9223372036854752,00 ms, adjusting to 2000,00 ms

This is the same issue as #48. The fix for which on the noisetorch side is in the current release (so it does not require building noisetorch from source) but it also requires a fix on the pulseaudio side. See [this comment](https://github.com/lawl/NoiseTorch/issues/48#issuecomment-771737354)

You would need to either wait for your distrobution to distribute a version of pulseaudio containing the bugfix, or you'd need to build pulseaudio from source code. There's nothing else you can do unfortunately.
