### ISSUE TITLE
Inconsistent state every time after upgrading to Fedora 34

### ISSUE THREAD

**Issue by monalisa-overdrive** [lawl/NoiseTorch#122]
Launch NoiseTorch, select microphone, click 'Load NoiseTorch', it fails to load with "Inconsistent state, please unload first."

Unloading/reloading does nothing. I've reinstalled the app, no change.

I suspect this has something to do with Fedora 34 routing all audio to PipeWire instead of PulseAudio: https://fedoraproject.org/wiki/Changes/DefaultPipeWire

**Comment by lawl** [comment]
Yes, PipeWire isn't supported yet, see: #63 

Hopefully soon though.
