### ISSUE TITLE
Noise cancelling lead to voice cancelling as well

### ISSUE THREAD

**Issue by i-am-olep** [lawl/NoiseTorch#123]
I followed the instructions for the installation, using the v0.10.1 release and everything went smoothly.
But when using the applications in a web call, I get perfect when I stay quiet, I can ear myself when there is "simple ambient noise" but a more invasive noise (like hand clapping) ends up cancelling the noise together  with my voice. So if the noise last for some time, I'm not able to speak in that time.
Is it a problem of mine or a general problem? I haven't found anything about that but I could easily have missed something.
Could it also be a problem related to the poor quality of my microphone>

OS: Manjaro
Browsers used: Brave, Firefox

**Comment by lawl** [comment]
Never heard of anything like that. Can you provide an audio sample (unfiltered) that would lead to voice also being filtered?

**Comment by lawl** [comment]
unresponsive.
