### ISSUE TITLE
Distribute as a Snap 

### ISSUE THREAD

**Issue by heidiwenger** [lawl/NoiseTorch#125]
Along comes desktop integration. Snaps are conveniently installed from app store instead of Github. No need to make the package executable either as in AppImages (and most guides approach chmodding via terminal, which is a great no-no for new users of Linux; i really think things should be one click nowadays on Linux).

Snap packages are also automatically sandboxed. No matter how good of a tool terminal often is, most computer users absolutely do not want to touch it. 

https://snapcraft.io/
https://forum.snapcraft.io/c/snap-requests/21
Alan Pope shows how to make a snap package in under 60 mins https://www.youtube.com/watch?v=ikoUByA5BLU

**Comment by lawl** [comment]
I don't like being at the whim of canonical. I had made efforts to create a snap before. The entire experience was less than enjoyable and took multiple months: https://forum.snapcraft.io/t/request-classic-confinement-for-noisetorch/18678

In the end i decided to write my own god damn updater so I can actually start shipping noisetorch. Now that I already have that the value proposition for snaps for me is unfortunately negative.

No snap as long as canonical can gate-keep me from releasing something.

**Comment by Scrumplex** [comment]
What about Flatpaks or AppImages?

**Comment by lawl** [comment]
@Scrumplex 
Flatpaks have their own issues. AppImages: once better end-user tooling is available beyond the simple `chmod+x;./AppImage` usercase,  see #39
