### ISSUE TITLE
i cant seem to get it to open

### ISSUE THREAD

**Issue by autoteelar** [lawl/NoiseTorch#126]
i have run all the commands, 
tar -C $HOME -xzf NoiseTorch_x64.tgz
sudo setcap 'CAP_SYS_RESOURCE=+ep' ~/.local/bin/noisetorch
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

and  it still dont work it just opens then closes immediately

$ tar -C $HOME -xzf NoiseTorch_x64.tgz
$ sudo setcap 'CAP_SYS_RESOURCE=+ep' ~/.local/bin/noisetorch
$ noisetorch
bash: noisetorch: command not found
$ if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
$ noisetorch
$ noisetorch
$ noisetorch
$ noisetorch -h
Usage of noisetorch:
  -i	Load supressor for input. If no source device ID is specified the default pulse audio source is used.
  -l	List available PulseAudio devices
  -o	Load supressor for output. If no source device ID is specified the default pulse audio source is used.
  -removerlimit int
    	for internal use only (default -1)
  -s string
    	Use the specified source/sink device ID
  -setcap
    	for internal use only
  -t int
    	Voice activation threshold (default -1)
  -u	Unload supressor
$ noisetorch 
$ noisetorch 
$ noisetorch 
$

**Comment by autoteelar** [comment]
using void linux

**Comment by lawl** [comment]
Please attach a log file as described in: https://github.com/lawl/NoiseTorch/wiki/Troubleshooting

**Comment by lawl** [comment]
Assuming this is solved.
