### ISSUE TITLE
Pipewire mode doesnt create noisetorch microphone device 

### ISSUE THREAD

**Issue by lorddickfist** [lawl/NoiseTorch#131]
Noisetorch will not unload after being loaded and no device called noisetorch microphone has been created. Can't seem to get a log file to generate any suggestions welcome

**Comment by lawl** [comment]
As mentioned in the patch notes, noisetorch doesn't create a log file by default anymore. See: https://github.com/lawl/NoiseTorch/wiki/Troubleshooting for how to obtain a log file now. Can you please attach that?

**Comment by lorddickfist** [comment]
Yeah I got it to work I mistyped something, here is the log
[noisetorch.log](https://github.com/lawl/NoiseTorch/files/6510792/noisetorch.log)

**Comment by lawl** [comment]
That log file doesn't contain the part where you load noisetorch. Can you try again but also press "Load noisetorch"?

**Comment by lorddickfist** [comment]
Sure, but heres the thing even after killing the noisetorch process it launches loaded. I hit reload, and unload several times this time. 
[noisetorch.log](https://github.com/lawl/NoiseTorch/files/6510846/noisetorch.log)

**Comment by lawl** [comment]
Error loading input: PulseAudio error: commandLoadModule -> No such entity

Interesting. Your pipewire reports to be 0.3.29, but doesn't support the feature which should have been shipped (and has been for me) with 0.3.28. How did you install this version of PipeWire?

**Comment by lorddickfist** [comment]
I installed it through AUR the non-git version. Should I try another package if I can first?

**Comment by lawl** [comment]
I think you should try a method that doesn't touch AUR and then reopen this issue if the problem persists.

**Comment by lawl** [comment]
(You could also try rebooting to make sure that *all* pipewire daemons have been restarted on the new version)

**Comment by lorddickfist** [comment]
> (You could also try rebooting to make sure that _all_ pipewire daemons have been restarted on the new version if you haven't)

Right I rebooted and installed offical packages of pipewire, pipewire-pulse, and pipewire-jack instead.I am still getting the same log as before, any other suggestions?

**Comment by lawl** [comment]
can you point me to the build script of the packages you installed?

**Comment by lorddickfist** [comment]
> can you point me to the build script of the packages you installed?

Im afraid im a bit confused, did you mean where I downloaded?

**Comment by lawl** [comment]
no not quite, i've found myself already. Can you give me the output of this:

    cd /;find -iname 'libpipewire*.so' 2>/dev/null

to find me a list off all pipewire libraries on your system?

**Comment by lorddickfist** [comment]
here you go https://ghostbin.co/paste/644wkz

**Comment by lawl** [comment]
link doesn't work for me can you please put that in a gist: https://gist.github.com/ ?

**Comment by lorddickfist** [comment]
https://gist.github.com/lorddickfist/b10665929bfa113203d3e68d08e3faad Here hopefully thats better

**Comment by lawl** [comment]
ok, i think at this point it's best to wait for fedora to release 0.3.28 to see if this is a distribution issue or not, they're still on 0.3.27 atm the moment

**Comment by lorddickfist** [comment]
Okay will do, thank you for the support

**Comment by lawl** [comment]
Tested this with the official fedora packages and it works fine there. Might be best to open an issue with your distribution. Not much i can do here, sorry.

**Comment by lorddickfist** [comment]
Will do thanks again
