### ISSUE TITLE
main.go:29:12: pattern c/ladspa/rnnoise_ladspa.so: no matching files found

### ISSUE THREAD

**Issue by yurivict** [lawl/NoiseTorch#132]
```
===>  Building noisetorch from .
main.go:29:12: pattern c/ladspa/rnnoise_ladspa.so: no matching files found
*** Error code 1
```

Additionally, ladspa is obsolete and shouldn't be user. It was superseded by LV2.

OS: FreeBSD 13.0

**Comment by lawl** [comment]
I don't use freebsd. If any *BSD users want to send pull requests to make it work, that's fine, but i'll probably never officially support it.

As for ladspa, well pulseaudio has the ability to load ladpa modules but not LV2, so complaining that it's obsolete is not very helpful.

**Comment by lawl** [comment]
(Just to clarify, if someone would like to step up and support the *BSD's officially here, that's of course also more than welcome, it's just that *I* wont)
