### ISSUE TITLE
Pulseaudio source not found

### ISSUE THREAD

**Issue by Razer0123** [lawl/NoiseTorch#139]
Trying Noisetorch on a system with Pipewire, i am testing the command via terminal, this is what i did

`noisetorch -i -s sys-devices-pci0000:00-0000:00:01.3-0000:01:00.0-usb1-1\x2d2-1\x2d2:1.0-sound-card1-controlC1.device -t 95`

But i am getting this error

`PulseAudio source not found: sys-devices-pci0000:00-0000:00:01.3-0000:01:00.0-usb1-1x2d2-1x2d2:1.0-sound-card1-controlC1.device`

The device ID should be correct

**Comment by lawl** [comment]
How did you get that device ID? Also attach a log please, as described [here](https://github.com/lawl/NoiseTorch/wiki/Troubleshooting)

**Comment by lawl** [comment]
Can't help with that sorry, autostart is unsupported.
