### ISSUE TITLE
[pipewire] commandLoadModule -> No such entity

### ISSUE THREAD

**Issue by cryptomilk** [lawl/NoiseTorch#140]
I don't get noisetorch with pipewire working:

```
$ rpm -q pipewire
pipewire-0.3.28-1.1.x86_64
$ rpm -q noisetorch
noisetorch-0.11.2-0.x86_64
$ noisetorch -l
Sources:
        Device Name: RØDE NT-USB Mini Analog Stereo
        Device ID: alsa_output.usb-R__DE_Microphones_R__DE_NT-USB_Mini_26BF1635-00.analog-stereo.monitor

$ noisetorch -i alsa_output.usb-R__DE_Microphones_R__DE_NT-USB_Mini_26BF1635-00.analog-stereo.monitor
Error loading PulseAudio Module: PulseAudio error: commandLoadModule -> No such entity
```

The help could be improved with e.g.

```
-i [SOURCE]    Load supressor for input.
```

This makes it clear that you can specify an optional input source. Same for other options with arguments ...

**Comment by lawl** [comment]
yeah the CLI is kinda weird, i know. you need to pass the device id with `-s`, so you'd do `noisetorch -i -s alsa_output.usb-R__DE_Microphones_R__DE_NT-USB_Mini_26BF1635-00.analog-stereo.monitor`

**Comment by lawl** [comment]
Sorry, I just saw the actual error. Can you attach a log, from passing `-log`?

**Comment by cryptomilk** [comment]
```
$ noisetorch -i -s alsa_output.usb-R__DE_Microphones_R__DE_NT-USB_Mini_26BF1635-00.analog-stereo.monitor -log
2021/05/26 08:12:25 Application starting. Version: unknown (custom)
2021/05/26 08:12:25 CAP_SYS_RESOURCE: true
2021/05/26 08:12:25 Checking if config needs to be initialized
2021/05/26 08:12:25 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/asn/.config'
2021/05/26 08:12:25 Wrote temp librnnoise to: /tmp/librnnoise-231428525.so
2021/05/26 08:12:25 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/asn/.config'
2021/05/26 08:12:25 Audioserver package name: PulseAudio (on PipeWire 0.3.28)
2021/05/26 08:12:25 Audioserver package version: 14.0.0
2021/05/26 08:12:25 Detected PipeWire
2021/05/26 08:12:25 Loading supressor for pipewire
2021/05/26 08:12:25 Error loading input: PulseAudio error: commandLoadModule -> No such entity
Error loading PulseAudio Module: PulseAudio error: commandLoadModule -> No such entity
```

**Comment by lawl** [comment]
Probably running into this issue: https://github.com/lawl/NoiseTorch/commit/c2bfe0202f5c58e35700925f6bbf5bafe613d509

You can try to use the official binary or try to build it from source yourself with clang. I don't know where that rpm came from.

**Comment by lawl** [comment]
Anything in your `pipewire-pulse` logs? Alternatively maybe installing pipewire 0.3.28 didn't restart pipewire-pulse.

**Comment by cryptomilk** [comment]
Oh, you're right, it complains that it can't find the `floorf()` functions. Will investigate ...

**Comment by cryptomilk** [comment]
I've found the issue. The problem isn't gcc!

The linker uses the option '--as-needed' by default now. This option allows the linker to ignore, i.e., not link against, some of the libraries supplied on its command line if they are not actually used by the shared library that is being created. For example, if you supply the -lm option on the command line to the linker but do not actually use any maths functions then the ''libm.so'' library will not be linked against.

You specify the `-lm` at the beginning, it needs to go to the end! :-)

```
cat noisetorch-fix-ladspa-linking.patch 
Index: NoiseTorch-0.11.2/c/ladspa/Makefile
===================================================================
--- NoiseTorch-0.11.2.orig/c/ladspa/Makefile    2021-05-20 15:04:40.000000000 +0200
+++ NoiseTorch-0.11.2/c/ladspa/Makefile 2021-05-26 10:10:41.198688064 +0200
@@ -1,3 +1,3 @@
 default: 
        $(CC) -Wall -O2 -c -fPIC ../ringbuf.c ../rnnoise/*.c module.c
-       $(CC) -shared -lm -Wl,--version-script=export.txt -o rnnoise_ladspa.so *.o
+       $(CC) -o rnnoise_ladspa.so *.o -shared -Wl,--version-script=export.txt -lm
```

**Comment by lawl** [comment]
Ah, awesome, thanks. I don't think I ever said that I think it's a problem with gcc :)

Though I could have sworn I tried that. Will fix that up once i'm back at a pc.
