### ISSUE TITLE
noisetorch not working with noexec on /tmp

### ISSUE THREAD

**Issue by jose1711** [lawl/NoiseTorch#142]
For security reasons I mount `/tmp` fs with `noexec`. Looks like `noisetorch` does not like this though and is complaining about this situation (`could not map segment from a shared object`). Is there any workaround other than remounting the filesystem?

Distro: Arch Linux x86_64 rolling
Version: 0.11.2-1 (from AUR)

**Comment by lawl** [comment]
IIRC we respect `TMPDIR`, so you should be able to set that and point it somewhere else.

**Comment by jose1711** [comment]
Thank you, as this need to happen at some point, could `noisetorch` give user a hint that currently it's running on a filesystem which does not allow `exec` calls? I only learned this by inspecting `systemd` logs.

**Comment by lawl** [comment]
Personally not interested in doing that. There's infinitely many system configurations in the linux world, and maybe someone has even disabled some kernel options. It's just not feasible to handle every single edge case on desktop linux.

However, if you want to create a PR with such a check, i *may* (no guarantee) merge it. For now I'll close this issue as it's resolved.
