### ISSUE TITLE
Can't Authenticate with sudo

### ISSUE THREAD

**Issue by jakob1379** [lawl/NoiseTorch#146]
Hello there and thank you for an awesome piece of software! After the update, I haven't been able to authenticate as asked for by Noisetorch and the password was verified with ´su´ as seen in the code snippet. I suspect that the password might be passed incorrectly.

```
[fuzie@fuzie-laptop ~]$ sudo su
[sudo] password for fuzie: 
[fuzie-laptop fuzie]# 
exit
[fuzie@fuzie-laptop ~]$ noisetorch 
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/home/fuzie/.local/bin/noisetorch' as the super user
Authenticating as: Jakob G. Aaes (fuzie)
Password: 
==== AUTHENTICATION FAILED ====
```

**Comment by lawl** [comment]
Can you attach a log? See [here](https://github.com/lawl/NoiseTorch/wiki/Troubleshooting).

**Comment by jakob1379** [comment]
[fuzie@fuzie-laptop ~]$ cat noise_log.log 
2021/06/07 13:03:03 Application starting. Version: 0.11.3 (official)
2021/06/07 13:03:03 CAP_SYS_RESOURCE: false
2021/06/07 13:03:03 Checking if config needs to be initialized
2021/06/07 13:03:03 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/fuzie/.config'
2021/06/07 13:03:03 Wrote temp librnnoise to: /tmp/librnnoise-734742488.so
2021/06/07 13:03:03 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/fuzie/.config'
2021/06/07 13:03:03 Audioserver package name: pulseaudio
2021/06/07 13:03:03 Audioserver package version: 14.2
2021/06/07 13:03:03 Detected PulseAudio
2021/06/07 13:03:03 couldn't parse server version, regexp didn't match version: 14.2
2021/06/07 13:03:03 Checking for updates
2021/06/07 13:03:03 Getting caps for: /home/fuzie/.local/bin/noisetorch
2021/06/07 13:03:03 Audioserver package name: pulseaudio
2021/06/07 13:03:03 Audioserver package version: 14.2
2021/06/07 13:03:03 Detected PulseAudio
2021/06/07 13:03:03 couldn't parse server version, regexp didn't match version: 14.2
2021/06/07 13:03:03 Connected to audio server. Server name ''
2021/06/07 13:03:03 Output alsa_output.pci-0000_00_1f.3.analog-stereo, {Index:0 Name:alsa_output.pci-0000_00_1f.3.analog-stereo Description:Built-in Audio Analog Stereo SampleSpec:{Format:3 Channels:2 Rate:44100} ChannelMap:[1 2] ModuleIndex:6 Cvolume:[18378 24273] Muted:false MonitorSourceIndex:0 MonitorSourceName:alsa_output.pci-0000_00_1f.3.analog-stereo.monitor Latency:0 Driver:module-alsa-card.c Flags:183 PropList:map[alsa.card:0 alsa.card_name:HDA Intel PCH alsa.class:generic alsa.device:0 alsa.driver_name:snd_hda_intel alsa.id:ALC236 Analog alsa.long_card_name:HDA Intel PCH at 0xa4320000 irq 131 alsa.name:ALC236 Analog alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 device.access_mode:mmap+timer device.api:alsa device.buffering.buffer_size:352800 device.buffering.fragment_size:176400 device.bus:pci device.bus_path:pci-0000:00:1f.3 device.class:sound device.description:Built-in Audio Analog Stereo device.form_factor:internal device.icon_name:audio-card-pci device.product.id:9d71 device.product.name:Sunrise Point-LP HD Audio device.profile.description:Analog Stereo device.profile.name:analog-stereo device.string:front:0 device.vendor.id:8086 device.vendor.name:Intel Corporation module-udev-detect.discovered:1 sysfs.path:/devices/pci0000:00/0000:00:1f.3/sound/card0] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:65537 CardIndex:0 Ports:[{Name:analog-output-speaker Description:Speakers Pririty:10000 Available:0} {Name:analog-output-headphones Description:Headphones Pririty:9900 Available:1}] ActivePortName:analog-output-speaker Formats:[{Encoding:1 PropList:map[]}]}
2021/06/07 13:03:03 Output combined, {Index:1 Name:combined Description:Simultaneous output to Built-in Audio Analog Stereo SampleSpec:{Format:3 Channels:2 Rate:44100} ChannelMap:[1 2] ModuleIndex:14 Cvolume:[55711 60296] Muted:false MonitorSourceIndex:2 MonitorSourceName:combined.monitor Latency:0 Driver:module-combine-sink.c Flags:162 PropList:map[device.class:filter device.description:Simultaneous output to Built-in Audio Analog Stereo device.icon_name:audio-card] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:65537 CardIndex:4294967295 Ports:[] ActivePortName: Formats:[{Encoding:1 PropList:map[]}]}
2021/06/07 13:03:05 Calling: /usr/bin/pkexec /home/fuzie/.local/bin/noisetorch -setcap
2021/06/07 13:03:09 Couldn't setcap self as root: exit status 127
2021/06/07 13:03:12 Deleted temp librnnoise: /tmp/librnnoise-734742488.so

**Comment by jakob1379** [comment]
[fuzie@fuzie-laptop ~]$ cat noise_log.log 
2021/06/07 13:03:03 Application starting. Version: 0.11.3 (official)
2021/06/07 13:03:03 CAP_SYS_RESOURCE: false
2021/06/07 13:03:03 Checking if config needs to be initialized
2021/06/07 13:03:03 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/fuzie/.config'
2021/06/07 13:03:03 Wrote temp librnnoise to: /tmp/librnnoise-734742488.so
2021/06/07 13:03:03 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/fuzie/.config'
2021/06/07 13:03:03 Audioserver package name: pulseaudio
2021/06/07 13:03:03 Audioserver package version: 14.2
2021/06/07 13:03:03 Detected PulseAudio
2021/06/07 13:03:03 couldn't parse server version, regexp didn't match version: 14.2
2021/06/07 13:03:03 Checking for updates
2021/06/07 13:03:03 Getting caps for: /home/fuzie/.local/bin/noisetorch
2021/06/07 13:03:03 Audioserver package name: pulseaudio
2021/06/07 13:03:03 Audioserver package version: 14.2
2021/06/07 13:03:03 Detected PulseAudio
2021/06/07 13:03:03 couldn't parse server version, regexp didn't match version: 14.2
2021/06/07 13:03:03 Connected to audio server. Server name ''
2021/06/07 13:03:03 Output alsa_output.pci-0000_00_1f.3.analog-stereo, {Index:0 Name:alsa_output.pci-0000_00_1f.3.analog-stereo Description:Built-in Audio Analog Stereo SampleSpec:{Format:3 Channels:2 Rate:44100} ChannelMap:[1 2] ModuleIndex:6 Cvolume:[18378 24273] Muted:false MonitorSourceIndex:0 MonitorSourceName:alsa_output.pci-0000_00_1f.3.analog-stereo.monitor Latency:0 Driver:module-alsa-card.c Flags:183 PropList:map[alsa.card:0 alsa.card_name:HDA Intel PCH alsa.class:generic alsa.device:0 alsa.driver_name:snd_hda_intel alsa.id:ALC236 Analog alsa.long_card_name:HDA Intel PCH at 0xa4320000 irq 131 alsa.name:ALC236 Analog alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 device.access_mode:mmap+timer device.api:alsa device.buffering.buffer_size:352800 device.buffering.fragment_size:176400 device.bus:pci device.bus_path:pci-0000:00:1f.3 device.class:sound device.description:Built-in Audio Analog Stereo device.form_factor:internal device.icon_name:audio-card-pci device.product.id:9d71 device.product.name:Sunrise Point-LP HD Audio device.profile.description:Analog Stereo device.profile.name:analog-stereo device.string:front:0 device.vendor.id:8086 device.vendor.name:Intel Corporation module-udev-detect.discovered:1 sysfs.path:/devices/pci0000:00/0000:00:1f.3/sound/card0] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:65537 CardIndex:0 Ports:[{Name:analog-output-speaker Description:Speakers Pririty:10000 Available:0} {Name:analog-output-headphones Description:Headphones Pririty:9900 Available:1}] ActivePortName:analog-output-speaker Formats:[{Encoding:1 PropList:map[]}]}
2021/06/07 13:03:03 Output combined, {Index:1 Name:combined Description:Simultaneous output to Built-in Audio Analog Stereo SampleSpec:{Format:3 Channels:2 Rate:44100} ChannelMap:[1 2] ModuleIndex:14 Cvolume:[55711 60296] Muted:false MonitorSourceIndex:2 MonitorSourceName:combined.monitor Latency:0 Driver:module-combine-sink.c Flags:162 PropList:map[device.class:filter device.description:Simultaneous output to Built-in Audio Analog Stereo device.icon_name:audio-card] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:65537 CardIndex:4294967295 Ports:[] ActivePortName: Formats:[{Encoding:1 PropList:map[]}]}
2021/06/07 13:03:05 Calling: /usr/bin/pkexec /home/fuzie/.local/bin/noisetorch -setcap
2021/06/07 13:03:09 Couldn't setcap self as root: exit status 127
2021/06/07 13:03:12 Deleted temp librnnoise: /tmp/librnnoise-734742488.so

**Comment by jakob1379** [comment]
[fuzie@fuzie-laptop ~]$ cat noise_log.log 
2021/06/07 13:03:03 Application starting. Version: 0.11.3 (official)
2021/06/07 13:03:03 CAP_SYS_RESOURCE: false
2021/06/07 13:03:03 Checking if config needs to be initialized
2021/06/07 13:03:03 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/fuzie/.config'
2021/06/07 13:03:03 Wrote temp librnnoise to: /tmp/librnnoise-734742488.so
2021/06/07 13:03:03 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/fuzie/.config'
2021/06/07 13:03:03 Audioserver package name: pulseaudio
2021/06/07 13:03:03 Audioserver package version: 14.2
2021/06/07 13:03:03 Detected PulseAudio
2021/06/07 13:03:03 couldn't parse server version, regexp didn't match version: 14.2
2021/06/07 13:03:03 Checking for updates
2021/06/07 13:03:03 Getting caps for: /home/fuzie/.local/bin/noisetorch
2021/06/07 13:03:03 Audioserver package name: pulseaudio
2021/06/07 13:03:03 Audioserver package version: 14.2
2021/06/07 13:03:03 Detected PulseAudio
2021/06/07 13:03:03 couldn't parse server version, regexp didn't match version: 14.2
2021/06/07 13:03:03 Connected to audio server. Server name ''
2021/06/07 13:03:03 Output alsa_output.pci-0000_00_1f.3.analog-stereo, {Index:0 Name:alsa_output.pci-0000_00_1f.3.analog-stereo Description:Built-in Audio Analog Stereo SampleSpec:{Format:3 Channels:2 Rate:44100} ChannelMap:[1 2] ModuleIndex:6 Cvolume:[18378 24273] Muted:false MonitorSourceIndex:0 MonitorSourceName:alsa_output.pci-0000_00_1f.3.analog-stereo.monitor Latency:0 Driver:module-alsa-card.c Flags:183 PropList:map[alsa.card:0 alsa.card_name:HDA Intel PCH alsa.class:generic alsa.device:0 alsa.driver_name:snd_hda_intel alsa.id:ALC236 Analog alsa.long_card_name:HDA Intel PCH at 0xa4320000 irq 131 alsa.name:ALC236 Analog alsa.resolution_bits:16 alsa.subclass:generic-mix alsa.subdevice:0 alsa.subdevice_name:subdevice #0 device.access_mode:mmap+timer device.api:alsa device.buffering.buffer_size:352800 device.buffering.fragment_size:176400 device.bus:pci device.bus_path:pci-0000:00:1f.3 device.class:sound device.description:Built-in Audio Analog Stereo device.form_factor:internal device.icon_name:audio-card-pci device.product.id:9d71 device.product.name:Sunrise Point-LP HD Audio device.profile.description:Analog Stereo device.profile.name:analog-stereo device.string:front:0 device.vendor.id:8086 device.vendor.name:Intel Corporation module-udev-detect.discovered:1 sysfs.path:/devices/pci0000:00/0000:00:1f.3/sound/card0] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:65537 CardIndex:0 Ports:[{Name:analog-output-speaker Description:Speakers Pririty:10000 Available:0} {Name:analog-output-headphones Description:Headphones Pririty:9900 Available:1}] ActivePortName:analog-output-speaker Formats:[{Encoding:1 PropList:map[]}]}
2021/06/07 13:03:03 Output combined, {Index:1 Name:combined Description:Simultaneous output to Built-in Audio Analog Stereo SampleSpec:{Format:3 Channels:2 Rate:44100} ChannelMap:[1 2] ModuleIndex:14 Cvolume:[55711 60296] Muted:false MonitorSourceIndex:2 MonitorSourceName:combined.monitor Latency:0 Driver:module-combine-sink.c Flags:162 PropList:map[device.class:filter device.description:Simultaneous output to Built-in Audio Analog Stereo device.icon_name:audio-card] RequestedLatency:0 BaseVolume:65536 SinkState:2 NVolumeSteps:65537 CardIndex:4294967295 Ports:[] ActivePortName: Formats:[{Encoding:1 PropList:map[]}]}
2021/06/07 13:03:05 Calling: /usr/bin/pkexec /home/fuzie/.local/bin/noisetorch -setcap
2021/06/07 13:03:09 Couldn't setcap self as root: exit status 127
2021/06/07 13:03:12 Deleted temp librnnoise: /tmp/librnnoise-734742488.so

**Comment by lawl** [comment]
This is not a bug in noisetorch.

> 2021/06/07 13:03:09 Couldn't setcap self as root: exit status 127

See https://manpages.ubuntu.com/manpages/precise/en/man1/pkexec.1.html

> If the
> calling process is not authorized or an authorization could not be obtained through
> authentication or an error occured, pkexec exits with a return value of 127.

Your pkexec denies us root, i can't help you with that. You'll need to fix that or you can work around it by setting the permissions manually as per install instructions in the readme

    sudo setcap 'CAP_SYS_RESOURCE=+ep' ~/.local/bin/noisetorch

You'd have to do that after every update.

**Comment by jakob1379** [comment]
Jesus. I'm an idiot. Sorry for bothering you and thank you for your time!
