### ISSUE TITLE
cant open NoiseTorch in kali linux

### ISSUE THREAD

**Issue by shherlocked** [lawl/NoiseTorch#147]
whenever I try to launch NoiseTorch, it shows this error.

![Screenshot_2021-06-10_05-06-00](https://user-images.githubusercontent.com/85661643/121468610-9c5e9680-c9aa-11eb-92c6-b96407baeb56.png)

pls help

**Comment by lawl** [comment]
follow the install instructions, i can't tell you more than that unfortunately.

**Comment by shherlocked** [comment]
i added .local/bin to the PATH, still getting the same error.

**Comment by bluthen** [comment]
1. Is the file there: _ls -la ~/.local/bin/noisetorch_
2. Is it executable: chmod a+rx ~/.local/bin/noisetorch
3. What happens when you run it from a shell: `~/.local/bin/noisetorch`
