### ISSUE TITLE
Move to GoTK3

### ISSUE THREAD

**Issue by DaKine23** [lawl/NoiseTorch#15]
May be you can consider using GTK3 to make your tool better fit into Linux DE. I can probably contribute some PR myself for that.

P.S. awesome work keep going!

**Comment by lawl** [comment]
hey, thanks for the suggestion, unfortunately this is very, very unlikely to happen as would for example make one statically linked binary unrealistic. I know it doesn't look native, but this is a deliberate trade-off, sorry.

**Comment by vn-ki** [comment]
You are trading accessibility and other native features by using an imgui instead of a proper gui toolkit.

For such a simple application which is targetting only linux, I don't see the benefit.

**Comment by lawl** [comment]
Ok, well, that's my decision and my reasoning for my decision, you are free to disagree with me.
