### ISSUE TITLE
Noisetorch doesnt launch

### ISSUE THREAD

**Issue by akiro03** [lawl/NoiseTorch#153]
When I launch noisetorch.desktop a file with setting open. 

Im new to Linux so this may be something obvious but I really dont know what do to

![Help](https://user-images.githubusercontent.com/85848461/122455822-1c898b00-cfad-11eb-95c5-db3193114b89.png)

**Comment by DuttaAB-dev** [comment]
> When I launch noisetorch.desktop a file with setting open.
> 
> Im new to Linux so this may be something obvious but I really dont know what do to
> 
> ![Help](https://user-images.githubusercontent.com/85848461/122455822-1c898b00-cfad-11eb-95c5-db3193114b89.png)

Try this:
1 Right click on the file.
2 Go to properties > permissions.
3 Check "run as executable".

Hope this works.

**Comment by akiro03** [comment]
It worked. Everything runs perfect now. Thank you for your help :)

**Comment by DuttaAB-dev** [comment]
Your welcome. Hope you have fun exploring the wonderful world of linux!

**Comment by lawl** [comment]
thanks for helping out @DuttaAB-dev !

closing this as it's resolved.
