### ISSUE TITLE
Fails to start when pulseaudio's socket is running elsewhere

### ISSUE THREAD

**Issue by acheronfail** [lawl/NoiseTorch#154]
### Context

I have my `pulseaudio` server configured so it can be shared by multiple users simultaneously. This is the setup in a nutshell:

```
$ cat /etc/pulse/client.conf
autospawn = no # spawned only once by pulseaudio.socket
default-server = /tmp/pulse-server
```

```
$ cat /etc/pulse/default.pa
# ... normal config file, except for this line
load-module module-native-protocol-unix auth-group=audio socket=/tmp/pulse-server
# ...
```

This setup just ensures that different users can share the same audio devices at the same time.

### NoiseTorch

When I run `noisetorch` with this setup, it outputs this and fails to start:

```
$ noisetorch -log
2021/06/21 10:23:08 Application starting. Version: 0.11.3 (archlinux)
2021/06/21 10:23:08 CAP_SYS_RESOURCE: true
2021/06/21 10:23:08 Checking if config needs to be initialized
2021/06/21 10:23:08 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/acheronfail/.config'
2021/06/21 10:23:08 Wrote temp librnnoise to: /tmp/librnnoise-070961303.so
2021/06/21 10:23:08 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/acheronfail/.config'
Couldn't create pulseaudio client: dial unix /run/user/1000/pulse/native: connect: resource temporarily unavailable
2021/06/21 10:23:08 Deleted temp librnnoise: /tmp/librnnoise-070961303.so
```

I've confirmed that reverting to a single pulseaudio server per user causes `noisetorch` to function normally.

### Attempted Solutions

I've tried `PULSE_RUNTIME_PATH=/tmp/pulse-server noisetorch -log` but then it attempts to access `/tmp/pulse-server/native` which doesn't exist - the socket is at `/tmp/pulse-server`...

Is there any way to configure `noisetorch` to support this? :thinking:

**Comment by lawl** [comment]
how do you tell other applications about the location of the socket? i don't really want to parse the pulse config to discover the location.

unfortunately, no there's currenly to way to configure noisetorch to do this. The only workaround that i can think of right now is to create a directory with the RUNTIME_DIR structure and symlinking your socket into it.

**Comment by acheronfail** [comment]
> how do you tell other applications about the location of the socket? i don't really want to parse the pulse config to discover the location.

I don't... They all just seem to work? If I run `pactl info` it shows the server running at `/tmp/pulse-server`. I've never had any issues with any application except `noisetorch` 😅 

> unfortunately, no there's currenly to way to configure noisetorch to do this. The only workaround that i can think of right now is to create a directory with the RUNTIME_DIR structure and symlinking your socket into it.

I was thinking the same... Definitely not ideal, but since everything else automatically finds the pulseaudio server I figure it's alright?

**Comment by lawl** [comment]
i see. yeah, we don't use libpulse, but a half baked reimplementation.

thinking about this, we also grab other information from the runtime dir, off the top of my head at least the `pid` file to grab the pid of the PA daemon.

So, unfortunately, I think this is just a setup that i won't support, as it's pretty niche.

**Comment by acheronfail** [comment]
> we don't use libpulse

Ah, I guess this is most likely why. That explains it.

> So, unfortunately, I think this is just a setup that i won't support, as it's pretty niche.

Completely understand. 🙂
