### ISSUE TITLE
Package for Flatpak

### ISSUE THREAD

**Issue by superuser-miguel** [lawl/NoiseTorch#157]
Please package for flatpak, post on flatub or provide a yaml, json manifest? Thanks

**Comment by lawl** [comment]
no

**Comment by advaithm** [comment]
if someone else were to provide a flatpak manifest would this be reconsidered?

**Comment by lawl** [comment]
no. people are free to offer third party packages in compliance with the license, but i will not offer an official flatpak a) because i don't like flatpak and b) i don't want to have to support it.

**Comment by razzeee** [comment]
Had a go at this here https://github.com/razzeee/io.github.lawl.noisetorch/blob/main/io.github.lawl.noisetorch.yml but it seems like we can't `setcap` with flatpak, so it's probably not being able to be packaged.
