### ISSUE TITLE
You saved my life

### ISSUE THREAD

**Issue by nocturn9x** [lawl/NoiseTorch#160]
Sorry for the noise (pun intended), but I just wanted to express my gratitude for having created this thing. I mainly use it on discord since the new noise reduction system is propietary and only runs on windows and this works like a charm. I have a noisy mechanical keyboard and my friends' ears will finally be able to rest!

I'll become a patron soon too, can't let this die, keep it up!

**Comment by lawl** [comment]
> I have a noisy mechanical keyboard and my friends' ears will finally be able to rest!

Cherry mx blue > *

**Comment by nocturn9x** [comment]
> > I have a noisy mechanical keyboard and my friends' ears will finally be able to rest!
> 
> Cherry mx blue > *

I have brown switches (the brand is from my keyboard's manufacturer so I don't remember it) >.<

but I agree, they're just *way* too noisy
