### ISSUE TITLE
Does noise torch support headphones with inbuilt mic?

### ISSUE THREAD

**Issue by 7549brijesh** [lawl/NoiseTorch#162]
I have boat Rockerz 510 which has a inbuilt mic which connects via the bluetooth when i connect my headphones in noisetorch I get is this:
(?incompatible) Boat Rockerz 510 on both headphone and microphone 
![2021-07-18_10-55](https://user-images.githubusercontent.com/25589680/126058838-d635b8d5-ad21-4a71-8e29-397d295ee15d.png)

And when i use noisetorch in google meet I get is this:
![2021-07-18_10-58](https://user-images.githubusercontent.com/25589680/126058878-2cde5bd1-eaba-4bb0-a475-48e033dd2b83.png)

Am I doing something wrong Please guide me through this I am new to linux and noisetorch

**Comment by lawl** [comment]
as it sais, incompatible. Nothing you can do, sorry.
