### ISSUE TITLE
[REQ] Set license on GH

### ISSUE THREAD

**Issue by forart** [lawl/NoiseTorch#167]
Hi there, this project is awesome !

Since we've collected it in our [HyMPS project list](https://github.com/forart/HyMPS) (in the [Voice section](https://github.com/forart/HyMPS/blob/main/Voice.md)), can you please set licensing terms on this git ?

Our "problem" is that actual ones does not generates the correct badge: 

![](https://flat.badgen.net/github/license/lawl/NoiseTorch/?label=LICENSE)
(generate string: https://flat.badgen.net/github/license/lawl/NoiseTorch/?label=LICENSE)

We've discovered that GH needs the license must be specifically formatted, like this one:

https://github.com/werman/noise-suppression-for-voice/blob/master/LICENSE

Thanks in advance.

**Comment by lawl** [comment]
the license file is there. github not being able to figure out the license (GPLv3-extended) is a github problem and not a me problem. i don't see an option in the project options to manually specify it, so nothing i can do about that, sorry.

**Comment by forart** [comment]
Thanks anyway.
