### ISSUE TITLE
Virtual Microphone is silent

### ISSUE THREAD

**Issue by xZeroW** [lawl/NoiseTorch#169]
physical mic gets audio but NT don't, was working yesterday
used NT as default, was working so far, just saw I should not use this way, anyways...

what i've tried so far:
restart/Shutdown pc
reload NT
the troubleshooting steps

on pavucontrol input tab mic bar moves but NT don't
on output tab LADSPA moves, Null Output don't

i don't have this file: ~/.pulse/daemon.conf

[noisetorch.log](https://github.com/lawl/NoiseTorch/files/7034684/noisetorch.log)
![pavu-input](https://user-images.githubusercontent.com/14045316/130514740-3e368e90-260a-4c54-8660-46db4a5a9438.png)
![pavu-output](https://user-images.githubusercontent.com/14045316/130514744-bb585de7-66fd-4137-b145-5a4e2a9c452a.png)

edit: gonna try to reinstall it

**Comment by lawl** [comment]
> i don't have this file: ~/.pulse/daemon.conf

create it if it doesn't exist.

> was working yesterday

did you do a system update in between, or anything?

**Comment by xZeroW** [comment]
You are a god!
Making the daemon file worked!!
Thanks

**Comment by xZeroW** [comment]
Had to reopen the issue :(
Android Studio keeps messing with my audio, everytime I run it I get static noises until I open a app or restart the avd
I can't get any input from any NT device, they are even greyed out now

[noisetorch.log](https://github.com/lawl/NoiseTorch/files/7079493/noisetorch.log)

![Screenshot-20210830174325-1149x842](https://user-images.githubusercontent.com/14045316/131402850-24158cae-1c4a-4146-be6e-8c0a99731463.png)

![Screenshot-20210830174236-1149x842](https://user-images.githubusercontent.com/14045316/131402751-ad07ccf4-3c50-4945-9e7c-9758a68e4b39.png)

**Comment by xZeroW** [comment]
It worked again, did nothing '-'
sorry about that
