### ISSUE TITLE
Using a custom RNNoise model

### ISSUE THREAD

**Issue by akashrajkn** [lawl/NoiseTorch#175]
Hi, Thank you for the amazing work, I love it :)

I trained a custom RNNoise model and I would like to use it instead of the default one. How do I go about it?

**Comment by lawl** [comment]
you will need to patch the `rnnoise_init` function here: https://github.com/lawl/NoiseTorch/blob/master/c/ladspa/module.c#L53 to load it. Also make sure to restart pulseaudio if you had the old module loaded previously, pulseaudio keeps it cached i think. Does that help?

**Comment by akashrajkn** [comment]
Yes, that answers my question. I will try this out and get back to you if I run into issues.
