### ISSUE TITLE
Using NoiseTorch inside Docker

### ISSUE THREAD

**Issue by NewBermuda** [lawl/NoiseTorch#176]
Hi there! Really like what you're doing with NoiseTorch.

Right now, I am trying to use NoiseTorch inside a Docker container.
How can I make use of the virtual microphone only using the terminal?
Inside Docker, I have been using an ALSA config file to set the default microphone to use.
I can't seem to find which sound card to specify to include the noise cancellation.
Do you know of a way to use NoiseTorch as the default microphone inside a container?

This is my output for arecord -l (I'm using the Yamaha microphone).
<img width="470" alt="Bildschirmfoto 2021-09-13 um 13 40 48" src="https://user-images.githubusercontent.com/13998895/133025033-9586de5a-4cd2-40e9-a205-0e61838e326e.png">

**Comment by lawl** [comment]
you need to do that via pulseaudio, not alsa. Probably something like `pacmd list-sources` and `pacmd set-default-source 42`

**Comment by mlcdf** [comment]
Hello @NewBermuda,
By any chance, did you find a solution?
