### ISSUE TITLE
With PulseAudio, switching default audio device while NoiseTorch is active means it sends audio to that device

### ISSUE THREAD

**Issue by Tvtossen** [lawl/NoiseTorch#177]
if you're switching into a speaker this will mean a very mean surprise as the audio loops back into your microphone and causes a very loud noise.
Doing this also seems to cause some static here and there in the audio

**Comment by lawl** [comment]
pulseaudio does that. We tell it to not do such things, it does such things anyways. Unfortunately the only thing i can tell you is to use pavucontrol to switch things per app, and don't touch the default device white noisetorch is active.

Unless someone knows of something i can do about this, i'm not aware of anything. Sorry :(
