### ISSUE TITLE
[Feature Request] CLI launcher

### ISSUE THREAD

**Issue by krisezra87** [lawl/NoiseTorch#180]
I use the crap out of this tool so TYVM, but I try to keep a CLI/keyboard centric workflow.  Is there now (or could there be) a way to launch or reload from the terminal?  Perhaps with a JSON or YML file for config?

Thanks!

**Comment by lawl** [comment]
> Is there now (or could there be) a way to launch or reload from the terminal?

have you tried `noisetorch -h` and see what happens?

**Comment by krisezra87** [comment]
This is exactly what I was looking for!  Two notes: 1) It would be great to have this in the readme / populate the wiki / submit a blurb to `man`, and 2) the CLI option seems to misbehave when you set both the source and sink in one call.  For whatever reason it says "inconsistent state".  I CAN get it to work by spawning a separate noisetorch process for each, but I don't think that is your intention.

**Comment by lawl** [comment]
> I CAN get it to work by spawning a separate noisetorch process for each, but I don't think that is your intention.

no, this is actually intended. I don't remember the exact issue, but yeah, it was easier to implement.

And no, the CLI will probably stay hidden-ish, it was contributed by someone else and I personally don't use it, so it's a bit neglected and weird at times. It's there for scripting for the people who need it, but not advertised on purpose.

**Comment by krisezra87** [comment]
Ah ok rock and roll.  I will do a separate spawn, and for anyone else looking they can verify their approach here.  Thanks for such a useful tool!
