### ISSUE TITLE
Kubuntu?

### ISSUE THREAD

**Issue by Shadowblitz16** [lawl/NoiseTorch#190]
I installed this how do I use it on kubuntu?

**Comment by lawl** [comment]
the same you use it anywhere else. hope that helps.

**Comment by Shadowblitz16** [comment]
the application didn't launch when I clicked on it in the kde application menu

**Comment by lawl** [comment]
can you try the first paragraph here: https://github.com/lawl/NoiseTorch/wiki/Troubleshooting ?

**Comment by Shadowblitz16** [comment]
```
shadowblitz16@Kubuntu-Node202:~$ noisetorch -log
noisetorch: command not found
shadowblitz16@Kubuntu-Node202:~$ noisetorch -log > noisetorch.log
noisetorch: command not found
shadowblitz16@Kubuntu-Node202:~$ 
```

**Comment by lawl** [comment]
then you haven't installed it correctly. please follow the instructions again.

> I realized your download isn't named the same or have the same extension as the instructions

it is named exactly the same.

**Comment by Shadowblitz16** [comment]
ah I see it was downloaded to a weird folder.
but even so when I extract it into my home folder it doesn't work. does it need to be extracted a certain way?

**Comment by Shadowblitz16** [comment]
ahhh I got it for some reason the kde menu couldn't launch it.
opening the binary directly made it run.
