### ISSUE TITLE
Launch options

### ISSUE THREAD

**Issue by mefflecakes** [lawl/NoiseTorch#194]
Would it be possible to automatically load noisetorch (using the last used microphone) and minimize/close to background? I know it's a very first world problem, but I'd really like to log in and have no open windows/extra clicks required.

Thanks for such a fantastic tool 😀

**Comment by Knebergish** [comment]
Hello.
Wiki contains this article: [Start automatically with Systemd](https://github.com/lawl/NoiseTorch/wiki/Start-automatically-with-Systemd)
This may be what you need.

**Comment by mefflecakes** [comment]
This is perfect, thank you so much :)
