### ISSUE TITLE
Consider implementing DTLN

### ISSUE THREAD

**Issue by MariasStory** [lawl/NoiseTorch#195]
Hi,
Thank you for the cool solution.

Please consider implementing DTLN for the noise suppression:
https://github.com/breizhn/DTLN

Different model formats are in this repo:
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/117_DTLN

Sincerely

**Comment by lawl** [comment]
Thank you, i'm very interested in new open source denoising tech and papers that provide code (i'm very small brained and don't understand them).

So this project is very interesting, but the last time i looked at it, it didn't work with TFlite, which now seems fixed!

I still have a few reservations.

16khz. Ugh, i really want full-band and not crappy telephone quality. So for me personally, that's an immediate disqualification.

That being said, if it *significantly* outperforms rnnoise it may still provide value to some people and i may consider adding it.

But i couldn't find any comparison against rnnoise from a quick glance. Does anyone have actual experience with it?

**Comment by lawl** [comment]
Also doesn't have vad, as it seems, so we'd have to either change the network, add it, and retrain, or still also pipe it through rnnoise.

Unless it's so good we can ditch the VAD completely.

**Comment by MariasStory** [comment]
Hi @lawl,
Thanks for the answer.
You've got a point with 16 kHz.
Maybe you can check this article for comparison:
https://vkteam.medium.com/neural-networks-vs-vacuum-cleaners-or-how-we-denoised-vk-calls-da8fe430f185

**Comment by lawl** [comment]
i looked into this a bit more. full band really is a killer criteria for me.
