### ISSUE TITLE
Other way to donate instead of Patreon

### ISSUE THREAD

**Issue by kadogo** [lawl/NoiseTorch#198]
Hello @lawl 

I tested today the headphone option and because it worked great I wanted to make a one-time donation, but I didn't find any listed alternative.

I searched about an email to contact you directly, but I didn't find any.

If there are no alternatives, it's not an issue, but I think it could profit for people that only to do a one-time donation.

Big thanks for your software and good work for the future.

Cheers

**Comment by lawl** [comment]
Hey, glad you like it.

It's always possible to just donate for one month on patreon and then cancel. Though I also understand why some people may not want to do that. That's fine too though, nobody is forced to donate anyways.
