### ISSUE TITLE
A problem with wireplumber

### ISSUE THREAD

**Issue by MobCode100** [lawl/NoiseTorch#199]
I'm using Fedora 35, there's a problem with wireplumber in the case that it can't detect noisetorch microphone. 
After loading noisetorch, OBS and Discord can't detect noisetorch microphone.

Looking at PulseAudio Volume Control it shows unknown input:
![Screenshot from 2021-11-22 00-53-48](https://user-images.githubusercontent.com/66469454/142771555-d70f0b06-498a-407b-bae6-c75fc7b49cce.png)

wireplumber version: 0.4.5-3

Reverting to the old session manager which is the pipewire-media-session fixed the problem for me.
Using the command `sudo dnf swap wireplumber pipewire-media-session`

I'm new to submitting issues, any additional information I'll gladly provide.

**Comment by lawl** [comment]
Then, that sounds like a bug in wireplumber, no?

**Comment by MobCode100** [comment]
> Then, that sounds like a bug in wireplumber, no?
I'm very sorry if i'd posted in the wrong place, i think it is an issue in wireplumber.
Thank you very much for your time 👍

**Comment by lawl** [comment]
No worries. If you do file a bug in wireplumber feel free to post the link here for other people coming across this issue.
