### ISSUE TITLE
Is there a way to start capture earlier? Start of the speech gets cut off.

### ISSUE THREAD

**Issue by Boris-Barboris** [lawl/NoiseTorch#20]
At the expense of latency of course. Is there a setting or a pointer in the right direction would be appreciated, maybe there is a setting in underlying library somewhere.

**Comment by lawl** [comment]
Try lowering the Voice Activation Threshold. You can set it to 0 to confirm that this is the issue, and then find a value that works for you.

**Comment by Boris-Barboris** [comment]
Indeed, at 0 it does not miss the start of my voice, thx.
