### ISSUE TITLE
[Feature Request] Custom notch filters in a tab

### ISSUE THREAD

**Issue by safronov-nikolai** [lawl/NoiseTorch#200]
Hi ^_^
Is it possible to add a tab with the possibility to add custom notch filters? That would help a lot to get the grounding loop ( https://en.wikipedia.org/wiki/Ground_loop_(electricity) ) hum killed.
In windows it is best done like this by EqualizerAPO:
https://fallwind.blog/2018/03/18/how-to-handle-headset-microphone-buzzing-noise-ground-loop-the-software-way/

I hate to see the 50, 100, 150 and so on Hz in the recordings. Thank you for your work!

**Comment by lawl** [comment]
Do you have a suggestion for implementing something like this without introducing new configuration options?

**Comment by safronov-nikolai** [comment]
In theory yes, you could analyse a quiet room. As each setup and each mic needs different amounts of notch filtering on different wavelengths, you need to adjust the frequencies and the Q-factor (width of the notch filter). My test showed that often you need to notch down from 50Hz all the way to 1000Hz in 50Hz intervals with very thin profiles (the 50Hz is a bit thicker though). And if you live in a country with 60Hz you will have the same there but it will be the harmonics of 60Hz instead.
In the example above for EqualizerAPO they use a custom clear text file to save the notch filtering settings (examples of them are linked there). It could be possible to parse a simmilar in sturcture file if you do not want to add a GUI for this feature. But if you do not want extra configuration and just one button approach, then you would need to
0. Get the sound FFT spectrum from 15Hz to about 1300Hz.
1. Figuer out what is it 50 or 60 Hz.

**Comment by lawl** [comment]
That would still complicate the setup a lot, "calibration" etc. I don't want that. NoiseTorch currently has one slider for configuration, and people don't understand *that* and I'd like to get rid of it.

If this cannot be done in a fully transparent (to the user) fashion, then that's a no from me. If someone thinks it *can* be done and wants to implemented, I *may* merge it, if it doesn't impact other users. But for now, this seems like too much additional complexity for too little gain.
