### ISSUE TITLE
Configurable voice grace period

### ISSUE THREAD

**Issue by MabezDev** [lawl/NoiseTorch#202]
First of all, thanks for this module! My friends have never been happier not to hear my keyboard :D.

If I understand this code correctly: https://github.com/lawl/NoiseTorch/blob/4aca9e658874f8c72fff3a03039de40e294d1822/c/ladspa/module.c#L114-L116

once voice data is detected and then subsequently not detected, there is a period in which the microphone's data is still transmitted before going back to silence.

I'd like to be able to increase this period. I often find the last word I say is cut short, or hard to hear, especially when I'm being a bit quiet.

Does this seem reasonable?

**Comment by lawl** [comment]
Yes and no. Indeed this value was chosen pretty arbitrarily by me. But it seems to work well for almost anyone.

I don't want another configuration option. Have you played with this value and found one that gives you a better trade-off between not letting noise through and cutting words off?

**Comment by MabezDev** [comment]
Thanks, I think you're right playing with this value didn't yield the results I expected. Moving my physical microphone to a better position stopped the clipping.
