### ISSUE TITLE
Load on startup

### ISSUE THREAD

**Issue by Smart-Helper** [lawl/NoiseTorch#203]
I love this program!

Would it be possible to get some launch parameter or some option to autoload NoiseTorch on program startup?

I have NoiseTorch on autostart when i boot my computer but i have to manually click on "Load NoiseTorch" everytime and then close it. This is not a big thing but maybe this could be automated?

Thanks for the effort!

**Comment by lawl** [comment]
https://github.com/lawl/NoiseTorch/wiki/Start-automatically-with-Systemd
