### ISSUE TITLE
Mistakenly removes initial plosives after silence.

### ISSUE THREAD

**Issue by sakaru** [lawl/NoiseTorch#204]
### Description
Using version `0.11.4` (latest version available in Achlinux)

NoiseTorch seems to remove the first few milliseconds of a word spoken after a silence if that word begins with a plosive, most noticeable with 't' and 'p'. This problem doesn't present itself when not at the start of an utterance after silence.

I tested this in an otherwise quiet room, with headphones.

### Steps to Reproduce:
1. Start NoiseTorch, set any Voice Activation Threshold and Load. I tried thresholds varying from 5% to 80% and the effect was the same.
2. Start a recording application, I use `gnome-sound-recorder`, set to use NoiseTorch Microphone.
3. Start recording, let there be silence, then say "tiny tim" or "peter piper", with silence between the words.

### Actual Results:
Listen back to the recording and it will have cut the initial of the "t" or "p" sounds from the audio.

### Expected Results:
I expect NoiseTorch to not drop the initial plosives.

**Comment by lawl** [comment]
Probably the neural network not classifying it as speech early enough.

We'd probably have to introduce more latency to fix that. Don't want to do that.

**Comment by neurolabs** [comment]
@lawl What about the following solution without introducing more latency:

* Buffer the last X ms of audio constantly, e.g. in a ringbuffer
* When threshold is reached, play back from the start of the buffer at 1.5x speed without pitch-up) until caught up
* resume live playback.

Probably this would be quite complex in implementation, or wouldn't it?
