### ISSUE TITLE
Allow window minimize or similar

### ISSUE THREAD

**Issue by kjkondratuk** [lawl/NoiseTorch#209]
First, let me say NoiseTorch is great and I'm really enjoying it!  This would probably be best filed under "feature request", but having come from using Cadmus that utilized a statusbar integration to stay out of your way as you used the tool, I find the NoiseTorch window gets a bit in the way--though you can reduce it to a comically small size.  This is mostly due to the fact that the window cannot be minimized or otherwise hidden.

Technical Details:
1. Arch Linux
2. Kernel 5.15.8
3. PulseAudio 15.0
4. Gnome 41.2

I had a brief look around to see if it was something I could do a PR for, but it looks like maybe nucular doesn't support it?  Happy to help if I can!

**Comment by lawl** [comment]
Ok, this might sound like a dumb question. But why not just close the window and re-open it when you need it? It doesn't need to be open for the virtual microphone to work.

**Comment by kjkondratuk** [comment]
That's valid.  Maybe it's a user experience issue then, because it's not clear (at least to me) that you can do that without unloading the module.  Thanks for the tip!  Maybe a "Load in the background" checkbox that will close the window after NoiseTorch is loaded would make it more intuitive?

**Comment by lawl** [comment]
I agree it's a UX issue, but i'm not sure what the solution is.

I don't like your checkbox suggestion as it clutters the options and is misleading, making people who currently don't believe the window needs to stay open that it does. It just inverts the problem at best, and causes more confusion at worst.

**Comment by kjkondratuk** [comment]
Fair.  Guess you'll know if it comes up again.  I'll close this.  Thanks for your replies!
