### ISSUE TITLE
 Couldn't create pulseaudio client

### ISSUE THREAD

**Issue by zevv** [lawl/NoiseTorch#21]
Starting 0.5.0:

```
2020/07/18 15:48:26 Application starting. Version: 0.5.0-beta
2020/07/18 15:48:26 Checking if config needs to be initialized
2020/07/18 15:48:26 Wrote temp librnnoise to: /tmp/librnnoise-653462070.so
2020/07/18 15:48:26 Checking for updates
2020/07/18 15:48:26 Couldn't create pulseaudio client
```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

**Comment by lawl** [comment]
Hey, on mobile atm.

Whats your $XDG_RUNTIME_PATH?

**Comment by zevv** [comment]
`/run/user/1000`

**Comment by lawl** [comment]
Then it might be that your pulseaudio speaks a protocol version lower than we support atm, 16.04 is quite old: https://github.com/lawl/pulseaudio/blob/master/client.go#L24

But cant confirm this atm, because on mobile. Can look deeper into it tmrw.

**Comment by zevv** [comment]
Ah you're not using any system PA libraries, everything is statically linked of course. Well, I'm tied to 16.04 because of other dependencies, so I'll check again one day after I get to update.

Thanks for the quick support!

**Comment by lawl** [comment]
Less of a static linking problem, more of a "we use a custom half baled reimplementation of libpulse". IF this is the problem.

**Comment by cellofellow** [comment]
I've had this same result on Arch Linux
```
$ noisetorch 
2020/07/18 14:16:39 Application starting. Version: 0.5.0-beta-1-g6db43dc
2020/07/18 14:16:39 Checking if config needs to be initialized
2020/07/18 14:16:39 Wrote temp librnnoise to: /tmp/librnnoise-465076362.so
2020/07/18 14:16:39 Couldn't create pulseaudio client
$ uname -r
5.7.9-arch1-1
```

I'm using Wayland (with Sway) and not X11, so not sure if that has anything to do with it.

**Comment by farmerbobathan** [comment]
I also get the same issue on Arch Linux
`$ noisetorch
2020/07/18 15:23:06 Application starting. Version: 0.5.0-beta
2020/07/18 15:23:06 Checking if config needs to be initialized
2020/07/18 15:23:06 Wrote temp librnnoise to: /tmp/librnnoise-327504421.so
2020/07/18 15:23:06 Couldn't create pulseaudio client

$ uname -r
4.19.132-2-surface-lts
`
I'm using wayland with gnome.

**Comment by lawl** [comment]
@cellofellow @farmerbobathan can you both also please confirm your XDG_RUNTIME_DIR

**Comment by lawl** [comment]
Okay, just got back to a computer and it's pretty late here. Unfortunately I didn't log the actual error that occurs here. Here's a build that logs the actual error. Please try again with this one so we can see what's going on: 
[noisetorch.zip](https://github.com/lawl/NoiseTorch/files/4942854/noisetorch.zip)

unpack the binary, `chmod +x` it, run it.

Or if you prefer to build from source, this is already pushed to master, so you can just build that, but I don't want to push an official release just for this yet: https://github.com/lawl/NoiseTorch/commit/a65e5d28a76d7f0c04003b4af12be21de259389b

**Comment by cellofellow** [comment]
Here's what I got

```
noisetorch 
2020/07/18 19:11:03 Application starting. Version: 0.5.0-beta
2020/07/18 19:11:03 Checking if config needs to be initialized
2020/07/18 19:11:03 Wrote temp librnnoise to: /tmp/librnnoise-287632414.so
2020/07/18 19:11:03 Couldn't create pulseaudio client: open /home/josh/.config/pulse/cookie: no such file or directory
```

My `XDG_RUNTIME_DIR` is `/run/usr/1000` btw.

**Comment by lawl** [comment]
Ahh, yep it is in fact impossible to connect to PA without the cookie. Possibly related to #26 could you also post your $XDG_CONFIG_HOME and if you can find that file in $XDG_CONFIG_HOME/pulse/cookie? If soi'll ship a fix for this tomorrow, if you cant find it there, you will need to find out why your system is missing it.

**Comment by zevv** [comment]
Two different issues here: on my ubuntu 16.04 the cookie is there, but the new binary indeed reports a version problem:

```
2020/07/19 06:00:39 Couldn't create pulseaudio client: pulseAudio server supports version 30 but minimum required is 32
```

**Comment by farmerbobathan** [comment]
When I made ~/.config a symlink to $XDG_CONFIG_HOME noisetorch would work for me.

**Comment by lawl** [comment]
Okay, I'm working on a fix to respect XDG everywhere, which should fix the missing pulse cookie for at least some users. Let's continue that in #26 

As for the original issue `pulseAudio server supports version 30 but minimum required is 32` @zevv had. I think that's unfortunately a wontfix from me, because of limited time, 16.04 being EOL in a year, and most people seeming to run a newer version.

Feel free to reopen if you see an issue with this.
