### ISSUE TITLE
Can't autostart NoiseTorch with pipewire

### ISSUE THREAD

**Issue by jonnyteronni** [lawl/NoiseTorch#211]
Solved the issue adding this to config file. It seems is still executing too fast even with After=pipewire.service

[Service]
ExecStartPre=/bin/sleep 10

**Comment by devmattrick** [comment]
I can confirm this fixed the issue for me as well. It was driving me crazy, thanks for this!

**Comment by lawl** [comment]
I thought one of the advantages of systemd was that we don't need random sleeps and hope they work. So I'm not sure it's a good idea to document that as a default setting.

But this really isn't up to me, but to @detjensrobert

**Comment by devmattrick** [comment]
I thought it may be worthwhile to document it and just clearly label it as a workaround (this issue's existence might be enough, of course). It definitely would be better to find the root cause of this but I'm really not familiar enough with systemd and pipewire to really look into it.

**Comment by FichteFoll** [comment]
Can confirm this behavior on 2 machines usint pipewire.

The unit in question is as follows:
```ini
# /usr/lib/systemd/user/noisetorch-pulse.service
[Unit]
Description=NoiseTorch noise supression (for PulseAudio)
Requires=pulseaudio.socket

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/noisetorch -i
ExecStop=/usr/bin/noisetorch -u

[Install]
WantedBy=default.target
```

and the error message I receive is the following:
```
Jan 03 16:52:13 dracaena systemd[973]: Starting NoiseTorch noise supression (for PipeWire)...
Jan 03 16:52:13 dracaena noisetorch[980]: PulseAudio source not found: @DEFAULT_SOURCE@
Jan 03 16:52:13 dracaena systemd[973]: noisetorch-pipewire.service: Main process exited, code=exited, status=1/FAILURE
Jan 03 16:52:13 dracaena systemd[973]: noisetorch-pipewire.service: Failed with result 'exit-code'.
Jan 03 16:52:13 dracaena systemd[973]: Failed to start NoiseTorch noise supression (for PipeWire).
```

**Comment by lawl** [comment]
NoiseTorch seems to complain about the default device missing and that systemd unit does not look like the one one the wiki, which i believe explicitly handles that by waiting for it too?

**Comment by FichteFoll** [comment]
Indeed, this is a different unit from the [`noisetorch-bin` AUR package](https://aur.archlinux.org/packages/noisetorch-bin/). I'll try the one from the wiki to see whether waiting for the device is indeed what's missing.

**Comment by lawl** [comment]
Thanks. So this is AUR offloading work to me again. Thanks for letting me know. Please file issues with them and not me.

**Comment by FichteFoll** [comment]
The unit in the wiki doesn't work for me either. After having my device change its usb device unit name two times consecutively without any external influence, I eventually managed to get a debug log run with it only to run into the same problem. The first attempt just didn't work at all for some reason (no debug log enabled).

```
Jan 08 12:56:00 pinaceae systemd[615]: Started Noisetorch Noise Cancelling.
Jan 08 12:56:01 pinaceae systemd[615]: noisetorch.service: Main process exited, code=exited, status=1/FAILURE
Jan 08 12:56:01 pinaceae systemd[615]: noisetorch.service: Failed with result 'exit-code'.
-- Boot 14a3486ceec8497a9d500401ce2e8b0b --
Jan 08 13:00:32 pinaceae systemd[604]: Dependency failed for Noisetorch Noise Cancelling.
Jan 08 13:00:32 pinaceae systemd[604]: noisetorch.service: Job noisetorch.service/start failed with result 'dependency'.
-- Boot 99f0ba5995124e2482e5bad1e3dd0c44 --
Jan 08 13:06:39 pinaceae systemd[600]: Dependency failed for Noisetorch Noise Cancelling.
Jan 08 13:06:39 pinaceae systemd[600]: noisetorch.service: Job noisetorch.service/start failed with result 'dependency'.
-- Boot c00a82f2f1854ebcac63cde4c1d5320e --
Jan 08 13:07:43 pinaceae systemd[615]: Started Noisetorch Noise Cancelling.
Jan 08 13:07:43 pinaceae noisetorch[625]: 2022/01/08 13:07:43 Application starting. Version: 0.11.4 (official)
Jan 08 13:07:43 pinaceae noisetorch[625]: 2022/01/08 13:07:43 CAP_SYS_RESOURCE: true
Jan 08 13:07:43 pinaceae noisetorch[625]: 2022/01/08 13:07:43 Checking if config needs to be initialized
Jan 08 13:07:43 pinaceae noisetorch[625]: 2022/01/08 13:07:43 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/fichte/.config'
Jan 08 13:07:43 pinaceae noisetorch[625]: 2022/01/08 13:07:43 Wrote temp librnnoise to: /tmp/librnnoise-1087668342.so
Jan 08 13:07:43 pinaceae noisetorch[625]: 2022/01/08 13:07:43 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/fichte/.config'
Jan 08 13:07:43 pinaceae noisetorch[625]: 2022/01/08 13:07:43 Audioserver package name: PulseAudio (on PipeWire 0.3.43)
Jan 08 13:07:43 pinaceae noisetorch[625]: 2022/01/08 13:07:43 Audioserver package version: 15.0.0
Jan 08 13:07:43 pinaceae noisetorch[625]: 2022/01/08 13:07:43 Detected PipeWire
Jan 08 13:07:43 pinaceae noisetorch[625]: PulseAudio source not found: alsa_input.usb-Focusrite_Scarlett_Solo_USB_Y77R9F80B6C053-00.analog-stereo
Jan 08 13:07:43 pinaceae noisetorch[625]: 2022/01/08 13:07:43 Deleted temp librnnoise: /tmp/librnnoise-1087668342.so
Jan 08 13:07:43 pinaceae systemd[615]: noisetorch.service: Main process exited, code=exited, status=1/FAILURE
Jan 08 13:07:43 pinaceae systemd[615]: noisetorch.service: Failed with result 'exit-code'.
```

```
~ ∃ noisetorch -l
Sources:
	Device Name: Scarlett Solo (3rd Gen.) Analog Stereo
	Device ID: alsa_output.usb-Focusrite_Scarlett_Solo_USB_Y77R9F80B6C053-00.analog-stereo.monitor

	Device Name: Scarlett Solo (3rd Gen.) Analog Stereo
	Device ID: alsa_input.usb-Focusrite_Scarlett_Solo_USB_Y77R9F80B6C053-00.analog-stereo

	Device Name: Built-in Audio Analog Stereo
	Device ID: alsa_output.pci-0000_00_1b.0.analog-stereo.monitor

	Device Name: Tahiti HDMI Audio [Radeon HD 7870 XT / 7950/7970] Digital Stereo (HDMI)
	Device ID: alsa_output.pci-0000_01_00.1.hdmi-stereo.monitor

Sinks:
	Device Name: Scarlett Solo (3rd Gen.) Analog Stereo
	Device ID: alsa_output.usb-Focusrite_Scarlett_Solo_USB_Y77R9F80B6C053-00.analog-stereo

	Device Name: Built-in Audio Analog Stereo
	Device ID: alsa_output.pci-0000_00_1b.0.analog-stereo

	Device Name: Tahiti HDMI Audio [Radeon HD 7870 XT / 7950/7970] Digital Stereo (HDMI)
	Device ID: alsa_output.pci-0000_01_00.1.hdmi-stereo
```

**Comment by FichteFoll** [comment]
I suppose I should tag @detjensrobert according to the wiki page, so here goes.

**Comment by detjensrobert** [comment]
If your device changes its name often, theres not really a good way to match against it. Your best option is here is probably to add a short delay as noted above. Hacky, but I don't see a good way around that if theres not a static unit to order off of.

**Comment by FichteFoll** [comment]
Regardless of whether the device changes names or not, the unit is still started too early for pipewire because the source is not yet available at the time noisetorch wants to access it. I could add a static delay or `Restart=on-failure` to the unit, but imo this is something that either pipewire or noisetorch should handle on their sides.

Ideally pipewire would support a way of signaling that a new source (with a name) is found that a systemd unit could then listen on to initialize, or noisetorch would support a work mode where it waits until the provided source is available (indefinitely/timeout) since there is evidently some asynchronicity with initializing the source. Though the latter isn't so much different from just retrying the unit until it succeeds.

I'm going to use the following instantiable unit going forward:
```ini
# noisetorch@.service
[Unit]
Description=Noisetorch Noise Cancelling
Requires=pipewire.socket

[Service]
Type=simple
RemainAfterExit=yes
ExecStart=/usr/bin/noisetorch -i -s '%i'
ExecStop=/usr/bin/noisetorch -u
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
```

**Comment by lawl** [comment]
> Though the latter isn't so much different from just retrying the unit until it succeeds.

It wouldn't be that hard to add a flag to noisetorch where we loop until a device is available. But i'm not sure noisetorch is the right place to do this. Since as you said, we'd need to poll every `x` seconds too.

**Comment by detjensrobert** [comment]
Perhaps the "best" solution is to add those `Restart` and `RestartSec` to the unit in the wiki since this should be handled as part of the startup and not in noisetorch. @lawl do you mind making that change?

**Comment by FichteFoll** [comment]
As a quick note to the unit I posted above, it obviously does not automatically unload or reload when the respective device is removed and replugged, but that was a bother with the changing device unit name before anyway and unfortunately you can only pass one parameter into an instance.
