### ISSUE TITLE
Noisetorch doesn't work with pulseeffects

### ISSUE THREAD

**Issue by AlphaCraft9658** [lawl/NoiseTorch#213]
I wanted to use noisetorch to remove backround noise because it's so good and I tried to add some additional effects with pulseeffects but it doesn't work. Please could someone try to find a way to use noisetorch with pulseeffects or try to find a possible bug responsible for this otherwise? It would really help!

Thank you in advance!

**Comment by lawl** [comment]
Can't you load noisetorch and then apply pulseeffects on top of the noisetorch microphone?

**Comment by lawl** [comment]
No reponse
