### ISSUE TITLE
Noisetorch gives mic input through the headphones.

### ISSUE THREAD

**Issue by VictoryPlayZx90** [lawl/NoiseTorch#215]
[noisetc.log](https://github.com/lawl/NoiseTorch/files/7910552/noisetc.log)
Attached Log File.

**Comment by lawl** [comment]
Can you elaborate on the problem and how to reproduce it?

**Comment by VictoryPlayZx90** [comment]
The problem is when i load noisetorch i can hear myself from the headphones. 
Step to Reproduce - 
Start Noisetorch
Load Noisetorch.

**Comment by lawl** [comment]
Cannot reproduce. Suggest filing an issue with your distro. Arch likes to break stuff.
