### ISSUE TITLE
[REQ] fix license on GH

### ISSUE THREAD

**Issue by forart** [lawl/NoiseTorch#216]
Hi there, this project is awesome !

Since we've collected it in our [HyMPS project list](https://github.com/forart/HyMPS) (in the [Voice section](https://github.com/forart/HyMPS/blob/main/Voice.md)), can you please set licensing terms on this git ?

Our "problem" is that does not generates the correct badge: 

![](https://flat.badgen.net/github/license/lawl/NoiseTorch?label=LICENSE)
(generate string: https://flat.badgen.net/github/license/lawl/NoiseTorch/?label=LICENSE)

...maybe it's a GH setup issue ?

Thanks in advance.

**Comment by lawl** [comment]
This tries to detect the license from the LICENSE file automatically. This fails because we have additional clauses with the GPL. Complain to badgen or github, i can't set this manually as far as im aware.

**Comment by lawl** [comment]
#167 

I thought i remember this.

**Comment by forart** [comment]
Sorry, didn't remember we already asked.
