### ISSUE TITLE
Audio input device name is not "NoiseTorch Microphone" after update to pipewire 0.3.44

### ISSUE THREAD

**Issue by OctopusET** [lawl/NoiseTorch#218]
After I update pipewire version to 0.3.44. NoiseTorch device name is now `filter-chain-11`. It was `NoiseTorch Microphone` before I update to newer version.

I think newer pipewire broken something.

Device info:
ArchLinux
pipewire 0.3.44
wireplumber 0.4.7
noisetorch 0.11.4 (installed and build with AUR)

**Comment by lawl** [comment]
> I think newer pipewire broken something.

Is there a reason you're filing an issue here instead of with pipewire then?

**Comment by OctopusET** [comment]
@lawl I thought this error only effect on NoiseTorch, So I thought it is more related to this repo than pipewire.
But yes, you are right, sorry I made mistake. It would be better reporting on pipewire repo. I'm closing this issue now.

BTW, anyone who is related this issue. Check out this https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2071

**Comment by rombert** [comment]
FWIW the upstream pipewire issue was closed with not apparent fix - https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2071 .

**Comment by lawl** [comment]
so much for the stable API they claimed they have...

**Comment by codevski** [comment]
getting this as well (filter-chain-11) :disappointed:

**Comment by AngelSherry** [comment]
I also get the same issue, Although NoiseTorch has been loaded (filter-chain-11), there isn't any noise reductions in fact.

**Comment by lawl** [comment]
Just went in the pipewire repo to figure out how to make it work again, and it seems PipeWire has fixed it: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2086

with [this](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/136989eaa64c25b4172274bd181fd48d552a6137) commit a week ago.

Checking the reslease notes for [0.3.46](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/0df9d037292f7b815be59d265c47790ee7a495c9) suggests to me that this regression has been fixed, as it mentions the issue above:

    `- Improve argument parsing and node.description. (#2086)`

I'll leave this issue open for a moment until someone confirms, or fedora pushes 0.3.46 to my VM so i can confirm myself.

**Comment by rombert** [comment]
That would be great news. I'll try it out as soon as pipewire 0.3.46 lands in Tumbleweed.

**Comment by ruifm** [comment]
Fixed on arch

**Comment by lawl** [comment]
ok, closing then (assuming arch rolled out 0.3.46 already)
