### ISSUE TITLE
Doesn't launch noisetorch

### ISSUE THREAD

**Issue by Renterl** [lawl/NoiseTorch#219]
Hello,
I click it to launch noisetorch, but nothing happens. I use Artix with s6.
Thank you.
noisetorch -log
2022/02/09 20:53:29 Application starting. Version: 0.11.4 (archlinux)
2022/02/09 20:53:29 CAP_SYS_RESOURCE: true
2022/02/09 20:53:29 Checking if config needs to be initialized
2022/02/09 20:53:29 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/renteri/.config'
2022/02/09 20:53:29 Wrote temp librnnoise to: /tmp/librnnoise-847977922.so
2022/02/09 20:53:29 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/renteri/.config'
2022/02/09 20:53:29 Audioserver package name: pulseaudio
2022/02/09 20:53:29 Audioserver package version: 15.0
2022/02/09 20:53:29 Detected PulseAudio
2022/02/09 20:53:29 couldn't parse server version, regexp didn't match version: 15.0
2022/02/09 20:53:29 Getting caps for: /usr/bin/noisetorch
2022/02/09 20:53:29 Deleted temp librnnoise: /tmp/librnnoise-847977922.so
panic: cannot connect to :0: dial unix /tmp/.X11-unix/X0: connect: no such file or directory

goroutine 1 [running]:
github.com/aarzilli/nucular/clipboard.Start()
        github.com/aarzilli/nucular@v0.0.0-20200615134801-81910c722bba/clipboard/clipboard_x11.go:28 +0x354
github.com/aarzilli/nucular.NewMasterWindowSize(0xc000180000, {0x55a60d984009, 0xa}, {0x1, 0x0}, 0x0)
        github.com/aarzilli/nucular@v0.0.0-20200615134801-81910c722bba/shiny.go:79 +0x114
main.main()
        noisetorch/main.go:81 +0x451

P. S. I'm new to linux.

**Comment by lawl** [comment]
Dont use arch linux
