### ISSUE TITLE
Any chance for a systray & minimize to systray?

### ISSUE THREAD

**Issue by duckunix** [lawl/NoiseTorch#22]
Would make this very handy to use.  I use i3, and there is no 'minimize' button on my windows. :)

**Comment by lawl** [comment]
Probably not for two reasons. DE's try to get rid of them, and the GUI toolkit i use doesn't suppport it, and the onöy solutions i saw a while ago are CGO which i'd like to avoid.

**Comment by lawl** [comment]
Oh, btw, check out Cadmus: https://github.com/josh-richardson/cadmus which may fit you better if you want it in your systray.

**Comment by vn-ki** [comment]
Have you seen this: https://github.com/getlantern/systray ?

**Comment by lawl** [comment]
@vn-ki that uses CGO, which i don't want in this project.

**Comment by vn-ki** [comment]
May I know, why you don't want cgo? I dont think the overhead from c call would affect the application in any way.

**Comment by lawl** [comment]
Static linked binaries.
