### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by memtech3** [lawl/NoiseTorch#225]
Edit: It looks like there is a command line, I just can't find documentation for it. May be a me problem. Can someone sanity check me? It's too early in the morning (1:15 AM)

A command line interface would open NoiseTorch up to all sorts of embedded applications (car computers a la OpenDash\OpenDsh). Feature's I would love to see in a CLI:

- Start with existing configuration
- Start with config file
- Restart
- Stop

**Comment by lawl** [comment]
yes there is a CLI, documentation is basically `noisetorch -h`, it's not well documented because it's frankly only half-heartedly supported as i personally don't use it.

**Comment by memtech3** [comment]
I think this is a valuable feature and should be further worked on and documented, if not by you by the community. This vastly expands the usability of this solution from a desktop application to a tool that could be used in many projects

**Comment by lawl** [comment]
I would love for someone to step up and take over the CLI. It was originally contributed by a user, and I have made sure to keep it working because I know it provides value to some people.

But as I said, I personally don't use it and the lack of dogfooding shows.

**Comment by memtech3** [comment]
Can you reopen this and tag it with Help Wanted?

**Comment by lawl** [comment]
I don't think telling people what to work on leads to high quality contributions. I prefer waiting until someone is annoyed enough by the CLI that they do it out of self-initiative.
