### ISSUE TITLE
PipeWire no Load NoiseTorch button if launched at startup

### ISSUE THREAD

**Issue by BorealBlizzard** [lawl/NoiseTorch#226]
I'm using EndeavourOS and when I have noisetorch launch at startup it doesn't show the "Load NoiseTorch" button or any microphones listed. It also didn't work when I tried to make a little script that initializes it. 

If any extra info is needed ill add it.

**Comment by lawl** [comment]
how do you launch it at startup, what script?

**Comment by lawl** [comment]
unresponse
