### ISSUE TITLE
High CPU utilization

### ISSUE THREAD

**Issue by mierzejk** [lawl/NoiseTorch#227]
Foremost, many thanks for such an impressive noise reducing app! At the same time I have noticed that enabling (loading) NoiseTorch thrusts pulseaudio process load to constant one thread / core 100% CPU utilization, no matter what, until unloaded. I wonder whether it is _by design_, or a conceivable glitch that could be patched up?

**Comment by lawl** [comment]
100% is a lot. There is indeed some expectation that NoiseTorch will siphon off some CPU use when using pulseaudio. But unless you have a weak CPU it shouldn't be 100%.

Can you try to figure out what the process is doing with e.g. [`perf top`](https://man7.org/linux/man-pages/man1/perf-top.1.html)?

**Comment by mierzejk** [comment]
I am pretty sure the _resource hungry_ process was pulseaudio, but I will double-check next week, as I am out of office the entire week. The processor is Intel Core i7-4800MQ 2.70GH 4 physical cores + Hyper Threading / 8 concurrent threads. But in my view the processor details do not really matter, as pulseaudio is simply exhausting one thread, regardless of the clock speed.

**Comment by lawl** [comment]
>  am pretty sure the resource hungry process was pulseaudio

`perf top`, not top. I want to know what pulseaudio is doing.

**Comment by lawl** [comment]
inactive

**Comment by lawl** [comment]
Sorry to hear that, hope your recovery is going well.

Yeah these two logs look about normal to me. If it happens again, it'd be great if you manage to catch it with `perf top` and report here.
