### ISSUE TITLE
Default volume

### ISSUE THREAD

**Issue by advilm** [lawl/NoiseTorch#229]
I usually have my microphone volume set to 30% because 100% is way too loud. However, when I enable noise torch it sets my microphone's volume to 100%. Is there a way I could disable this? I'm fine with compiling my own version to disable this. I would appreciate it if someone pointed me towards where the code that sets this is.

**Comment by lawl** [comment]
The code shouldn't and to my knowledge doesn't set this. So i'm not quite sure what's happening, can you provide more information?

**Comment by advilm** [comment]
After some testing, I figured out that it is Discord controlling the volume, not NoiseTorch. A bit strange that NoiseTorch is triggering Discord to set the volume since Discord normally doesn't set it. I managed to fix this by adjusting microphone volume in Discord settings.
