### ISSUE TITLE
open pulse/pid: no such file or directory

### ISSUE THREAD

**Issue by gerroon** [lawl/NoiseTorch#23]
When I try to load NT this is what I get. It does not look like it is loading the module.

Debian Testing x64. 

2020/07/18 19:38:50 Querying pulse rlimit
2020/07/18 19:38:50 open pulse/pid: no such file or directory

**Comment by lawl** [comment]
(i'm on mobile)

Does it succeed in connecting to pulseaudio, i assume ypu see a device list to select one to denoise?

What does

    echo $XDG_RUNTIME_DIR

say?

**Comment by lawl** [comment]
Can you try with the newest version and set `PULSE_RUNTIME_DIR` and `PULSE_COOKIE`?

**Comment by gerroon** [comment]
Thanks for the fix
