### ISSUE TITLE
Are there command line controls and persistent settings for noise torch?

### ISSUE THREAD

**Issue by syedalamabbas** [lawl/NoiseTorch#233]
Hi lawl,
              Is there a way to control things like the noise threshold or loading/unloading via the command line? And I noticed that when I restart the noisetorch unload, and then I have to go the GUI and reload it again.  Not sure if it has something to do with pulse audio or noise torch, as even my defaults source/sink change after restart. Is there a way to make these settings persistent?

Thanks.

**Comment by lawl** [comment]
> Is there a way to control things like the noise threshold or loading/unloading via the command line? 

`noisetorch --help`

> And I noticed that when I restart the noisetorch unload, and then I have to go the GUI and reload it again.

Sorry, I don't follow. Can you elaborate the problem again?

**Comment by syedalamabbas** [comment]
Ok. Thanks. 
When I restart my machine. The noisetorch is unloaded. Then I have to click on the button to load noise torch again...

**Comment by lawl** [comment]
https://github.com/lawl/NoiseTorch/wiki/Start-automatically-with-Systemd

**Comment by syedalamabbas** [comment]
Fantastic! This answers everything!

Closing this out...
