### ISSUE TITLE
Drop internal microphone when NoiseTorch is not in use

### ISSUE THREAD

**Issue by ZagButNoZig** [lawl/NoiseTorch#234]
When NoiseTorch is running as a service, gnome constantly shows me that my microphone is in use in the top right corner.
Which it is, since NoiseTorch is grabbing that input. 

Could we in theory "drop" the internal microphone, as in not use that source when the NoiseTorch Microphone is not used and only "grab" the internal microphone when NoiseTorch is used.

By internal microphone I mean the microphone NoiseTorch is filtering. 

I'd be happy to contribute but I have not a lot of experience with pipewire and NoiseTorch, so I would need some pointers.

**Comment by lawl** [comment]
No, there is a big fat warning about this being an issue [here](https://github.com/lawl/NoiseTorch/wiki/Start-automatically-with-Systemd). So if you run noisetorch as a service, you should know this.

**Comment by lawl** [comment]
(just to not be misunderstood, there's nothing i can do about this, it's a pulseaudio problem, not a noisetorch problem)

**Comment by ZagButNoZig** [comment]
Thanks for the quick response! Anything we can do in pipewire?

**Comment by lawl** [comment]
Sorry, didn't see the pipewire thing. But the answer is no, unfortunately. This is outside our control.
