### ISSUE TITLE
Would it be possible to implement NoiseTorch as an EasyEffects Plugin?

### ISSUE THREAD

**Issue by JacobTravers** [lawl/NoiseTorch#237]
I already use [easyeffects](https://github.com/wwmm/easyeffects) interface to add parametric eq presets to my headphones using [autoeq](https://github.com/jaakkopasanen/AutoEq), would it be possible to make this a plugin for easyeffects? That way I don't need to install and configure a whole separate interface. It would also be nice since you can set easyeffects to automatically apply presets based on which input device is being used. That way you could have settings for multiple microphones etc.

I know there is already an rnnoise plugin so I wonder if it would just be a matter of adapting/updating that one...

Either way thanks for this tool it's really made talking to my friends and coworkers much nicer with my clicky keyboard, fans, pets, etc in the background.

**Comment by lawl** [comment]
I that's something you're interested in working on, then I'm sure that could be done.

I have also used easyeffects for system wide EQ before and I think both tools serve different purposes, so I'm not interested in working on this, but I'm not stopping anyone from doing so. It's open source after all.

**Comment by JacobTravers** [comment]
no worries thanks for the quick response!
