### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by Maciejka1** [lawl/NoiseTorch#241]
Add a autostart function which would automatically activate noisetorch on startup to save a few clicks
![Screenshot_20220421_221519](https://user-images.githubusercontent.com/82782118/164545240-b1c759de-00d9-4955-add5-b34cbff84607.png)
.

**Comment by lawl** [comment]
@YourSandwich is right.

See: https://github.com/lawl/NoiseTorch/wiki/Start-automatically-with-Systemd

Especially see the warning at the top, that's why this is not a simple option in the gui (yet).

**Comment by A7mmud** [comment]
While it is not an issue on pipewire. I think it is time to add this feature. Ubuntu LTS and fedora switched to pipewire already. Many distros are switching too.

**Comment by lawl** [comment]
There are some more thoughts here: https://github.com/lawl/NoiseTorch/issues/201

I'd like to keep PipeWire and Pulse mostly the same for those reasons. 22.04 will still ship pulse. It's an LTS release, however, it's unlikely that i will support pulse for 5 years.

Still a bit too early to drop Pulse right now, I think.

**Comment by yanxun3737** [comment]
> @YourSandwich is right.
> 
> See: https://github.com/lawl/NoiseTorch/wiki/Start-automatically-with-Systemd
> 
> Especially see the warning at the top, that's why this is not a simple option in the gui (yet).
![image](https://user-images.githubusercontent.com/67913358/173172845-c0a57ec4-e294-490f-adfc-ab757f2f6d8f.png)
Link seems dead

**Comment by AXDOOMER** [comment]
Use this link instead: https://github.com/noisetorch/NoiseTorch/wiki/Start-automatically-with-Systemd

**Comment by yanxun3737** [comment]
> Use this link instead: https://github.com/noisetorch/NoiseTorch/wiki/Start-automatically-with-Systemd

Thank you <3
