### ISSUE TITLE
[Feature Request] Select Multiple Input Devices

### ISSUE THREAD

**Issue by YourSandwich** [lawl/NoiseTorch#243]
Hi lawl,
thank you for your awesome programm, its a live changer.

I would like to reqest a posibility to select multiple Input sources.

With this i could for example route the DIscord/Element chat audio to my Chat Sink and user noisetorch on it while simulteniously using it on my microphone :D

Love your work!

**Comment by lawl** [comment]
Not quite sure what you want to do exactly, so i'm going off the title.

The problem with that is that I haven't found a good way yet to make the UI not (more) confusing, especially with e.g. the consistency checks noisetorch does. Pulseaudio sometimes, uh... drops the ball and only half our filter chain is still alive.

As an example: NoiseTorch catches that and displays that the pulseaudio state is inconsistent with that's configured. If you have mutliple sources now and you unplug a microphone, what should NoiseTorch display?

Now, if you want to do some advanced routing, I believe using noisetorch on the CLI lets you load multiple instances. While not officially supported, maybe scripting your more advanced setup would make sense anyways?

**Comment by YourSandwich** [comment]
Thank you your right i could accomplish my goal with the cli :O Im already loading noisetorch with systemd so i could just add a second instance for my Chat Sink.

My plan is to apply noisetorch on an Virtual Sink where the output of Single/Multiple VoIP is accumulated(my viewers wont hear the keyboard of my friends that dont use noisetorch) like this ->  
![image](https://user-images.githubusercontent.com/20018243/164711529-bd166160-4807-4a90-a322-e37b882eea0e.png)
Thankfully Chat Audio/Sink is detected as Monitor Source.

Your right this story is tricky if you want make it user readible.
Thank you for your quick help <3
