### ISSUE TITLE
How to make NoiseTorch Microphone show up as sinks on patchbay?

### ISSUE THREAD

**Issue by limsherwin** [lawl/NoiseTorch#244]
Hello,

I am using Cadence, Catia, and Calf Studio Gar for JACK Audio.

Is there a way to have NoiseTorch Microphone show up as sinks so that I can route it through Calf Studio?

Not sure if it help to show my use case, but every time I start Jack, I run the following script:

`pacmd set-default-sink jack_out `
`pacmd set-default-source jack_in`
`alsa_in -j UnitekMic -d hw:CARD=Device -r 48000 -c 1 >/dev/null &`
`pactl load-module module-jack-source client_name=MorseOnly_IN channels=2 connect=0`
`pactl load-module module-jack-source client_name=MorseVoice_IN channels=2 connect=0`
`pactl load-module module-jack-source client_name=Zoom_IN channels=2 connect=0`

Thank you.

Sherwin

**Comment by lawl** [comment]
I dont understand what you're trying to do, and I have never used Jack, nor do I know what Calf Studio is.
I'm also not sure how the Microphone would be a sink, as in pulse/pipewire that would normally be a source?

**Comment by limsherwin** [comment]
Yes, microphone is a source. 

As shown in the attached screen capture of the graph, NoiseTorch Microphone is not visible. I would like to capture the audio from NoiseTorch Microphone as the input of Voice In for the Calf Studio (I guess it's basically a mixer?)

![Screenshot_20220423_181628~2](https://user-images.githubusercontent.com/941004/164890579-60d6abe2-6824-4d11-bb16-cf348a8ab5c7.png)

**Comment by lawl** [comment]
I've used Catia on Pipewire and NoiseTorch showed up just fine there. So right now I'm assuming that would be some JACK thing that I can't help you with.
