### ISSUE TITLE
Programm completly doesn't wanna work. Say about Access Denied with sudo rights.

### ISSUE THREAD

**Issue by W1nKille3r** [lawl/NoiseTorch#246]
While compiling ended with error:
```
~/NoiseTorch$ make
make -C c/ladspa
make[1]: enter to catalogue «/home/XXX/NoiseTorch/c/ladspa»
cc -Wall -Werror -O2 -c -fPIC ../ringbuf.c ../rnnoise/*.c module.c 
cc -o rnnoise_ladspa.so *.o -shared -Wl,--version-script=export.txt -lm
make[1]: exit from catalogue «/home/XXX/NoiseTorch/c/ladspa»
mkdir -p bin/
go generate
go build -ldflags '-X main.version=0.11.5' -o bin/noisetorch
build noisetorch: cannot load crypto/ed25519: cannot find module providing package crypto/ed25519
make: *** [Makefile:8: dev] Error 1
```
After using sudo
```
make: go: That file or catalogue doesn't exist
make: *** [Makefile:7: dev] Error 127
```

Trying to install on Debian. System: Q4OS Plasma

Dropped .local to home folder. After i try to launch app they say that is impossible. But i give them setcap command.

Without sudo rights Konsole type:
`Couldn't create pulseaudio client: PulseAudio error: commandAuth -> Access denied`
With sudo
Same (first Konsole start was with some info but in general saying about failing create pulseaudio)

**Comment by W1nKille3r** [comment]
After cleaning pulse audio by that guide: [https://forums.linuxmint.com/viewtopic.php?t=295346](url)
That app finaly start working. I guess that was caused because i installed near Mumble and they screw up audio settings.
Anyways that start working.

**Sorry by my stupidness. Im new in Linux (using like 3 days) and gain expirience from that.**

**Comment by lawl** [comment]
glad u got it working
