### ISSUE TITLE
Does not work when selected as input

### ISSUE THREAD

**Issue by rhyst** [lawl/NoiseTorch#25]
I'm on Ubuntu 20.04. It seems to do the initial load fine and I can see in pavucontrol that the NoiseTorch input is working and picking up sound. Then I have three issues:

- If I select the NoiseTorch as the input then it stops working (completely silent even in pavucontrol)
- If I try to reload then it gets stuck on working
- If I try to unload then it gets stuck on working

The reloading/unloading also disconnects my headphones and makes any running application unable to produce sound until restarted.

Log:
[noisetorch.log](https://github.com/lawl/NoiseTorch/files/4942413/noisetorch.log)

Thanks :)

**Comment by lawl** [comment]
From looking at this the getting stuck thing while loading/unloading is a separate issue and the same issue I fixed for loading [here](https://github.com/lawl/NoiseTorch/issues/11). I deliberately didn't implement it yet for unloading, as I hoped I could get away with it so we don't need to elevate to root again and ask for the user password.

I've filed a separate bug for this at #27 to fix this once I've got some more severe issues out of the way. As unloading not working, while certainly annoying has a relatively simple work-around. Restart NoiseTorch and other applications that don't handle losing the connection to PA gracefully, the modules will already be unloaded because Pulse got `SIGKILL`d and restarted.

Ok, so then let's focus on your first issue here. 

> If I select the NoiseTorch as the input then it stops working (completely silent even in pavucontrol)

I will need PulseAudio logs for this. Can you trigger this and then run 

    journalctl -n100 --no-pager -b /usr/bin/pulseaudio

and throw it in a gist, so we can see if PulseAudio gives us a hint here. NoiseTorch isn't really involved anymore once the modules are loaded into PA.

**Comment by rhyst** [comment]
I did this first thing after booting to try and make sure it wasn't anything else. Weirdly it allowed me to select NoiseTorch once and it seemed to work quite well (I was using the audio checking in Discord). But I selected the normal mic and then NoiseTorch again and it stopped working. The pulseaudio logs are just full of this:

```
Jul 19 10:12:01 laptop pulseaudio[37184]: AppArmor profile could not be retrieved.
```

Repeated hundreds of times.

**Comment by lawl** [comment]
> AppArmor profile could not be retrieved.

That's a from a buggy patch canonical applies to pulseaudio, but I haven't seen it cause any issues yet (well, the spamming this part of the patch).

Could you go through your log again and maybe `| grep -v " AppArmor profile could not be retrieved"` ?

**Comment by rhyst** [comment]
Sure! There is surprisingly little left:

```
Jul 19 10:27:35 laptop pulseaudio[3049]: Configured latency of 1.00 ms is smaller than minimum latency, using minimum instead
Jul 19 10:27:35 laptop pulseaudio[3049]: Cannot set requested sink latency of 2.25 ms, adjusting to 2.50 ms
Jul 19 10:27:35 laptop pulseaudio[3049]: Cannot set requested source latency of 2.25 ms, adjusting to 2.50 ms
Jul 19 10:27:35 laptop pulseaudio[3049]: Too many underruns, increasing latency to 12.00 ms
Jul 19 10:27:35 laptop pulseaudio[3049]: No remapping configured, proceeding nonetheless!
Jul 19 10:27:45 laptop pulseaudio[3049]: Too many underruns, increasing latency to 17.00 ms
Jul 19 10:28:32 laptop pulseaudio[3049]: ALSA woke us up to write new data to the device, but there was actually nothing to write.
Jul 19 10:28:32 laptop pulseaudio[3049]: Most likely this is a bug in the ALSA driver 'snd_usb_audio'. Please report this issue to the ALSA developers.
Jul 19 10:28:32 laptop pulseaudio[3049]: We were woken up with POLLOUT set -- however a subsequent snd_pcm_avail() returned 0 or another value < min_avail.
Jul 19 10:29:46 laptop pulseaudio[3049]: Configured latency of 1.00 ms is smaller than minimum latency, using minimum instead
Jul 19 10:29:46 laptop pulseaudio[3049]: Cannot set requested source latency of 2.25 ms, adjusting to 2.50 ms
Jul 19 10:30:01 laptop pulseaudio[3049]: Configured latency of 1.00 ms is smaller than minimum latency, using minimum instead
Jul 19 10:30:01 laptop pulseaudio[3049]: Cannot set requested source latency of 2.25 ms, adjusting to 2.50 ms
Jul 19 10:30:04 laptop pulseaudio[3049]: Configured latency of 1.00 ms is smaller than minimum latency, using minimum instead
Jul 19 10:30:04 laptop pulseaudio[3049]: Cannot set requested source latency of 2.25 ms, adjusting to 2.50 ms
Jul 19 10:33:46 laptop pulseaudio[3049]: Configured latency of 1.00 ms is smaller than minimum latency, using minimum instead
Jul 19 10:33:46 laptop pulseaudio[3049]: Assertion 'PA_SINK_IS_LINKED(s->state)' failed at pulsecore/sink.c:914, function pa_sink_suspend(). Aborting.
Jul 19 10:33:47 laptop pulseaudio[7432]: Stale PID file, overwriting.
```

**Comment by lawl** [comment]
Assertion 'PA_SINK_IS_LINKED(s->state)' failed at pulsecore/sink.c:914, function pa_sink_suspend(). Aborting.

That does not look normal to me. I'm super swamped right now, I can try looking into it more later, but if you want to do some digging of your own in the meantime, that's where I'd start.

**Comment by lawl** [comment]
Hmm, yeah, I'd make sure that this log line is triggered by using NoiseTorch, and then you will have to file a bug with your distribution or at PulseAudio. There's not much I can do for you here, sorry.

**Comment by rhyst** [comment]
I've been playing around with it a bit more. I don't think that error is relevant because it happens a fair amount even when NoiseTorch is working. 

I have found that Noisetorch works perfectly (loading/unloading/reloading) as long as I do not have it selected as the input device in the Ubuntu settings (I do not know what that means in PulseAudio). If I just set the input to NoiseTorch in individual programs then it's great. As soon as I select it as the Input Device in the Ubuntu settings then the NoiseTorch input is completely silent, and unloading/reloading stop working. If I unselect it then the NoiseTorch input starts working again and unloading/reloading work as well.

I guess this is quite low priority now and not even sure if this is anything to do with NoiseTorch :smile: but I'd be keen to get it working. I'm not sure where to go with it from here though so let me know if there are any logs I can provide. 

Thanks for you help so far.

**Comment by lawl** [comment]
> I have found that Noisetorch works perfectly (loading/unloading/reloading) as long as I do not have it selected as the input device in the Ubuntu settings (I do not know what that means in PulseAudio). If I just set the input to NoiseTorch in individual programs then it's great.

Ahh, yeah, that makes sense. Yeah, setting it as default causes issues, which is why NoiseTorch doesn't set it as the default input by itself. I haven't found a solution for this yet.

This should definitely be mention in some kind of knowledge base though.

**Comment by lawl** [comment]
I've created a [Troubleshooting](https://github.com/lawl/NoiseTorch/wiki/Troubleshooting) page on the wiki that's linked in the readme and talks about this.

So I'm closing this for now.
