### ISSUE TITLE
Add option to disable self update feature

### ISSUE THREAD

**Issue by ModProg** [lawl/NoiseTorch#250]
This would be great for distribution via package manager, where the updating happens outside the application and the self-update probably doesn't even work correctly.

Maybe this could be inside a system configuration, but not sure what the best way would be.

**Comment by lawl** [comment]
https://github.com/lawl/NoiseTorch/blob/master/Makefile#L1

just don't set `UPDATE_URL` and thats exactly what happens. As far as I know basically all packages do this, except noisetorch-bin from AUR. The solution there is to stay far, FAR away from AUR.

**Comment by ModProg** [comment]
Sorry, I hadn't found the other issue yet about the AUR package. Therefore, I didn't know the reasoning you had against enabling this without building from source.

While I would personally like a way to do this and still being able to use your build artifacts from GitHub, I can understand why you chose not to support this.
