### ISSUE TITLE
GUI threshold display does not update after setting via CLI

### ISSUE THREAD

**Issue by dmaahs2017** [lawl/NoiseTorch#251]
# Expected Behavior (intuitive)
When NoiseTorch settings are updated via the CLI, the NoiseTorch voice activation slider should be adjusted to match the new settings

# Actual Behavior
After setting the NoiseTorch input suppression Via CLI, the voice activation slider remains unchanged, and the user is not informed that the Threshold on the GUI is not the actual active threshold.

This does not update even after restarting the GUI app

# Nice to have
A CLI sub-command or flag to output the current active settings.

# Cause (Maybe)
This seems to be caused by the CLI not updating the `Threshold` in the config file. 

## Fix
When using the command `noisetorch -i <input_source> -t <threshold>` update the config to match the threshold. This would at least make it consitent after restarting the GUI application it seems.

**Comment by lawl** [comment]
The CLI is entirely independent of the GUI, and doesn't touch the config file. This is/was by design, it may have been the wrong call, but changing it now might break peoples expectations for those that have already running it with scripts. I'm not sure thats a good idea.
