### ISSUE TITLE
Doesn't follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by farmerbobathan** [lawl/NoiseTorch#26]
Currently NoiseTorch stores its config file in ~/.config/noisetorch, thus cluttering the user's home directory with yet another arbitrarily chosen hidden directory.  NoiseTorch should instead support the [Freedesktop.org XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and place its config file in XDG_CONFIG_HOME/noisetorch and revert to ~/.config/noisetorch when XDG_CONFIG_HOME isn't set.

**Comment by lawl** [comment]
https://github.com/lawl/pulseaudio/blob/master/client.go#L26 should use XDG_RUNTIME_DIR if available, this should also be fixed.

**Comment by lawl** [comment]
Not respecting XDG breaks some users here: https://github.com/lawl/NoiseTorch/issues/21#issuecomment-660589751

**Comment by lawl** [comment]
Here's a new build: 
[noisetorch.zip](https://github.com/lawl/NoiseTorch/files/4943532/noisetorch.zip)
 that should respect XDG, unpack it, chmod +x it, run it. If you prefer to build from source, please build this branch: https://github.com/lawl/NoiseTorch/tree/repect-xdg

If possible I'd like to get a confirmation from @farmerbobathan and possibly @cellofellow that this resolves the "failed to connect to pulseaudio" issue (and other issues) and will then merge this and push it out officially.

**Comment by lawl** [comment]
[NoiseTorch 0.5.1-beta](https://github.com/lawl/NoiseTorch/releases/tag/0.5.1-beta) is now released and addresses this.

The next time you start NoiseTorch it should ask you if you want to update. Please note that you need to restart NoiseTorch after installing the update via the built-in updater.

If this does not address your issues, please reopen.

**Comment by RatanRSur** [comment]
I was seeing the bug in #21 and followed the conversation here but I'm still seeing it even though I have the release you mentioned

```
 130 ~/.config/pulse noisetorch
2020/07/19 21:12:11 Application starting. Version: 0.5.1-beta
2020/07/19 21:12:11 Checking if config needs to be initialized
2020/07/19 21:12:11 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/ratan/.config'
2020/07/19 21:12:11 Wrote temp librnnoise to: /tmp/librnnoise-666164609.so
2020/07/19 21:12:11 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/ratan/.config'
2020/07/19 21:12:11 Resolved $XDG_RUNTIME_DIR to '/run/user/1000'
2020/07/19 21:12:11 Couldn't resolve $XDG_CONFIG_HOME falling back to '/home/ratan/.config'
2020/07/19 21:12:11 Couldn't create pulseaudio client: open /home/ratan/.config/pulse/cookie: no such file or directory
```

**Comment by lawl** [comment]
@RatanRSur possibly related to #31 do you have `$PULSE_COOKIE` set in your environment?

**Comment by RatanRSur** [comment]
It's not. I have a file `~/.pulse_cookie`, but when I set the envvar to that, I still get the same error message with the same `.config/pulse/cookie` path.

**Comment by lawl** [comment]
@RatanRSur can you please create a new issue for this?
