### ISSUE TITLE
Doesn't launch

### ISSUE THREAD

**Issue by arnauldb** [lawl/NoiseTorch#28]
Hello,
I installed it, but it doesn't launch. I have an icon in my application launcher, I click it to launch NoiseTorch, but nothing happens. I use Linux Mint 18.3 Sylvia.
Thank you.

**Comment by lawl** [comment]
Can you please attach your `/tmp/noisetorch.log` file?

**Comment by arnauldb** [comment]
Here is my log: [link](https://arnauld.org/zerobin/?00322c21744933d2#5y3k4YbLD7UXT2qSMV3AM9YebZLUzJw8QFUbff42CbZT)

**Comment by lawl** [comment]
I just release [0.5.1-beta](https://github.com/lawl/NoiseTorch/releases/tag/0.5.1-beta) 20 minutes ago, which may fix your issue, can you update and check? If it doesn't fix your issue, please attach the log from 0.5.1 too, as it includes more logging for this issue.

When you start NoiseTorch it should ask you if you want to update, you will have to restart NoiseTorch after it sais "Update installed!" for it to apply.

**Comment by lawl** [comment]
I just realized it doesn't start for you, so you cant use the built in updater. Please just follow the install instructions again, with 0.5.1.

**Comment by arnauldb** [comment]
Here is the log after manual install of 0.5.1-beta: [link](https://arnauld.org/zerobin/?78fff71b589e6ddc#1eyJfPMomCKEhgcnULDMsDbcgiAe9FhDe7rQBuKNpYA)

**Comment by lawl** [comment]
I see

    
2020/07/19 14:52:52 Couldn't create pulseaudio client: pulseAudio server supports version 30 but minimum required is 32

Are you running an LTS distro? It seems your pulseaudio server is too old and I don't support it.

The bad news is that I also don't plan to support it, so your only option is to upgrade.

**Comment by arnauldb** [comment]
Ok, I will upgrade my distro to a more recent one. Thank you for your work.
