### ISSUE TITLE
In OBS noistorch makes it sound like a robot

### ISSUE THREAD

**Issue by yurgburg** [lawl/NoiseTorch#34]
I am usually not able to hear keyboard in like discord but obs you can hear and I also sound like a robot enveloped by static don't have any filters on in obs either

**Comment by lawl** [comment]
So NoiseTorch works fine in Discord, but not OBS?

**Comment by yurgburg** [comment]
Yes I actually found out its not a noistorch issue just now because I tested my microphone without the filter on at first it wasn't a robot but then I left it off and the robot came back so I am going to close the issue
