### ISSUE TITLE
Please clarify if the UI can be closed without unloading the plugin

### ISSUE THREAD

**Issue by cipriancraciun** [lawl/NoiseTorch#38]
I've observed that I can just kill the `noisetorch` binary / window, and have the plugin still active.

**This is excelent, and I like this!**

However this is just an observed behaviour, and not talked about in the documentation.

Please clarify if this is by design, or just a side-effect.

(In case it's just a side-effect, please consider the option to let the plugin still active after closing the UI.)

**Comment by lawl** [comment]
That's just how it happens to work, and i'm not going to write extra code to unload it when the window is closed.

You are right, this should be documented.

**Comment by lawl** [comment]
Fixed with 5ce761a62b3e1314615eeb1ac5192d758021a43e
