### ISSUE TITLE
Default input and output devices and microphone loopback

### ISSUE THREAD

**Issue by dumbPy** [lawl/NoiseTorch#40]
### Background
On loading NoiseTorch, it doesn't outright work for me on Ubuntu 18.04
Going through Troubleshooting page, I see my default input is NoiseTorch and no bars in Null Output and LADSPA Plugin...
Changing Default microphone to Built-in Audion Analog Stereo seems to make NoiseTorch Microphone bars work and LADSPA bars work.

### Problem after Troubleshooting
But I cannot hear anything on my headphones anymore. (output defaults to LADSPA)
Changing Output to my Bluetooth Headphones makes microphone loop back to my headphones (my default noisy microphone, not NoiseTorch's)

I am probably missing something but I think it would be great if you can explain the audio routing somewhere (I understand you want it to be plug and play but still) so that what device should be selected where would be more clear.

My apologies if I am missing something too obvious 

[noisetorch.log](https://github.com/lawl/NoiseTorch/files/4975361/noisetorch.log)

**Comment by dumbPy** [comment]
As I said, It's something very obvious that I am missing.

Set default microphone to the noisy one
Set default output to LADSPA...
for each application set NoiseTorch as the input
for each application in pavucontrol's playback tab, set the required output device manually. (This step was not written in troubleshooting)

**Comment by lawl** [comment]
That's super weird, because NoiseTorch should *not* touch your default input/output device.

**Comment by dumbPy** [comment]
I have been playing around with pulseaudio trying to get HFP profile working for my bluetooth headphones, following [this](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Bluetooth/)

Most probably I might have changed somethings in default.pa or system.pa that might be regressing here.
Unless someone reports something similar, you may neglect this. I will be doing a clean install soon so will let you know if it arises again.
