### ISSUE TITLE
High CPU usage when NoiseTorch is loaded

### ISSUE THREAD

**Issue by vn-ki** [lawl/NoiseTorch#41]
Pulseaudio takes 50% cpu when Noise Torch is loaded. Unloading it reduces the CPU usage.

**Comment by lawl** [comment]
Yes, it runs on CPU, so it consumes CPU.

**Comment by vn-ki** [comment]
Is there a possibility to activate it only if some program is recording?

It seems like a waste of resource when the module keeps on working when no program is using the microphone.

**Comment by lawl** [comment]
Unfortunately not, the work-around currently required to make this work with pulseaudio at all means that it's always running even if no application is capturing from it.

This should be resolved if [this](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/120) is implemented in PulseAudio. Nothing we can do on our side, unfortunately, for now I suggest to unload NoiseTorch if you're not using it.
