### ISSUE TITLE
[Feature Request] Noise Suppression on Output

### ISSUE THREAD

**Issue by Mushoz** [lawl/NoiseTorch#44]
It would be awesome if the application could be changed, so that it is also possible to do noise suppression on sound output. For example, if I am in a call with a person that does not have noise suppression himself, it would be awesome if I could use this application to set my sound output as Noisetorch's input, which will then create a virtual Noisetorch Output device. Selecting this device should then allow me to hear this other person with the noise filtered out.

The actual noise suppression functionality can remain identical as far as I know, only the input and output device from Noisetorch's point of view would need to be wired up differently.

**Comment by SleepingFox88** [comment]
Taking this one step further, It would be best if NoiseTorch could only do noise suppression on selected applications. This way, you could specify NoiseTorch to filter sounds from a VOIP application (say discord), while still receiving unfiltered sound from other applications running at the same time such as games, videos, etc.

**Comment by Mushoz** [comment]
@SleepingFox88 this should be possible. Basically, it would work like this:

1) You select your physical output device
2) It creates a virtual Noisetorch Output device
3) In any application that you want noise to have noise suppression on (Such as Discord) you will select the virtual Noisetorch Output device
4) All sounds being outputted to that virtual device will be noise suppressed and sent to the physical output device selected in step 1).

It works identical to how it works now for noise suppression on input, but simply in reverse for outputs.

**Comment by lawl** [comment]
This is implemented with [0.9.0](https://github.com/lawl/NoiseTorch/releases/tag/0.9.0).
