### ISSUE TITLE
Couldn't create pulseaudio client

### ISSUE THREAD

**Issue by lbischof** [lawl/NoiseTorch#46]
I sometimes receive the following error when starting Noisetorch:
```
2020/07/30 18:55:01 Couldn't create pulseaudio client: dial unix /run/user/1000/pulse/native: connect: no such file or directory
```
When I check the native file does not exist, but the pulse directory does.

It seems to work directly after running `pactl list short sinks`.

Happy to give more information.

**Comment by lawl** [comment]
The pulse directory exists, but is not emtpy? Is there e.g. a `pid` file with the pid of the pulseaudio server?

`pactl` iirc uses a `cli` file in that folder, *if* the folder is the same, so that would exist too, if we find the correct folder. Could you check these?

**Comment by lbischof** [comment]
There is also a `pid` file in `/run/user/1000/pulse/`, but the error does not occur at the moment (`native` exists). I have found no way to reproduce the problem. 

There is no `cli` file. I will reopen the issue, when the error occurs again.
