### ISSUE TITLE
Log file location should be in XDG_DATA_HOME

### ISSUE THREAD

**Issue by zingyb** [lawl/NoiseTorch#51]
Thanks for this utility!

Presently, noisetorch outputs a log to a static filename in /tmp. It's considered a faux pas to have a static file name in the /tmp directory. I propose that NoiseTorch instead use the standard XDG_DATA_HOME (~/.local/share/ by default/unspecified). to store logs. You can see an example of this by looking at Xorg's logs at "$XDG_DATA_HOME/xorg"

#35 would also be solved with this change.

**Comment by lawl** [comment]
Agree the name shouldn't be static, as you mention there's already #35 

I really don't like using `$XDG_DATA_HOME`. It's not (essential) data, it's a temporary file. `$XDG_CACHE_HOME` seems like a better fit.

From the XDG spec:

> $XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.

> $XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.

Though even that is somewhat nebulous. XDG doesn't really have a path for "logs go here". Many programming languages provide a utility function to create temp files, and e.g. Go seems to use `$TMPDIR` and if that doesn't exist, use `/tmp`, see [here](https://golang.org/src/io/ioutil/tempfile.go?s=1419:1477#L40) and [here](https://golang.org/src/os/file_unix.go?h=tempDir#L345).

So I believe we should just use that logic, over (ab?)using some XDG path. If you have no objections I'll add that to #35

**Comment by zingyb** [comment]
You make good points - the XDG spec is a great step forward but it 
frustrates me for reasons like this. Perhaps the systemd journal if 
present, then $TMPDIR, then /tmp as an order of preference?

**Comment by lawl** [comment]
Nope, sorry, I'm hard vetoing journal or syslog, the file must be easy uploadable as it's debug output for me when users report things. I'll close this now and add it to #35

**Comment by zingyb** [comment]
`journalctl --user -t noisetorch -b > some_tmp_file` would do just that...

**Comment by lawl** [comment]
As i said, no. It's also debug output and not just logs. It doesn't belong in syslog.

**Comment by zingyb** [comment]
On 2020-08-11 14:23, lawl wrote:
>As i said, no. It's also debug output and not just logs. It doesn't belong in syslog.

It's your project, you can do what you want. But the user journal is 
different from the system journal.
