### ISSUE TITLE
Linux Mint - Silent Microphone

### ISSUE THREAD

**Issue by winterstein** [lawl/NoiseTorch#53]
Sadly, the NoiseTorch microphone is silent on my computer.

I'm running Linux Mint 20 Xfce (Cinnamon desktop), which is based off Ubuntu 20.04.

Here's a snapshot of the NoiseTorch UI:

![snapshot_2020-08-18_8709](https://user-images.githubusercontent.com/255664/90513679-ec3c4a80-e157-11ea-91e6-45c70830b508.png)

_Originally posted by @winterstein in https://github.com/lawl/NoiseTorch/issues/30#issuecomment-675452489_

**Comment by winterstein** [comment]
@lawl You asked for a copy of the log -- Where do I find that? Thanks.

**Comment by lawl** [comment]
@winterstein Hey, the noisetorch log is in `/tmp/noisetorch.log` additionally a pulseaudio log may also be helpful. `journalctl --no-pager -b /usr/bin/pulseaudio`

**Comment by winterstein** [comment]
@lawl Thank you for looking into this. Here's the files:

[noisetorch.log](https://github.com/lawl/NoiseTorch/files/5094532/noisetorch.log)

Pulseaudio output with NoiseTorch loaded:
[pulseaudio-with.log](https://github.com/lawl/NoiseTorch/files/5094539/pulseaudio-with.log)

And also Pulseaudio output without NoiseTorch loaded:
[pulseaudio-without.log](https://github.com/lawl/NoiseTorch/files/5094548/pulseaudio-without.log)

**Comment by lawl** [comment]
This all looks normal. Have you already tried the things mentioned in the [Troubleshooting](https://github.com/lawl/NoiseTorch/wiki/Troubleshooting#virtual-microphone-is-silent) section?

**Comment by winterstein** [comment]
Hello @lawl Doh! I was trying to use NoiseTorch as my system microphone, and your Troubleshooting notes clearly say:

> Make sure that you have not selected your NoiseTorch as your default microphone, e.g. via Gnome. The NoiseTorch Microphone needs to be set on individual applications and can currently not be set as the default device.

I have now got Chrome using it, and it works :+1: 

A tip for fellow Chrome users:   
You can set which microphone Chrome uses at: chrome://settings/content/microphone

@lawl Can I thank you for your time / apologise with a small gift or a donation to your chosen charity?

**Comment by lawl** [comment]
> @lawl Can I thank you for your time / apologise with a small gift or a donation to your chosen charity?

The best way to thank me doesn't involve money and is simply by telling your friends about NoiseTorch ;-) As for charities, may I suggest the [Software Freedom Conservacy](https://sfconservancy.org/)?

Please remember to close this issue if everything is resolved.
