### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by nndurj** [lawl/NoiseTorch#58]
I tried everything mentioned in the troubleshoot guide. Still its not working. 
![image](https://user-images.githubusercontent.com/1689958/92298624-b6290400-ef68-11ea-9d6d-566a2fefb4be.png)

[noisetorch-2020_09_05_10_44_00.log](https://github.com/lawl/NoiseTorch/files/5177573/noisetorch-2020_09_05_10_44_00.log)

**Comment by lawl** [comment]
2020/09/05 10:47:48 Input alsa_input.pci-0000_00_1f.3.analog-stereo, [snip] Muted:true

It sais your mic is muted.

**Comment by nndurj** [comment]
@lawl But the first bar corresponding to the headset is moving when I talk.

**Comment by lawl** [comment]
Well, pulseaudio sais it's muted, so....

You could post your pulseaudio logs and I can check if I see something, otherwise, this seems like an issue with your system that I cannot help you with. The muted info is coming directly from PulseAudio.

**Comment by nndurj** [comment]
[log.txt](https://github.com/lawl/NoiseTorch/files/5177638/log.txt)

**Comment by lawl** [comment]
I don't think that's from the same session as the NoiseTorch log above, and it's not a pulseaudio log. I need `journalctl -b /usr/bin/pulseaudio`.

**Comment by nndurj** [comment]
[journalctl.txt](https://github.com/lawl/NoiseTorch/files/5177657/journalctl.txt)

**Comment by lawl** [comment]
Sep 05 10:49:43 abacus pulseaudio[5011]: [pulseaudio] sink.c: Default and alternate sample rates are the same.

Possibly an issue with your sample rates. You could try others than 44100.

NoiseTorch reports all modules are correctly loaded into PA and there's nobody else reporting any similar issue. This is very unlikely to be an issue with NoiseTorch and more likely to be an issue with (your) PulseAudio and/or hardware.

What distribution are you using?

**Comment by nndurj** [comment]
I'm on ubuntu-mate-18.04

**Comment by lawl** [comment]
You could try it on a live usb stick with e.g. ubuntu 20.04 to see if it works there. If it does, it's you could try to figure out if there's any configuration difference between yours and the live pulseaudio. If it still doesn't, it may be an issue of PA not always playing nice with your hardware.

Unfortunately, that's pretty much all I can do for you right now, so I will close this issue, but you can let me know how it goes.

**Comment by nndurj** [comment]
@lawl thanks. Will try with usb stick. If it works, it will be a blessing for WFH and conf calls. :slightly_smiling_face:

**Comment by jacksongoode** [comment]
Was this resolved for you @nndurj ? I have a similar issue with a XPS 9370.

**Comment by mind-overflow** [comment]
Having a similar issue too, with a Trust GXT 242.
