### ISSUE TITLE
Load at startup

### ISSUE THREAD

**Issue by Cshark1** [lawl/NoiseTorch#6]
I would love to see a feature to automatically load NoiseTorch at startup

**Comment by lawl** [comment]
Hey!

Unfortunately this is currently unlikely to happen because the module currently consumes CPU even if no application is using the microphone. See [this issue](https://github.com/werman/noise-suppression-for-voice/issues/15) which in turn filed an issue on PulseAudio.

I'm not *super* opposed to it, if enough people want this. But it's something you can already achieve by configuring pulseaudio manually as described [here](https://github.com/werman/noise-suppression-for-voice).

**Comment by alx365** [comment]
Couldn't you easily check, if there is a recording application (several other apps already did this with pulse, e.g. palva and kmixer), and only **then** activate noise cancellation?

**Comment by lawl** [comment]
no, because a lot of applications require the virtual microphone to be present before they start, otherwise they don't see it as they query the device list only once on start unfortunately.

**Comment by lawl** [comment]
With [`0.7.0-beta`](https://github.com/lawl/NoiseTorch/releases/tag/0.7.0-beta) this could now be achieved by using commandline options and placing them in your desktop environments auto start.

Would this be sufficient as a solution, or did you have something else in mind?

**Comment by Cshark1** [comment]
> With [`0.7.0-beta`](https://github.com/lawl/NoiseTorch/releases/tag/0.7.0-beta) this could now be achieved by using commandline options and placing them in your desktop environments auto start.
> 
> Would this be sufficient as a solution, or did you have something else in mind?

Yes, this is enough, thank you for improving the app, also I would like to give you some feedback:

I think it is more intuitive to give the device id to the -i parameter(`noisetorch -i <DEVICE_ID`), rather than `noisetorch -s <DEVICE_ID> -i`

And also I can't run the app with sudo
![image](https://user-images.githubusercontent.com/53350732/90308668-feb14c80-dee9-11ea-8c0f-8aadeff66e58.png)

**Comment by lawl** [comment]
Yeah that may may been better, but too late to change now.

As for not being able to run it with sudo, that's because it's only in your users PATH and not in root's PATH. You'll need to specify the absolute path.

However, since the original issue here is resolved, I'll now close this.

**Comment by Razer0123** [comment]
Hello, so what is the recommended command to run this automatically on boot?

**Comment by lawl** [comment]
There's a wiki entry here: https://github.com/lawl/NoiseTorch/wiki/Start-automatically-with-Systemd

**Comment by Razer0123** [comment]
Thanks for the prompt reply, tried but seems not to be working, maybe i did something wrong

Here is my daemon
`[Unit]
Description=Noisetorch Noise Cancelling
Requires=sys-devices-pci0000:00-0000:00:01.3-0000:01:00.0-usb1-1\x2d2-1\x2d2:1.0-sound-card1-controlC1.device      loaded active plugged USB_PnP_Audio_Device
After=sys-devices-pci0000:00-0000:00:01.3-0000:01:00.0-usb1-1\x2d2-1\x2d2:1.0-sound-card1-controlC1.device      loaded active plugged USB_PnP_Audio_Device


[Service]
Type=simple
RemainAfterExit=yes
ExecStart=%h/.local/bin/noisetorch -i -s alsa_input.usb-CMEDIA_USB_PnP_Audio_Device-00.mono-fallback -t 95
ExecStop=%h/.local/bin/noisetorch -u

[Install]
WantedBy=default.target`

**Comment by Razer0123** [comment]
Could it work if i remove the requires version? seems to work if i remove it

**Comment by lawl** [comment]
I cannot provide support for people's individual system configuration, sorry.

**Comment by lnicola** [comment]
FWIW, I'm using NoiseTorch with PipeWire and it doesn't seem to be burning any CPU when no application is recording.

**Comment by qualk** [comment]
Yes, same here

**Comment by RyuunosukeDS3** [comment]
Can someone give me some help? I Have my startup config like this:

```systemd
[Unit]
Description=Noisetorch Noise Cancelling
Requires=sys-devices-pci0000:00-0000:00:08.1-0000:0a:00.3-usb3-3\x2d1-3\x2d1:1.0-sound-card1-controlC1.device
After=sys-devices-pci0000:00-0000:00:08.1-0000:0a:00.3-usb3-3\x2d1-3\x2d1:1.0-sound-card1-controlC1.device
# Depending on if you're using pulseaudio or pipewire, uncomment the correct line
After=pulseaudio.service
# After=pipewire.service

[Service]
Type=simple
RemainAfterExit=yes
ExecStart=/home/ryuunsuke/.local/bin/noisetorch -i -s "alsa_input.usb-BLUE_MICROPHONE_Blue_Snowball_201306-00.mono-fallback" -t 95
ExecStop=/home/ryuunsuke/.local/bin/noisetorch -u

[Install]
WantedBy=default.target
```
But it exits with

`PulseAudio source not found: alsa_input.usb-BLUE_MICROPHONE_Blue_Snowball_201306-00.mono-fallback`

I set the device as required, so I'm not sure why it won't load.

**Comment by lnicola** [comment]
@RyuunosukeDS3 does `systemctl --user restart noisetorch` help? I've had issues with it not working after resume (probably because the microphone was gone).

If not, does it actually work if you run that command from a terminal?

**Comment by RyuunosukeDS3** [comment]
Running it manually does work, yes!

**Comment by lnicola** [comment]
I'm not sure why that would happen (surely your USB microphone is initialized by the time you log in?).

**Comment by RyuunosukeDS3** [comment]
> I'm not sure why that would happen (surely your USB microphone is initialized by the time you log in?).

I don't know if there is a reason it wouldn't, tbh... I'm fairly sure it is...

**Comment by Razer0123** [comment]
I had to add a delay to make mine work, but suddenly stopped again
