### ISSUE TITLE
[Feature Request] Load NoiseTorch with "default"/last used device whenever starting NoiseTorch

### ISSUE THREAD

**Issue by AtilioA** [lawl/NoiseTorch#66]
I bet most users just use the same device every time they want to load NoiseTorch (I do). The last update removed the nuisance of needing to type your password, but it can get even smoother. Maybe this could be a toggle switch under the Settings section.
Think of RTX voice, which uses the last device whenever it starts.

**Comment by lawl** [comment]
I think we don't need a toggle switch. NoiseTorch should just remember the device you selected last across application restarts.

And yes, I agree, we should do that.

**Comment by AtilioA** [comment]
> You will still need to press "Load NoiseTorch", but that's intentional. For users wanting to get rid of that too...

Actually, that was my point: not having to press "Load NoiseTorch", though having the device checked on startup would be good already.

**Comment by ecyshor** [comment]
Is anybody working on this?

If not I can give it a quick try.

I just took a look at the code and looks like I should save the lastUsedDevice Id in the config file and preselect the device when the app loads if we find that config.

One other thing I had in mind is also preselecting the input if there's a single input available. 

Should I maybe also add a config which allows the user to specify that it wants to autoload NoiseTorch when the app starts? It would be disabled by default but would allow people to have noise torch start on startup and load automatically.

**Comment by AtilioA** [comment]
> Should I maybe also add a config which allows the user to specify that it wants to autoload NoiseTorch when the app starts? It would be disabled by default but would allow people to have noise torch start on startup and load automatically.

That would be great! I'm not working on it; unfortunately I know nothing about Go

**Comment by lawl** [comment]
> I just took a look at the code and looks like I should save the lastUsedDevice Id in the config file and preselect the device when the app loads if we find that config.

Yep.

> One other thing I had in mind is also preselecting the input if there's a single input available.

Sounds good. 

> Should I maybe also add a config which allows the user to specify that it wants to autoload NoiseTorch when the app starts? It would be disabled by default but would allow people to have noise torch start on startup and load automatically.

Nope, will not merge that, sorry. As I've said before, there's already the CLI for people not wanting to use the UI.

**Comment by ecyshor** [comment]
> > I just took a look at the code and looks like I should save the lastUsedDevice Id in the config file and preselect the device when the app loads if we find that config.
> 
> Yep.
> 
> > One other thing I had in mind is also preselecting the input if there's a single input available.
> 
> Sounds good.
> 
> > Should I maybe also add a config which allows the user to specify that it wants to autoload NoiseTorch when the app starts? It would be disabled by default but would allow people to have noise torch start on startup and load automatically.
> 
> Nope, will not merge that, sorry. As I've said before, there's already the CLI for people not wanting to use the UI.

Sounds good, will try to add it in the next couple of days.

As for the autoload, I just checked the systemd wiki page, makes sense to not start on startup if it consumes resources even when idle.
Would you be alright with using the default input if the client is run with the load flag and no other source id is specified?

**Comment by lawl** [comment]
> Would you be alright with using the default input if the client is run with the load flag and no other source id is specified?

Not sure about that one. So far the CLI is completely detached from anything that would touch the config file. I feel like i may bleed the UI and CLI together in weird ways. Not sure though.

**Comment by lawl** [comment]
I think the way we should handle this is that when called without a specific source it uses the default device configured in pulseaudio. Now that I read your comment again, maybe that's even what you meant. Then in the UI instead of preselecting the device when only one is available, I think we should also preselect the pulseaudio default device, if none has been explicitly written to the config file.

Since then case "preselect if one device" is only really a concern the first start, or if someone switches a USB device. Thus the logic for the UI should be

    Is there a last used device stored in the config?
    Y: Try to preselect that
          Available: good, we're done
          Unavailable: preselect pulseaudio default device
    N: preselect pulseaudio default device

And for the CLI

    Device passed as parameter?
    Y: Try use that, if unavailable, error out.
    N: use pulseaudio default device

**Comment by lawl** [comment]
Fixed in [0.8.3](https://github.com/lawl/NoiseTorch/releases/tag/0.8.3-beta). Thanks @ecyshor!
