### ISSUE TITLE
CLI broken in 0.8.0

### ISSUE THREAD

**Issue by mksaleem** [lawl/NoiseTorch#67]
Thanks a lot for the update 0.8, great not to keep putting a password. 
I am trying to load it using:
noisetorch -s "alsa_input.usb-SteelSeries_SteelSeries_Arctis_5_00000000-00.analog-chat" -i
tried it without "" too.
doesn't give any error but doesn't load either. it was working ok before the update. Can you please help.
Kind Regards

**Comment by lawl** [comment]
Sorry about that [0.8.2](https://github.com/lawl/NoiseTorch/releases/tag/0.8.2) should fix it.

**Comment by mksaleem** [comment]
Thank you, I can confirm its working fine after 0.8.2 perfectly fine.
