### ISSUE TITLE
Option to skip root privileges from CLI

### ISSUE THREAD

**Issue by YodaEmbedding** [lawl/NoiseTorch#69]
For systems that don't need root privileges to load NoiseTorch, perhaps it would be nice to allow a CLI option:

```
noisetorch --no-root -i -s "alsa_input.pci-0000_00_1f.3.analog-stereo"
```

This way, we can autostart at startup without needing to run with root.

----

Also, slightly related issue: `sudo noisetorch -i -s "alsa..."` doesn't seem to start NoiseTorch, which makes it difficult to set up a systemd startup service.

**Comment by lawl** [comment]
Why not just give the binary `CAP_SYS_RESOURCE`?

**Comment by lawl** [comment]
Unresponsive, closing.

**Comment by br0wnboi** [comment]
I see you closed it down, but could there be a autostart feature added to GUI?.

**Comment by lawl** [comment]
@br0wnboi maybe for pipewire that's possible.
