### ISSUE TITLE
.local/bin might not be in PATH

### ISSUE THREAD

**Issue by lawl** [lawl/NoiseTorch#7]
See this PR: https://github.com/lawl/NoiseTorch/pull/3

Need to find a good solution, maybe just tell people to make sure .local/bin is in their PATH

**Comment by alx365** [comment]
Hmm, dunno, something seems fishy about your icon breaking, when changing the "exec" line

**Comment by lawl** [comment]
Seems gnome doesn't accept absolute paths in `.desktop` files. It accepts neither `~/...` nor `/home/user/...`.

I have added instructions to the readme to make sure `.local/bin` in the PATH. Can't think of a way to solve this otherwise.

**Comment by alx365** [comment]
yeah i just read that, but maybe gnome will accept the $HOME, variable?

**Comment by lawl** [comment]
Nope, doesn't accept `$HOME` either.

**Comment by alx365** [comment]
That really doesn't make any sense, after all you can also call a executable from the `/` dir by just specifying the full path. e.g. `cd / && ./usr/bin/git --help`

**Comment by alx365** [comment]
But i quote from the gnome docs:
> Quoting must be done by enclosing the argument between double quotes and escaping the double quote character, backtick character ("`"), dollar sign ("$") and backslash character ("\") by preceding it with an additional backslash character.

**Comment by lawl** [comment]
Yes, according to the standard [here](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables).

At least giving it a full path without `~` or `$HOME` should definitely work, but what can I say? For some reason it doesn't, or I'm doing something wrong. I will have to look into this later.

**Comment by lawl** [comment]
Couldn't find any way to make this work, closing for now as it's at least documented in the readme, if anyone has found a solution, please reopen.
