### ISSUE TITLE
Hide or remove extra output sources

### ISSUE THREAD

**Issue by nathanfranke** [lawl/NoiseTorch#70]
```
$ noisetorch -l
Device Name: Monitor of USB Audio Device Digital Stereo (IEC958)
Device ID: alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.iec958-stereo.monitor

Device Name: USB Audio Device Multichannel
Device ID: alsa_input.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.multichannel-input

$ noisetorch -i -s "alsa_input.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.multichannel-input" -t 0

$ noisetorch -l
Device Name: Monitor of USB Audio Device Digital Stereo (IEC958)
Device ID: alsa_output.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.iec958-stereo.monitor

Device Name: USB Audio Device Multichannel
Device ID: alsa_input.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.multichannel-input

Device Name: Monitor of Null Output
Device ID: nui_mic_denoised_out.monitor

Device Name: Monitor of LADSPA Plugin Noise Suppressor for Voice (Mono) on Null Output
Device ID: nui_mic_raw_in.monitor
```

As you can see, NoiseTorch creates two outputs that I have no need to use. It really crams up my audio settings.
![image](https://user-images.githubusercontent.com/14253836/100998289-ed379300-3520-11eb-941f-daaaab5d3400.png)

**Comment by lawl** [comment]
> As you can see, NoiseTorch creates two outputs that I have no need to use.

Yes you do, because it's not possible for NoiseTorch to work otherwise. This is an artifact of how we load into pulseaudio, and I'm not aware of any other way of doing it, so nothing I can do here, sorry. If anyone does know of a way to hide these in UIs outside of NosieTorch's control, please lmk, but we can't get around creating them.

**Comment by nathanfranke** [comment]
Fair enough, provided pulseaudio doesn't provide a flag to hide or mark as dummy. In this case, this is probably more suited as a feature request for KDE's audio control.

**Comment by lawl** [comment]
Yes, if there is a flag I can set on these that makes UIs ignore them, I'm happy to do so. I don't know of one.
