### ISSUE TITLE
Deepin OS 20 low volume of sound

### ISSUE THREAD

**Issue by acrossoffwest** [lawl/NoiseTorch#73]
Deepin OS 20 low volume of sound when I'm tryning to turn on system noise cancelation it's became out laud but one moment voice going to speackers only.

![image](https://user-images.githubusercontent.com/1808737/101999631-43ee5b00-3cdf-11eb-9e7b-19c70d1f5ab2.png)

After turn on Automatic Noise Suppression cleared sound went to speackers and if I turn off system Automatic Noise Suppression voices still in speackers. Only if I unload Noisetorch it stopped 

[Log file](https://gist.github.com/acrossoffwest/17bb1d8b79581ae3f967377503ce21fd)

Please somebody help me with this problem.

**Comment by lawl** [comment]
If you're activating both this Noise Suppression in the screenshot and NoiseTorch, and can imagine that leading to some problems, this is not a supported configuration, sorry.

**Comment by acrossoffwest** [comment]
> If you're activating both this Noise Suppression in the screenshot and NoiseTorch, and can imagine that leading to some problems, this is not a supported configuration, sorry.

Ok, I got it

**Comment by acrossoffwest** [comment]
@lawl I got it. But can you help with low level  volume of sound?

**Comment by lawl** [comment]
I don't fully understand the issue there, sorry. There is a bit of a language barrier I feel.

**Comment by acrossoffwest** [comment]
I had very quiet sound from NoiseTorch Microphone but today maybe with your updates it became better. Anyway thank you for your made job.
