### ISSUE TITLE
Bluetooth headphones disconnect on unloading noisetorch

### ISSUE THREAD

**Issue by selflein** [lawl/NoiseTorch#75]
## Steps to reproduce

* Connect bluetooth headphones
* Start noisetorch and load for any input by clicking on "Load NoiseTorch"
* Start `pavucontrol`
* Unload noisetorch by clicking on "Unload NoiseTorch"
* Bluetooth headphones disconnect

Oddly, enough when not accessing the microphone loading and unloading noisetorch does not cause the bluetooth headphones to disconnect.

Log file: [noisetorch-2020_12_15_03_52_11.log](https://github.com/lawl/NoiseTorch/files/5696634/noisetorch-2020_12_15_03_52_11.log)

**Comment by lawl** [comment]
(on mobile)

Not BT related. Your pulseaudio crashes. Reason for that:

> 2020/12/15 15:52:13 Couldn't remove rlimit as root: exit status 127

Either make sure the binary has `cap_sys_resource` also after every update, or make sure pkexec doesn't return 127.

**Comment by selflein** [comment]
Oh did not see that. Sorry for the unrelated issue.

**Comment by lawl** [comment]
No reason to apologize, the UI in that situation is non existant, and I should probably fix that. So these issues help, because they help me find out where things need to be improved still.
