### ISSUE TITLE
[Issue] Noisetorch input silent, but LADSPA has an output

### ISSUE THREAD

**Issue by TobiPeterG** [lawl/NoiseTorch#78]
As stated on the troubleshooting wiki page, a issue should be opened when the noise torch input doesn't work, but the LADSPA plugin output shows an output in pavucontrol. 
Well, that's the case for me. I selected my stereo mic as input source, but noisetorch stays silent, no matter what noise suppression level I select.

Which logs are of interest?

I run Opensuse Tumbleweed with version noisetorch version 0.9.0

**Comment by lawl** [comment]
> when the noise torch input doesn't work

Can you clarify what "not works" means exactly? Also please attach the noisetorch log as described in the troubleshooting wiki page. Additionally screenshots of all pavucontrol tabs.

**Comment by TobiPeterG** [comment]
> > when the noise torch input doesn't work
> 
> Can you clarify what "doesn't work" means exactly, do you see a bar moving in pavucontrol? Also please attach the noisetorch log as described in the troubleshooting wiki page. Additionally screenshots of all pavucontrol tabs.

Of course, I'm sorry.

with "Doesn't work" I mean that the noisetorch input is always "muted" (if I speak, the noisetorch bar isn't moving).
The LADSPA plugin output bar in oavucontrol is moving though. 
The bar of my mic itself is moving as well.

The log files are here, I hope they're helpful:
[noisetorch-2020_12_22_11_52_31.log](https://github.com/lawl/NoiseTorch/files/5750807/noisetorch-2020_12_22_11_52_31.log)
[noisetorch-2020_12_22_11_56_43.log](https://github.com/lawl/NoiseTorch/files/5750808/noisetorch-2020_12_22_11_56_43.log)
[noisetorch-2020_12_23_12_04_52.log](https://github.com/lawl/NoiseTorch/files/5750809/noisetorch-2020_12_23_12_04_52.log)
[noisetorch-2020_12_23_12_07_09.log](https://github.com/lawl/NoiseTorch/files/5750811/noisetorch-2020_12_23_12_07_09.log)
[noisetorch-2020_12_23_12_12_06.log](https://github.com/lawl/NoiseTorch/files/5750812/noisetorch-2020_12_23_12_12_06.log)
[noisetorch-2020_12_23_12_18_08.log](https://github.com/lawl/NoiseTorch/files/5750813/noisetorch-2020_12_23_12_18_08.log)
[noisetorch-2020_12_29_02_18_21.log](https://github.com/lawl/NoiseTorch/files/5750814/noisetorch-2020_12_29_02_18_21.log)

The screenshots of all tabs:
![grafik](https://user-images.githubusercontent.com/19935382/103286949-98811e00-49e1-11eb-9f3b-17fefe4a7c97.png)
![grafik](https://user-images.githubusercontent.com/19935382/103286982-ac2c8480-49e1-11eb-9e66-2c903f2e5e6f.png)
![grafik](https://user-images.githubusercontent.com/19935382/103287021-bfd7eb00-49e1-11eb-8118-4d66fb05a6ff.png)
![grafik](https://user-images.githubusercontent.com/19935382/103287057-d2eabb00-49e1-11eb-8965-16777694e11e.png)
![grafik](https://user-images.githubusercontent.com/19935382/103287070-dbdb8c80-49e1-11eb-9116-27948f2cf5be.png)

**Comment by lawl** [comment]
From log `23_12_18_08`

```
2020/12/23 00:18:27 Loading supressor
2020/12/23 00:18:27 Loaded null sink as idx: 34
2020/12/23 00:18:27 Loaded ladspa sink as idx: 35
2020/12/23 00:18:27 Loaded loopback as idx: 36
2020/12/23 00:18:27 Loaded remap source as idx: 37
[...]
2020/12/23 00:18:32 Unloading pulseaudio modules
2020/12/23 00:18:32 Searching for null-sink
2020/12/23 00:18:32 Found null-sink at id [34], sending unload command
2020/12/23 00:18:32 Searching for ladspa-sink
2020/12/23 00:18:32 Searching for loopback
2020/12/23 00:18:32 Searching for remap-source
```

This looks weird pulseaudio reports the modules as loaded but when unloading them later it doesn't seem to find them.

But when you load modules again later

```
2020/12/23 00:18:32 Loading supressor
2020/12/23 00:18:32 Loaded null sink as idx: 38
2020/12/23 00:18:32 Loaded ladspa sink as idx: 39
2020/12/23 00:18:32 Loaded loopback as idx: 40
2020/12/23 00:18:32 Loaded remap source as idx: 41
```

The id increments, so pulseaudio hasn't crashed in between.

Also that doesn't seem like the standard pavucontrol, possibly `pavucontrol-qt`?

Can you please send me this again with the default pavucontrol, and *one* load after a fresh start of your PC, just to make sure pulseaudio isn't in a weird state from previous attempts? Additionally `pacmd list-modules` after it's been loaded would be helpful. Then one more question, does it say "NoiseTorch active" in the top right of the noisetorch window?

**Comment by TobiPeterG** [comment]
Yes, that is the qt version, here is the "normal" version:

![grafik](https://user-images.githubusercontent.com/19935382/103369361-36e8ae80-4aca-11eb-9e7a-9b72909ec258.png)
![grafik](https://user-images.githubusercontent.com/19935382/103369430-65668980-4aca-11eb-8795-44fbf1619d35.png)
![grafik](https://user-images.githubusercontent.com/19935382/103369436-6c8d9780-4aca-11eb-89e2-2c5f987f2c91.png)
![grafik](https://user-images.githubusercontent.com/19935382/103369450-744d3c00-4aca-11eb-9789-e00b855cc729.png)
![grafik](https://user-images.githubusercontent.com/19935382/103369456-7911f000-4aca-11eb-9619-225ac3eb6312.png)


here's the log, I restarted my PC, loaded noisetorch once, tested if it's working and got the screenshots, I did nothing in between.
I then unloaded noisetorch again.

Here's the log:
[noisetorch-2020_12_30_06_10_02.log](https://github.com/lawl/NoiseTorch/files/5755036/noisetorch-2020_12_30_06_10_02.log)

Here's `pacmd list-modules`:

`34 module(s) loaded.
    index: 0
        name: <module-device-restore>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "Lennart Poettering"
                module.description = "Automatically restore the volume/mute state of devices"
                module.version = "14.0-rebootstrapped"
    index: 1
        name: <module-stream-restore>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "Lennart Poettering"
                module.description = "Automatically restore the volume/mute/device state of streams"
                module.version = "14.0-rebootstrapped"
    index: 2
        name: <module-card-restore>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "Lennart Poettering"
                module.description = "Automatically restore profile of cards"
                module.version = "14.0-rebootstrapped"
    index: 3
        name: <module-augment-properties>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "Lennart Poettering"
                module.description = "Augment the property sets of streams with additional static information"
                module.version = "14.0-rebootstrapped"
    index: 4
        name: <module-switch-on-port-available>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "David Henningsson"
                module.description = "Switches ports and profiles when devices are plugged/unplugged"
                module.version = "14.0-rebootstrapped"
    index: 5
        name: <module-udev-detect>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "Lennart Poettering"
                module.description = "Detect available audio hardware and load matching drivers"
                module.version = "14.0-rebootstrapped"
    index: 6
        name: <module-alsa-card>
        argument: <device_id="1" name="pci-0000_01_00.1" card_name="alsa_card.pci-0000_01_00.1" namereg_fail=false tsched=yes fixed_latency_range=no ignore_dB=no deferred_volume=yes use_ucm=yes avoid_resampling=no card_properties="module-udev-detect.discovered=1">
        used: 5
        load once: no
        properties:
                module.author = "Lennart Poettering"
                module.description = "ALSA Card"
                module.version = "14.0-rebootstrapped"
    index: 7
        name: <module-alsa-card>
        argument: <device_id="2" name="usb-SJ-180517-N_1080P_Webcam-02" card_name="alsa_card.usb-SJ-180517-N_1080P_Webcam-02" namereg_fail=false tsched=yes fixed_latency_range=no ignore_dB=no deferred_volume=yes use_ucm=yes avoid_resampling=no card_properties="module-udev-detect.discovered=1">
        used: 1
        load once: no
        properties:
                module.author = "Lennart Poettering"
                module.description = "ALSA Card"
                module.version = "14.0-rebootstrapped"
    index: 8
        name: <module-alsa-card>
        argument: <device_id="0" name="pci-0000_00_1f.3" card_name="alsa_card.pci-0000_00_1f.3" namereg_fail=false tsched=yes fixed_latency_range=no ignore_dB=no deferred_volume=yes use_ucm=yes avoid_resampling=no card_properties="module-udev-detect.discovered=1">
        used: 7
        load once: no
        properties:
                module.author = "Lennart Poettering"
                module.description = "ALSA Card"
                module.version = "14.0-rebootstrapped"
    index: 9
        name: <module-bluetooth-policy>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "Frédéric Dalleau, Pali Rohár"
                module.description = "Policy module to make using bluetooth devices out-of-the-box easier"
                module.version = "14.0-rebootstrapped"
    index: 10
        name: <module-bluetooth-discover>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "João Paulo Rechi Vita"
                module.description = "Detect available Bluetooth daemon and load the corresponding discovery module"
                module.version = "14.0-rebootstrapped"
    index: 11
        name: <module-bluez5-discover>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "João Paulo Rechi Vita"
                module.description = "Detect available BlueZ 5 Bluetooth audio devices and load BlueZ 5 Bluetooth audio drivers"
                module.version = "14.0-rebootstrapped"
    index: 12
        name: <module-esound-protocol-unix>
        argument: <>
        used: -1
        load once: no
        properties:
                module.author = "Lennart Poettering"
                module.description = "ESOUND protocol (UNIX sockets)"
                module.version = "14.0-rebootstrapped"
    index: 13
        name: <module-native-protocol-unix>
        argument: <>
        used: -1
        load once: no
        properties:
                module.author = "Lennart Poettering"
                module.description = "Native protocol (UNIX sockets)"
                module.version = "14.0-rebootstrapped"
    index: 14
        name: <module-gsettings>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "Sylvain Baubeau"
                module.description = "GSettings Adapter"
                module.version = "14.0-rebootstrapped"
    index: 15
        name: <module-combine>
        argument: <>
        used: -1
        load once: no
        properties:
                module.author = "Colin Guthrie"
                module.description = "Compatibility module (module-combine rename)"
                module.version = "14.0-rebootstrapped"
    index: 16
        name: <module-combine-sink>
        argument: <>
        used: -1
        load once: no
        properties:
                module.author = "Lennart Poettering"
                module.description = "Combine multiple sinks to one"
                module.version = "14.0-rebootstrapped"
    index: 17
        name: <module-default-device-restore>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "Lennart Poettering"
                module.description = "Automatically restore the default sink and source"
                module.version = "14.0-rebootstrapped"
    index: 19
        name: <module-always-sink>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "Colin Guthrie"
                module.description = "Hält stets ein Ziel geladen, selbst wenn dies ein Null-Ziel ist"
                module.version = "14.0-rebootstrapped"
    index: 20
        name: <module-intended-roles>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "Lennart Poettering"
                module.description = "Automatically set device of streams based on intended roles of devices"
                module.version = "14.0-rebootstrapped"
    index: 21
        name: <module-console-kit>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "Lennart Poettering"
                module.description = "Create a client for each ConsoleKit session of this user"
                module.version = "14.0-rebootstrapped"
    index: 22
        name: <module-systemd-login>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "Lennart Poettering"
                module.description = "Create a client for each login session of this user"
                module.version = "14.0-rebootstrapped"
    index: 23
        name: <module-position-event-sounds>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "Lennart Poettering"
                module.description = "Position event sounds between L and R depending on the position on screen of the widget triggering them."
                module.version = "14.0-rebootstrapped"
    index: 24
        name: <module-role-cork>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "Lennart Poettering"
                module.description = "Mute & cork streams with certain roles while others exist"
                module.version = "14.0-rebootstrapped"
    index: 25
        name: <module-filter-heuristics>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "Colin Guthrie"
                module.description = "Detect when various filters are desirable"
                module.version = "14.0-rebootstrapped"
    index: 26
        name: <module-filter-apply>
        argument: <>
        used: -1
        load once: yes
        properties:
                module.author = "Colin Guthrie"
                module.description = "Load filter sinks automatically when needed"
                module.version = "14.0-rebootstrapped"
    index: 27
        name: <module-x11-publish>
        argument: <display=:0 xauthority=/run/user/1000/xauth_lhprKY>
        used: -1
        load once: no
        properties:
                module.author = "Lennart Poettering"
                module.description = "X11 credential publisher"
                module.version = "14.0-rebootstrapped"
    index: 28
        name: <module-x11-cork-request>
        argument: <display=:0 xauthority=/run/user/1000/xauth_lhprKY>
        used: -1
        load once: no
        properties:
                module.author = "Lennart Poettering"
                module.description = "Synthesize X11 media key events when cork/uncork is requested"
                module.version = "14.0-rebootstrapped"
    index: 29
        name: <module-x11-xsmp>
        argument: <display=:0 xauthority=/run/user/1000/xauth_lhprKY session_manager=local/Tobias:@/tmp/.ICE-unix/15024,unix/Tobias:/tmp/.ICE-unix/15024>
        used: -1
        load once: no
        properties:
                module.author = "Lennart Poettering"
                module.description = "X11 session management"
                module.version = "14.0-rebootstrapped"
    index: 34
        name: <module-null-sink>
        argument: <sink_name=nui_mic_denoised_out rate=48000>
        used: 4
        load once: no
        properties:
                module.author = "Lennart Poettering"
                module.description = "Getaktetes NULL-Ziel"
                module.version = "14.0-rebootstrapped"
    index: 35
        name: <module-ladspa-sink>
        argument: <sink_name=nui_mic_raw_in sink_master=nui_mic_denoised_out label=noise_suppressor_mono plugin=/tmp/librnnoise-707125582.so control=24>
        used: 3
        load once: no
        properties:

    index: 36
        name: <module-loopback>
        argument: <source=alsa_input.pci-0000_00_1f.3.analog-stereo sink=nui_mic_raw_in channels=1 latency_msec=1 source_dont_move=true sink_dont_move=true>
        used: -1
        load once: no
        properties:
                module.author = "Pierre-Louis Bossart"
                module.description = "Loopback from source to sink"
                module.version = "14.0-rebootstrapped"
    index: 37
        name: <module-remap-source>
        argument: <master=nui_mic_denoised_out.monitor source_name=nui_mic_remap source_properties="device.description='NoiseTorch Microphone'">
        used: 1
        load once: no
        properties:
                module.author = "Stefan Huber"
                module.description = "Virtual channel remapping source"
                module.version = "14.0-rebootstrapped"
    index: 38
        name: <module-cli-protocol-unix>
        argument: <>
        used: -1
        load once: no
        properties:
                module.author = "Lennart Poettering"
                module.description = "Command line interface protocol (UNIX sockets)"
                module.version = "14.0-rebootstrapped"
`

I have to admit that I loaded noisetorch a second time to get those, I hope they're still helpful, if not, I'm sorry and I'll get those logs again ofc.

And yes, it says noisetorch active in the up right corner. :D

**Comment by lawl** [comment]
Thanks, well, I see the same behavior that I have no explanation for where NoiseTorch doesn't find the sinks to unload but pulseaudio sais they're there. Two more questions:

a) I see your using pulse 14, what distro is this so i can spin it up in a VM?
b) did you install NT from an OS repo or using the binary from github or built it from source?

**Comment by TobiPeterG** [comment]
> Thanks, well, I see the same behavior that I have no explanation for where NoiseTorch doesn't find the sinks to unload but pulseaudio sais they're there. Two more questions:
> 
> a) I see your using pulse 14, what distro is this so i can spin it up in a VM?
> b) did you install NT from an OS repo or using the binary from github or built it from source?

I use OpenSUSE Tumbleweed, I installed Noisetorch using the file provided by you in the release tab (latest).

**Comment by lawl** [comment]
> I use OpenSUSE Tumbleweed, I installed Noisetorch using the file provided by you in the release tab (latest).

Thanks, I'll try spinning that up in a VM to see if that reproduces it. I don't really have another idea at the moment.

**Comment by lawl** [comment]
Hey, I didn't get to spin up an OpenSUSE VM, but I couldn't reproduce this with pulse 14, so I don't think that's it. Could you try it in a fresh VM to see if it's reproducible there too?

**Comment by itsanov** [comment]
Fedora 33, PulseAudio 14.0, same issue.
Please let me know what info to provide.

**Comment by lawl** [comment]
@itsanov can you reproduce the issue in a VM with a fresh install?

**Comment by itsanov** [comment]
@lawl Will it be sufficient to boot from Fedora Live image from USB and try there?

**Comment by lawl** [comment]
@itsanov If it works then yes, it's an issue with your config, if it doesn't work, it's not enough because a VM also abstracts the hardware, ruling that out.

**Comment by TobiPeterG** [comment]
> @itsanov If it works then yes, it's an issue with your config, if it doesn't work, it's not enough because a VM also abstracts the hardware, ruling that out.

Well, since it works with my Webcam selected as input it seems to work in general.
But selecting my stereo mic doesn't work.

**Comment by itsanov** [comment]
My ALSA is also reporting the internal mic as stereo. I have no webcam.
I have installed [WebRTC-audio-processing](https://freedesktop.org/software/pulseaudio/webrtc-audio-processing/) and it works just fine. Setting up WebRTC is easy like installing one package from repository 
`sudo dnf install webrtc-audio-processing`
and adding some lines to /etc/pulse/default.pa
```
.nofail
load-module module-echo-cancel aec_method=webrtc source_name=echosource
set-default-source echosource
.fail
```

**Comment by itsanov** [comment]
I tested with Fedora 33 Live and Fedora 33 in Gnome Boxes.
In both results are almost identical. It kind of works. Noise is removed, but to hear the voice, you have to boost the mic up to 100% and it is still very quiet and very very distorted. And there is a 2-3 sec. delay. 
In Boxes it sounds a bit better, but with a greater lag.

**Comment by itsanov** [comment]
OK, solved here. The problem is because of stereo mic reported by also. I don't know is it really a stereo or it's a trick for input sound amplification. Anyway, I used [this](https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting#Another_Possible_Cause) tutorial to remap single channel to input source. Then I select remapped  input in NoiseTorch and it works fine (with mic volume at 100%)
@TobiPeterG try at your side.

**Comment by lawl** [comment]
@itsanov Great find! I've added this to the troubleshooting page now. Thanks!

**Comment by lawl** [comment]
I assume this is solved now.
