### ISSUE TITLE
Setting RLIMIT with setcap

### ISSUE THREAD

**Issue by mrichar1** [lawl/NoiseTorch#80]
I've just started playing with noisetorch, and I'm a bit unhappy about using polkit to give the app full superuser permissions.

I see in the wiki there's a request for any suggestions on how to better handle it, so here's my thoughts...

Instead fo full root, it looks like giving CAP_SYS_RESOURCE capability is enough, i.e:
```
sudo setcap 'CAP_SYS_RESOURCE=+ep' ~/.local/bin/noisetorch
```

My first suggestion would be to just add this as an installation step in the documentation - it's not difficult to run, and it lets people know why superuser privs are needed.

If you are worried that people might miss this step, then the code could be changed to something like (pseudo-code):

```
if not getcap('CAP_SYS_RESOURCE', binary):
  # Prompt for super user rights to set capability
  setcap(('CAP_SYS_RESOURCE', binary)
```

That way the super-user prompt only occurs once, for a specific limited action, and then never again (unless the capability is removed).

**Comment by lawl** [comment]
Thanks for the feedback.

> My first suggestion would be to just add this as an installation step in the documentation - it's not difficult to run, and it lets people know why superuser privs are needed.

Totally fair. This is something i missed from before we used capabilities.

> If you are worried that people might miss this step, then the code could be changed to something like [...]

The code does already do something like this the first time you give it root. Unfortunately it's not *just* when it's installed, but also when installing an update. via the self-updater, so it still does need a way to elevate and set CAP_SYS_RESOURCE.

**Comment by mrichar1** [comment]
That's great, thanks!

Yes I don't think there's a way of modifying the file during update such that capabilities would be preserved - so it would need re-added after each update.

A check on startup might be the best approach to simplify things - if nothing else it gives an easy location to insert information/instructions on what/why things are happenning... part of the reason I raised this issue is that the polkit prompt came without any context, which may put people off using it.
