### ISSUE TITLE
Noisetorch no longer works

### ISSUE THREAD

**Issue by mritunjaymusale** [lawl/NoiseTorch#82]
Ever since I switched to my new pc(x570-e with 5900x), Noisetorch has become shoddy at best.
It works once when I install it, after that it says noisetorch loaded and the microphone is visible in discord and teams aswell but there's no output.
It  happened on Manjaro and Mint20

**Comment by lawl** [comment]
https://github.com/lawl/NoiseTorch/wiki/Troubleshooting

**Comment by mritunjaymusale** [comment]
OMG!It was the stupid pulseaudio conf that cause this whole nonsense.
Thanks for the tip, fixed and closing issue.
