### ISSUE TITLE
Support for multiple NoiseTorch microphones

### ISSUE THREAD

**Issue by SeriousBug** [lawl/NoiseTorch#84]
Hi,

I have 2 microphones, I use each microphone in different programs. Both microphones are plugged in, and appear in NoiseTorch's UI. However, choosing one microphone deactivates the other. I would love to have the option to apply NoiseTorch separately to both microphones.

In other words, I have 2 input devices plugged in (Headphones, Built-in), and only 1 NoiseTorch microphone that chooses one of either source. I would like to create 2 NoiseTorch microphones (NoiseTorch Headphones, NoiseTorch Built-in).

**Comment by lawl** [comment]
I think this would certainly be useful, but i don't want the maintenance burden of that.
