### ISSUE TITLE
noise disconects when unload

### ISSUE THREAD

**Issue by Taza53** [lawl/NoiseTorch#88]
Hi,
In discord if the app is open(In a voice call), and I unload noise torch the mic and the speaker get disconnected. So I can't hear anyone or talk. All option for changing mic and speaker are gone. If I use the script below to unload noisetorch I get the expected result, and it switches from the noisetorch mic to the normal mic.

**Comment by lawl** [comment]
I think this is likely a duplicate of #76 . Can you check if the PID of pulseaudio changes before and after unloading? I.e. it crashes and is restarted?

**Comment by Taza53** [comment]
yep pulse audio crashes.

**Comment by lawl** [comment]
Closing this as duplicate of #76 then.
