### ISSUE TITLE
System Tray support

### ISSUE THREAD

**Issue by HeuFui** [lawl/NoiseTorch#89]
This is just an enhancement. I really love NoiseTorch as of now. However...

... it would be nice if NoiseTorch supported Close to Tray as Cadmus does instead of being just another window. Especially since its functionality is a once in a session kind of thing. 

In any case, thanks for making it happen. That alone is enough to grant you a big thank you.

**Comment by lawl** [comment]
System tray won't happen as e.g. gnome doesn't support it by default anymore. We'll need to figure out something, but systray isn't it. With pipewire noisetorch will need to keep running in the background so i'm forced to address this soon-ish, and i have some ideas.
