### ISSUE TITLE
Always in "inconsistent state"

### ISSUE THREAD

**Issue by Xenorio** [lawl/NoiseTorch#9]
When i load NoiseTorch, i'm always getting the "Inconsistent state, please unload first." error

Unloading and reloading does not change anything

noisetorch.log output:
```
2020/07/16 18:53:06 Application starting. Version: 0.3.4-beta
2020/07/16 18:53:06 Checking if config needs to be initialized
2020/07/16 18:53:06 Wrote temp librnnoise to: /tmp/librnnoise-791479153.so
2020/07/16 18:53:06 Checking for updates
2020/07/16 18:53:12 Loading supressor
2020/07/16 18:53:12 Loaded null sink as idx: 27
2020/07/16 18:53:12 PulseAudio error: commandLoadModule -> Module initialization failed
```

**Comment by lawl** [comment]
Can you grab me the last 100 or so lines from your PulseAudio log and throw them in a gist/pastebin with

    journalctl -n100 --no-pager -b /usr/bin/pulseaudio

**Comment by Xenorio** [comment]
Here you go: [https://pastebin.com/mPCUfQU2](https://pastebin.com/mPCUfQU2)

Basically just spamming "AppArmor profile could not be retrieved."

(Tried to load NoiseTorch again before getting the log to make sure it's not from something else)

**Comment by lawl** [comment]
That apparmor message is from a buggy ubuntu patch, but i believe that's not the cause. Can you try a couple hundred lines more so i can see the real messages?

**Comment by lawl** [comment]
Oh btw, you can unload that ubuntu patch with

    pacmd unload-module module-snap-policy

To verify thats not the cause and should make the appsrmor spam go away. Only temporarily do this though. Allows snaps to escape from their sandbox.

**Comment by Xenorio** [comment]
This seems to be relevant (It's the only other output i could get and seems to relate to noise reduction stuff):

```
Jul 16 20:52:46 pop-os pulseaudio[3178]: Failed to load LADSPA plugin: file not found
Jul 16 20:52:46 pop-os pulseaudio[3178]: Failed to load module "module-ladspa-sink" (argument: "sink_name=nui_mic_raw_in sink_master=nui_mic_denoised_out label=noise_suppressor_mono plugin=/tmp/librnnoise-883136844.so control=95"): initialization failed.
```

**Comment by lawl** [comment]
Failed to load LADSPA plugin: file not found

Yep that's it. Now, I have absolutely no idea why though. Nt writes a shared object to /tmp that is then loaded into pulse, and for some pulse reason it doesn't find the file.

It's getting late here though so I'll have to look at this tomorrow.

**Comment by Xenorio** [comment]
Welp, just tell me what you need me to run when you have the time and i'll run it

Also, have a good night^^

**Comment by Xenorio** [comment]
Just listed my /tmp ([https://i.imgur.com/9Gkz9pW.png](https://i.imgur.com/9Gkz9pW.png)) and i can find a "librnnoise-883136844.so" in there. So if that's this LADSPA plugin thingy, it's definitely being written to there.

Maybe a wrong path somewhere? Or pulse tries to load it before it's being written?

**Comment by Xenorio** [comment]
In case it's a permission issue, `ls -l /tmp/librnnoise-883136844.so` returns this:
```
-rw------- 1 xenorio xenorio 284520 Jul 16 20:38 /tmp/librnnoise-883136844.so
```
xenorio is the account i run both NoiseTorch and the pulse daemon (pulseaudio -D) with

**Comment by lawl** [comment]
Are you building from source or using the prebuilt binary?

Can you run `ldd /tmp/librnnoise.........so`

**Comment by Xenorio** [comment]
Using prebuilt binary. But if that matters, i'll just go build it from source and see what happens.

ldd returns this:
```
linux-vdso.so.1 (0x00007fff976f0000)
libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc60904b000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc608efc000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc608ee1000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc608cef000)
/lib64/ld-linux-x86-64.so.2 (0x00007fc609291000)
```

**Comment by Xenorio** [comment]
Same behavior on a fresh build from master

**Comment by lawl** [comment]
Super weird. If you start noisetorch, it'll write the file to `/tmp`, can you the run `chmod 777 /tmp/librnnoise-....so` before attempting to load to so we can rule out a permission issue?

**Comment by Xenorio** [comment]
did that, still no change

**Comment by Xenorio** [comment]
uuuuh... i just found the issue.
had to update pulse. now it seems to be working.
soooo, guess i can close this now
