### ISSUE TITLE
Noisetorch unusable, unable to get required capabilities

### ISSUE THREAD

**Issue by DarwinAwardWinner** [lawl/NoiseTorch#90]
After updating NoiseTorch, it now displays this screen on startup:

![image](https://user-images.githubusercontent.com/228145/106684620-c6372500-6594-11eb-9d78-85500c17b4ff.png)

Clicking the button and entering my password simply returns me to the same screen. There is no way to get past it and actually use the app.

**Comment by DarwinAwardWinner** [comment]
This is Ubuntu 20.10.

**Comment by lawl** [comment]
Can you attach logs?

**Comment by DarwinAwardWinner** [comment]
It appears that NoiseTorch produces a new log each time I push the button. Here is one such log:

[noisetorch-2021_02_03_05_59_47.log](https://github.com/lawl/NoiseTorch/files/5917913/noisetorch-2021_02_03_05_59_47.log)

Here is what `getcap` returns on the noisetorch binary:

```
$ getcap /home/ryan/.local/bin/noisetorch
/home/ryan/.local/bin/noisetorch cap_sys_resource=eip
```

**Comment by lawl** [comment]
Well, NoiseTorch thinks it doesn't have `CAP_SYS_RESOURCE`

    2021/02/03 05:59:47 CAP_SYS_RESOURCE: false

Why? No clue, would need a way to reproduce this to analyze.

**Comment by UchihaSR** [comment]
i am getting the same issue. how to get the log details?

**Comment by DarwinAwardWinner** [comment]
@UchihaSR https://github.com/lawl/NoiseTorch/wiki/Troubleshooting

@lawl Is there any way I can debug it from my end and send you some additional information?

**Comment by lawl** [comment]
@DarwinAwardWinner You would need to build it from source probably and then either use a debugger or add debug statements.

https://github.com/lawl/NoiseTorch/blob/master/main.go#L93

`hasCapSysResource(getCurrentCaps())` apparently returns false when it shouldn't. The code path on our side for this is pretty simple, so could be a bug in the capability package, could be something else. I don't really have anything to go off here, so unfortunately I can't offer much assistance beyond from "use a debugger" and "insert debug statements" currently.

**Comment by DarwinAwardWinner** [comment]
What would be the code to print the full set of capabilities read by `getCurrentCaps()` (and maybe also `getSelfFileCaps()`)? I can add that in and try to build it from source.

**Comment by lawl** [comment]
log.Printf("CAPS: %s\n", (*getCurrentCaps()).String())

should print

    CAPS: { effective="empty" permitted="empty" inheritable="empty" bounding="full" }

if it doesn't have the capabilities and

    CAPS: { effective="sys_resource" permitted="sys_resource" inheritable="empty" bounding="full" }

if they're set correctly.

**Comment by UchihaSR** [comment]
[log.txt](https://github.com/lawl/NoiseTorch/files/5918163/log.txt)

**Comment by lawl** [comment]
@UchihaSR You are having a different problem

    2021/02/03 16:41:00 Couldn't setcap self as root: exit status 127

Your pkexec is misconfigured and doesn't allow us to elevate privileges. Either fix your pkexec. Or run

    sudo setcap 'CAP_SYS_RESOURCE=+ep' ~/.local/bin/noisetorch


after each update [according to the install instructions](https://github.com/lawl/NoiseTorch#download--install)

**Comment by DarwinAwardWinner** [comment]
It looks like the running process is not getting the same caps as the executable:

```
$ getcap bin/noisetorch 
bin/noisetorch cap_sys_resource=eip
$ grep CAP /tmp/noisetorch-2021_02_03_06_53_07.log
2021/02/03 06:53:07 CAP_SYS_RESOURCE: false
2021/02/03 06:53:07 CURRENT CAPS: { effective="empty" permitted="empty" inheritable="empty" bounding="full" }
2021/02/03 06:53:07 EXECUTABLE CAPS: { effective="sys_resource" permitted="sys_resource" inheritable="sys_resource" }
```

Is there some OS security policy that could globally disable these capabilities regardless of what is set on the file? I haven't configured anything like this, as far as I know. It should just be whatever Ubuntu's default is.

Note: previous versions of NoiseTorch would ask for my password every time when I enabled it.

**Comment by lawl** [comment]
> Is there some OS security policy that could globally disable these capabilities regardless of what is set on the file? I haven't configured anything like this, as far as I know. It should just be whatever Ubuntu's default is.

I honestly don't know. Some things you could look into are maybe you're using a FUSE fs like ecryptfs on your `/home`? I've had some issues when doing some for fancy filesystem stuff on ecryptfs before. Or maybe something like AppArmor strips the capabilities? Or again, there could be some bug the the capability package that makes it read them wrong.

> Note: previous versions of NoiseTorch would ask for my password every time when I enabled it.

Yeah this shouldn't have happened for a while now.

**Comment by DarwinAwardWinner** [comment]
Hmm, this system is on a ZFS filesystem. I don't *think* that should cause an issue, especially considering that `getcap` seems to return the right answer, but maybe this has something to do with it?

**Comment by lawl** [comment]
As I said, no clue unfortunately, just shots in the dark.

**Comment by DarwinAwardWinner** [comment]
I think I've figured out the problem: https://stackoverflow.com/questions/38965819/file-capabilities-do-not-transfer-to-process-once-executed

Mounting a filesystem with nosuid also disables all capabilities set on files on the filesystem. My home directory is indeed mounted nosuid:

```
$ mount | grep home/ryan" "
rpool/calliope/home/ryan on /home/ryan type zfs (rw,nosuid,nodev,relatime,xattr,posixacl)
```

**Comment by lawl** [comment]
Ah, that makes sense. Probably an edge case i'm not going to handle in code though, but I'll add it to the troubleshooting wiki page.

**Comment by DarwinAwardWinner** [comment]
Sure enough, after `sudo zfs set setuid=on rpool/calliope/home/ryan`, everything works. I think it might be worth checking for this case in code, because the failure mode is rather opaque. You don't need to check the specific case of nosuid, but if the executable has the required capabilities and the process doesn't, it would be helpful to add a warning linking to the Troubleshooting page to the app window.

**Comment by lawl** [comment]
Fair enough.

47d8188b3adb4361c125d582ea4c7cbb1e0be581 Untested though, but it's low enough risk to push untested :)

Please remember to close the issue if you think this is solved now.

**Comment by JLarky** [comment]
I had the same problem with `ecryptfs` so I just moved the app into `/opt` which uses `ext4`
