### ISSUE TITLE
Causing audio delay in OBS 

### ISSUE THREAD

**Issue by lorddickfist** [lawl/NoiseTorch#94]
Hello running Arch Linux using the git version(I have tried source and the other two packages as well) arch package, and I am having audio delay issues on for other sources (not the microphone) when I stream. 
I have noticed this issue after using my Blackmagic capture card I only notice the audio delay when I have Noisetorch active, delay increases the longer I stream.

I do not notice any microphone delay on its own in my pavucontrol, nor in the stream only the other sources. If I restart the noisetorch OBS audio devices are no longer selectable and pavucontrol will not work.

Here's my sources 
`pactl list sources short
0	alsa_output.usb-Kingston_HyperX_Quadcast_4110-00.analog-stereo.monitor	module-alsa-card.c	s16le 2ch 44100Hz	RUNNING
1	alsa_input.usb-Kingston_HyperX_Quadcast_4110-00.analog-stereo	module-alsa-card.c	s16le 2ch 44100Hz	RUNNING
2	alsa_output.pci-0000_1f_00.1.hdmi-stereo.monitor	module-alsa-card.c	16le 2ch 44100Hz	RUNNING
3	alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.mono-chat.monitor	module-alsa-card.c	s16le 1ch 44100Hz	RUNNING
4	alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.stereo-game.monitor	module-alsa-card.c	s16le 2ch 44100Hz	RUNNING
5	alsa_input.usb-SteelSeries_SteelSeries_Arctis_7-00.mono-chat	module-alsa-card.c	s16le 1ch 44100Hz	RUNNING
6	alsa_output.pci-0000_21_00.3.analog-stereo.monitor	module-alsa-card.c	16le 2ch 44100Hz	RUNNING
7	nui_mic_denoised_out.monitor	module-null-sink.c	s16le 2ch 48000Hz	UNNING
8	nui_mic_raw_in.monitor	module-ladspa-sink.c	float32le 2ch 48000Hz	RUNNING
9	nui_mic_remap	module-remap-source.c	s16le 2ch 48000Hz	RUNNING`

I have re-installed noisetorch, obs, and have rebuilt my pulseaudio recently.

[modules](http://ix.io/2OLb)

[latest log file ](https://ghostbin.co/paste/gnn6x)

**Comment by lawl** [comment]
> Hello running Arch Linux using the git version(I have tried source and the other two packages as well) arch package

https://github.com/lawl/NoiseTorch#third-party-packages-like-aur

Sorry, I don't support broken packages. Please file a report with your package maintainer of follow the instructions with an official package.
