### ISSUE TITLE
noisetorch -u doesn't work

### ISSUE THREAD

**Issue by matclab** [lawl/NoiseTorch#95]
Running `noisetorch -s alsa_input.usb-Logitech_USB_Headset_Logitech_USB_Headset-00.mono-fallback -i` works well,
 but neither `noisetorch -s alsa_input.usb-Logitech_USB_Headset_Logitech_USB_Headset-00.mono-fallback -u` not `noisetorch -u`  unloads noisetorch (Only after launching the GUI and unloading noisetorch I see pulseaudio stop using 25% CPU).

**Comment by matclab** [comment]
Oups, I forgot to thank you for this usefull tool !

**Comment by lawl** [comment]
Thanks for reporting this. This is actually already fixed in master 335b8a2567eff46169a37011849870c9f2c2cc3b however, I haven't made a release with this yet. Fix for this will roll out with the next release.
