### ISSUE TITLE
Automaticly detect new microphone

### ISSUE THREAD

**Issue by oscardssmith** [lawl/NoiseTorch#97]
Is there a way to make noisetorch automatically detect when I plug in a new microphone and auto-switch to using it as input?

**Comment by lawl** [comment]
Detecting it, as in show uo in the UI, that would be posdible i think but we currently don't do that.

Automatically switching to it, as in having loaded noisetorch already and then start denoising a different microphone? That's currently not possible with the way we do things i think.

**Comment by oscardssmith** [comment]
darn. Is there a way to control noisetorch from command line then so I can automatically load a new microphone with a simple command line command?

**Comment by lawl** [comment]
Why don't you just try `noisetorch -h` and see what happens?

**Comment by lawl** [comment]
i assume this is solved then.
