### ISSUE TITLE
[Feature Request] Can you add speech enhancement measuring parameters?

### ISSUE THREAD

**Issue by RXAldreezee** [lawl/NoiseTorch#98]
Hi, Great Project! Can you add speech enhancement measuring parameters? Examples are: Segmental Signal to Noise Ratio(SegSNR), Log-Likelihood Ratio, Latency (fr. Mic to Output of filter) and Perceptual Evaluation of Speech Quality (PESQ)? To measure the program's performance and for comparison. Thank you.

**Comment by lawl** [comment]
No. This isn't a research project on speech enhancement, it's an application for endusers. If you want to know these i suggest you look up rnnoise yourself.

**Comment by RXAldreezee** [comment]
Thank you.
