### ISSUE TITLE
(question)Result of training model file

### ISSUE THREAD

**Issue by astralis111** [lawl/NoiseTorch#99]
Hi, I'm looking for the location of the trained model file. Can you please help me? Thank you.

**Comment by lawl** [comment]
Probably need to ask upstream [rnnoise](https://github.com/xiph/rnnoise) for that. Afaik they only publish the quantized model embedded here: https://github.com/xiph/rnnoise/blob/master/src/rnn_data.c

**Comment by lawl** [comment]
assume this is solved.
